### ISSUE TITLE
Choosing a specific color will show a photo gallery containing only clothing in this color.

### ISSUE THREAD

**Issue by alinadivante** [vuestorefront/vue-storefront#1327]
As new user of the vue storefront, I expect that by selecting a color, I will only see available photos for this filtr, not for all configurations.

**Example:**
Choosing a black blouse, where two photos are available for this color, I can browse the gallery. However, only one picture will be shown for green or yellow color.

![image](https://user-images.githubusercontent.com/36628922/41700999-f38d525c-752a-11e8-928f-d9bd54321e07.png)

**Comment by nuovecode** [comment]
Hi! ok that's could be a configuration. Do you agree?

**Comment by ymaheshwari1** [comment]
I am trying to achieve the above-mentioned functionality but get a triplet of the images when doing so.
I have seen other PRs and issues related to it and found that if we remove the entries from the image_attributes then it will work fine.

I wanted to know two things:
1. How the media_gallery of the configurable children is used in the product_gallery?
2. When defining the mergeConfigurableChildren to false, then the images are mapped from the **image_attrbutes** from the config file. So what is the use of media_gallery inside the configurable_children inside the product?

Thank you for your help.
