### ISSUE TITLE
Add customizable virtual products support

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#1344]
http://demo-magento2.vuestorefront.io/luma-yoga-for-life.html

**Comment by mcspronko** [comment]
Hi @pkarw 
Is there a plan to include this feature into the upcoming releases?
Thanks

**Comment by pkarw** [comment]
Hi @mcspronko! There is a partial solution for that waiting for changes after CR: 
https://github.com/DivanteLtd/vue-storefront/pull/2130

Would it be helpful to Your case?
