### ISSUE TITLE
Magento2 one login (external checkout)

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#1381]
Currently, when You're logged in to Vue storefront and uses the External Checkout (going to Magento checkout for just placing an order - https://medium.com/p/af415843ac86?source=user_profile---------10-------------------) Your session is being held even after returning back to VS.

However, If you're not authorized in VS -> go to Magento2 for checkout -> authorize -> go back -> the session is not being transferred from M2 -> VS.

We need to pass the authorization back to VS to keep the user logged in

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
