### ISSUE TITLE
Move entity types registration and gql queries on the module level

### ISSUE THREAD

**Issue by yuriboyko** [vuestorefront/vue-storefront#2028]
## What is the motivation for adding / enhancing this feature?
Currently all queries are located on the searchAdapter side each of them is related to the certain module work . So it probably make sense to move queries for search adapter on the module level

so each module should have  search adapters folders structure 
something like this: 
'search-adapter' 
-> 'graphql' 
-> 'api' 

where should be a registeration of all required for this module search adapter entity types

**Comment by lukeromanowicz** [comment]
Related to #2239

**Comment by pkarw** [comment]
Done!
