### ISSUE TITLE
Checkbox variant selection

### ISSUE THREAD

**Issue by ghost** [vuestorefront/vue-storefront#2089]
## What is the motivation for adding / enhancing this feature?
On https://hoversport.no/p/V0100373/hoverboard-bluetooth-rd-8, you have a product with various variants or options. When clicking on one of the options, it selects all of the options, it then shows a wrong color option in the shopping cart, further on when you go to checkout you will then have the right color option in Magento checkout. 

A suggestion is to fix it so that when you click on one option, it doesn't select all the options and doesn't show a wrong variant name in the shopping cart on the storefront.

**Comment by pkarw** [comment]
Hi, it requires some debugging - please do some test changing the custom options type from "checkbox" to "radio" in Magento2 and then syncing the products (I believe it's a correct option type as You can select only one, correct?)

Anyway the checkbox options should be tested + fixed

**Comment by pkarw** [comment]
@Decntdefalt  can You provide us with elasticsearch dump (`npm dump` in the `vue-storefront-api` then send us the  `vue-storefront-api/var/catalog.json`) @patzick can You check this one? It's strange as after short debugging of `ProductCustomOptions.vue` it seems like we're setting correct values so maybe just the UI part is broken.

**Comment by pkarw** [comment]
This is connected with #1675
