### ISSUE TITLE
Extend the db tool for zero-downtime indexing

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#2156]
## What is the motivation for adding / enhancing this feature?

 I think that would be great to add the `--destIndex` option to https://github.com/DivanteLtd/vue-storefront-api/blob/290b18c29996d0033d1f97d893fe9bf22e674e37/scripts/db.js#L7

After adding this feature You would be able to use the following sequence of commands:
`npm run db new -- --indexName=myTemporaryIndex`
`export INDEX_NAME=myTemporaryIndex`
**>>run mage2vuestoeront process in here <<**
`npm run db rebuild — --indexName=myTemporaryIndex destIndexName=vue_storefront_catalog`

By having this in place there could be full db reindex made with zero down-time - the last command publishes the reindexed database.
Probably we should extend db tool with one more command: `delete` (`npm run db delete`) or `rename` (or both!) for removing the indexes (the temporary ones)

**Comment by Cyclonecode** [comment]
The main problem here as I see it is how to figure out the name of the old index that should be deleted? For instance, if I have `vue_storefront_catalog_<timestamp>` and create a temporary index `vue_storefront_temporary` and reindex this and then point the alias `vue_storefront_catalog` to it, how to know name of the previous index? Maybe I am just a little confused when looking on the code db tool. Would be great to get some more input on how to best implement this so we can get going =)

**Comment by Cyclonecode** [comment]
I would be glad to try to implement this one, but I think we need to talk a little more on how this really should work. Right now I am feeling that it is pretty hard to figure out the old index which should be removed. Would be nice to get some more input on this.

**Comment by pkarw** [comment]
Hi @Cyclonecode in this scheme You don't have to figure out the old index name as it's using the alias `vue_storefront_catalog`. So all You need to do is to add this `destIndexName` switch - then it works like this:
1. You're creating new index `npm run db new -- --indexName=myTemporaryIndex`
2. You 're switching `mage2vuestorefront` to use it by `export INDEX_NAME=myTemporaryIndex`
3. You're running `mage2vuestorefront` to index into `myTemporaryIndex`
4. You're renaming/reindexing the `myTemporaryIndex` to `vue_storefront_catalog`  -> `npm run db rebuild — --indexName=myTemporaryIndex destIndexName=vue_storefront_catalog`

The `myTemporaryIndex` is probably a subject to change
