### ISSUE TITLE
Make OneSignal integration

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#2228]
## Description

Create module integrating One Signal ( https://onesignal.com/ ) with Vue Storefront. It'll allow awesome service for Push Notifications
Feel free to ask me for details on slack if you have any questions

**Comment by lzgrzebski** [comment]
will take this one

**Comment by filrak** [comment]
@idziakjakub please confirm your collaboration invitation and assign yourself ;)
