### ISSUE TITLE
Add: Get Chrome / Firefox badge for IE users

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#2268]
## What is the motivation for adding/enhancing this feature?

VS is not working great on IE (however it should work just fine on Edge :-)). We should rather display the modern browser recommendation instead of a broken website (as we do today)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
