### ISSUE TITLE
Add the Downloadable product configuration 

### ISSUE THREAD

**Issue by ibugaj** [vuestorefront/vue-storefront#2315]
## Current behavior
Product without price - can't add it to the Cart

## Expected behavior
There probably shouldn't be product without price, because user can't buy it.

## Steps to reproduce the issue
1. Find product without price, for example: https://demo.storefrontcloud.io/p/240-LV09/luma-yoga-for-life
1. Click on **Add to cart** button

see:
![image](https://user-images.githubusercontent.com/47220013/52075526-d0c91900-258c-11e9-85b7-b71c230c034f.png)

## Environment details
https://demo.storefrontcloud.io

**Comment by mcspronko** [comment]
Working on this one.

**Comment by MarcoGrecoBitbull** [comment]
solved, we doing pull request right now

**Comment by mcspronko** [comment]
Ok, thanks.

**Comment by ibugaj** [comment]
Product provided as example still is without price. Now when I try to add it to cart I get notification "Please specify product link(s)."
Checked on https://test.storefrontcloud.io/p/240-LV09/luma-yoga-for-life

**Comment by pkarw** [comment]
OK, so this is Feature Requests. We're not currently supporting Downloadable products properly. We need to extend [mage2vuestorefront]() to get the product links: https://devdocs.magento.com/swagger/#!/downloadableLinkRepositoryV1 - and support them using the kind of `ProductCustomOptions.ts` logic (to configure the price based on selected links/options)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
