### ISSUE TITLE
Add Klevu Search support

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#2381]
## What is the motivation for adding / enhancing this feature?

Klevu Search API could be integrated with our Search component.

## What are the acceptance criteria 

* `KlevuSearch` module added - extending/overriding the Vuex methods for Search methods
* ... or KlevuSearch component added - ready to be used in the theme

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
