### ISSUE TITLE
Separate legacy installation guide from standard one

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#2467]
## What is the motivation for adding/enhancing this feature?
Sounds like many devs don't read the guide carefully enough and follow both legacy and standard steps at the same time. Splitting the guide into two separated ones would help newcomers with the installation process as developers are used to simply copy-paste all there is without much of a reading.

## What are the acceptance criteria 
* there are two separated pages in docs: one containing standard installation guide and one with legacy installation guide

# Can you complete this feature request by yourself?
Yes, but not in the closest future

**Comment by janmyszkier** [comment]
@lukeromanowicz
WHY should the legacy setup be supported / listed at all? isn't it deprecated and it's OK to only leave it in the old commits?

**Comment by lukeromanowicz** [comment]
Some developers decide to go with legacy way for performance sake, especially when using macbooks or windows. Legacy way is still viable in specific cases, although it could be renamed, updated and better described when exactly you can benefit from it.

**Comment by pkarw** [comment]
That’s good point. @kkdg can you take care?

I guess we should even streamline the installation process further.

Eg: we can include vsfapi (the whole app) as a dependency (using npm) and have just single docker-compose - how does it sound? Maybe the next step.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
