### ISSUE TITLE
Add vs-api endpoint for indexing the products

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#2486]
## What is the motivation for adding / enhancing this feature?

Currently `vue-storefront-api` is accessing ElasticSearch just in read-only mode. The `src/api/catalog.js` is not accepting any other endpoints than `_search`. This is good approach regarding the security, however with new `magento2-vsbridge-indexer` and `magento1-vsbrdige-indexer` users must connect these modules directly to Elastic without the vs-api in the middle. It won't work with cloud deployments (like storefrontcloud.io) where there is no public access to Elasticsearch instance.

We should extend the `catalog.js`:

* add htaccess authorization over ElasticSearch
* add the following endpoints:
* `bulk`
* `create`
* `refresh`
* `exists`
* `delete`
* `putMapping`
* `deleteByQuery` 

Details: https://github.com/DivanteLtd/magento2-vsbridge-indexer/blob/master/src/module-vsbridge-indexer-core/Elasticsearch/Client.php

## What are the acceptance criteria 

* native indexer could be connected to `vue-storefront-api`
* authorization works

**Comment by mdanilowicz** [comment]
In my opinion, we should create new microservice that will be a connection interface to ES. Then we will be able to secure connections by IP checking etc.
