### ISSUE TITLE
Restock notification function

### ISSUE THREAD

**Issue by michhy** [vuestorefront/vue-storefront#2562]
Hello, 

Love vue storefront a lot and learning how to build my own theme for plugging vs to my magento system.

Would like to know if magento's 'Restock notification' function will be activated in vs later too?

Thanks a lot!

**Comment by pkarw** [comment]
@filrak it will be hard for me to take it (due to time constraints) I'll leave it unassigned maybe somebody can take care sooner

**Comment by pkarw** [comment]
@michhy this feature isn't yet planned on our roadmap, would be great if someone could take care of it

**Comment by michhy** [comment]
thank you piotr, just a nice to have function only :)
