### ISSUE TITLE
Codacy code quality scan

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#2596]
## What is the motivation for adding/enhancing this feature?
Improving the project code quality and prevent regression over time

## What are the acceptance criteria 
* codacy scan added to PR checks
* codacy status in README.md

# Can you complete this feature request by yourself?
No, I believe the Repo Owner should take care of this one.

## Additional information
There are ~180 issues that should be addressed. We should plan how to handle it.
![image](https://user-images.githubusercontent.com/46789227/54434589-ebb3af00-472e-11e9-9c96-53b3384d62d6.png)

**Comment by pkarw** [comment]
I believe that @patzick or @filrak will be able to take this one sooner than me
