### ISSUE TITLE
Outdated vue-offline dependency without babel

### ISSUE THREAD

**Issue by bartdominiak** [vuestorefront/vue-storefront#2633]
## Current behavior
Vue-offline is outdated and doesn't have webpack and babel in version `1.0.8`. This behavior brakes code on IE, with unreadable syntax like arrow functions and const.

## Expected behavior
We should update this lib to newer version, and add support for IE11+

## Steps to reproduce the issue
Just open demo.storefrontcloud.io on IE11+

# Can you handle fixing this bug by yourself?
Yes

**Comment by pkarw** [comment]
@bartdominiak that's great. How about checking the other libs vs. IE11?
