### ISSUE TITLE
Add to cart from wishlist and add to cart from product listing

### ISSUE THREAD

**Issue by WGoldsworthy** [vuestorefront/vue-storefront#2637]
## What is the motivation for adding / enhancing this feature?

1. User add items that regularly purchases to a wishlist/favourites. When they want to reorder items from wishlist, they are able to add products directly from the wishlist into the cart without the need to go into each products individual page. This provides a quicker user journey for customers that are regularly purchasing the same items. 
1. Users can go into a category listing. Users can add products to the cart from the product tile without having to go into each individual product page.

## What are the acceptance criteria 

* User can see a quantity and add button for each product in their wishlist.
* When clicking the add button, the desired quantity of that product is added to the cart.
* User can see a quantity and add button under each product tile.
* When clicking the add button, the desired quantity of that product is added to the cart.

# Can you complete this feature request by yourself?

No

## Additional information

The tesco tiles for example: 
![](https://user-images.githubusercontent.com/9464386/54820558-8f551000-4c97-11e9-80ac-8f5b949b287e.png)

**Comment by Hackbard** [comment]
I will give it a try

**Comment by GabiDivante** [comment]
Hi, @WGoldsworthy @Hackbard what about configurable products for which I have to choose for example color and size to add them to the cart?

**Comment by Hackbard** [comment]
> Hi, @WGoldsworthy @Hackbard what about configurable products for which I have to choose for example color and size to add them to the cart?

Good Question, i have the same Question within another Ticket.
Maybe there should be a Standard Overlay what we can use everywhere if it is a  Configurable products ? Or i would make a if that the button is only renderd when it is simple.

**Comment by GabiDivante** [comment]
Hi @Hackbard 
I think this task is much more complex. It all depends on how many the product has attributes that you have to choose to add it to the cart. The display method may differ depending on the attributes - I do not know if it is possible to propose a default solution or design that will be reusable. Besides, there are also other types of products like bundle or grouped.
@pkarw hat do you think about it? Should we implement only for simple products or try to design a solution for all types?

**Comment by Hackbard** [comment]
@GabiDivante i was thinking of that too.
I would they to implement it just for simple products.

Did you consider that this can be a configurable thing? So you can provide within the .env files that you only want it for product type XY ?

**Comment by GabiDivante** [comment]
I do not know how to solve it technically, @pkarw do you have any suggestions?

**Comment by pkarw** [comment]
Hi there! Thanks for this discussion - it’s important and was a good one :-) typically we’d need an additional popup for configurable to just let the user configure the product from the list view. As we don’t have it for the current default design I do propose to have some workaround: simples can be added from the list and in the case of configruables the button should be named like “Configure” or even “Add to cart” but then - redirect the user to the configurable product page. What do You think in that? Maybe not the best one but at least giving the user a chance to set the required options. The same mode should be for the other types of products (bundle, grouped ...)

**Comment by Hackbard** [comment]
> Hi there! Thanks for this discussion - it’s important and was a good one :-) typically we’d need an additional popup for configurable to just let the user configure the product from the list view. As we don’t have it for the current default design I do propose to have some workaround: simples can be added from the list and in the case of configruables the button should be named like “Configure” or even “Add to cart” but then - redirect the user to the configurable product page. What do You think in that? Maybe not the best one but at least giving the user a chance to set the required options. The same mode should be for the other types of products (bundle, grouped ...)

Sounds good to me. But then we need another ticket to make this popup

**Comment by Dnd-Dboy** [comment]
I will work on this during hackathon :)

**Comment by Dnd-Dboy** [comment]
Done, you can find my PR here: https://github.com/DivanteLtd/vue-storefront/pull/3645

**Comment by adityasharma7** [comment]
I think after the merge of https://github.com/DivanteLtd/vue-storefront/pull/3812, 1.11 only offers add to cart from wishlist, not product listing the changelog seems misleading and need to be updated.

https://github.com/DivanteLtd/vue-storefront/pull/3812/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR14

For reference comment and commit that removes it from the product listing for now in https://github.com/DivanteLtd/vue-storefront/pull/3812

- https://github.com/DivanteLtd/vue-storefront/pull/3812#issuecomment-554989652
- https://github.com/DivanteLtd/vue-storefront/pull/3812/commits/25d8cb8ab685527550afe236f54009342dc0e1fb
