### ISSUE TITLE
Confusing password validation when creating an account while placing an order

### ISSUE THREAD

**Issue by GabiDivante** [vuestorefront/vue-storefront#2700]
## Current behavior
-> When creating an account while placing an order, the **validation of the entered password is carried out at the end when attempting to place an order.** 
-> If user provide too short password  (for ex mypass) at **first the validation message about password min length is shown**. 
-> After re-entering longer password, the **client must go through all the checkout steps and try to place an order again.**
-> **Next the validation message containing information about the additional requirements for building the password is shown** for a short time - so that the user is not able to read it. 
-> After again re-entering a more complex password, the **client must go through all the checkout steps again.**

## Expected behavior
Validation of the password structure should take place as soon as it is entered (so that the customer can correct it right away), and the validation message should be visible until the password requirements are met (so that the client knows what the requirements are).

As a result, the customer does not have to go through the entire shopping path again and again just because he has entered a password that does not meet the standards.

## Steps to reproduce the issue
1. Open https://demo.storefrontcloud.io/
1. Add any product to the cart
1.  Click 'Go to checkout' 
1. Fill in personal details section
1. Check option 'I want to create an account' and provide two identical, not complex and short passwords (for ex 'mypass')
1. Accept Terms and conditions
1.  Fill in shipping and payment sections
1. Go to review order
1. Mark checkbox 'I agree to Terms and conditions' 
1. Click on 'Place the order' -> the first validation message is shown (password is too short)
1. Go to personal details section and provide longer password (for ex. 'mypassword')
1. Go through all the next steps again
1. Click on 'Place the order' again -> the second validation message is shown (password have to meet a few requirements)
1. Go back to personal details section again 
1. Provide more complex password according to the requirements
1. Go through all the next steps again
1. Successfully place the order. 

## Can you handle fixing this bug by yourself?
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
* Browser: many
* OS: Windows 10

**Comment by ananth-iyer** [comment]
@GabiDivante I have found that before sending the place order request, it sends create user request with new passwords sent to Magento 2 through VS API. Then Magento validates password length or strength and if not valid then returns the error message to VS API then it error message is shown in Vue Storefront.

It is likely a Magento 2 feature but there is no API to get password configuration from M2. And every Magento 2 store will have different password configurations.

I will check this issue and update you the workaround to resolve it.

**Comment by pkarw** [comment]
I can confirm @ananth-iyer - there would be no other way to validate the passwords - we must wait till the form is being posted to check the results against Magento2 user register/login endpoints :(

**Comment by ananth-iyer** [comment]
@pkarw Could be we have password configuration same like Magento in config.xml and local.xml for VS?

**Comment by grimasod** [comment]
It's also confusing when the password validation passes and the order is submitted successfully. There are multiple messages about being logged in and proceeding to the checkout. Also, I just did a test on the Develop branch and my cart still contained items after the Order Confirmation was displayed. This could cause confusion possibly lead to customers submitting their order twice.

All the information needed to create an account is collected in the first step, "Personal Details". So, I think it should be possible to validate / create the account after clicking "Continue to Shipping".

**Comment by grimasod** [comment]
Another solution is to remove the "I want to create an account" checkbox and instead have a "Create an account" link, just like the "login to your account" link, except it would open on the "Register" form. It already works, almost perfectly, by clicking on the Account icon to create the account while on the Checkout page

**Comment by fancydev18** [comment]
Another solution is to remove the "I want to create an account" checkbox during the checkout. Just let the customer pay and complete order. Anything extra will reduce conversions.

On the screen shown after placing the order (after everything is paid etc), have a button to 
*Create an account* to save your addresses and be eligible to potential discounts

This will also work well with Instant checkout.
