### ISSUE TITLE
Offline Sync Notification

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#2753]
## What is the motivation for adding/enhancing this feature?
Extracting state synchronization to a visual layer and notifying a user about successful/unsuccessful actions when he's back online would simplify and solve a lot of issues regarding offline actions. It should be used in ordering out of stock products, products that have additional business validation, invalid address fields, expired coupons, etc.

## What are the acceptance criteria 
* When a user gets into offline mode, an additional icon should be shown in the menu. Could be a bell, could be something like:
![image](https://user-images.githubusercontent.com/46789227/56320300-22cd1400-6164-11e9-9073-93b30605c331.png) ( to be discussed with a UX Specialist) 
* When there are queued actions to be synchronized, an icon can be clicked to display a dropdown list with actions to sync and status (to sync, in progress, failure). Should look like more or less like facebook notifications
* Successful actions are removed from the dropdown list
* When there is a failure, the user should see the notification and the icon should be red to indicate that there are some problems to be fixed with a short description of the issue.
* (If applies) a user can click failed action to correct the issue, click "reload" icon to retry or click "X" to remove that action from the list (simply ignore the issue)
* When a user is online and the list is empty, the status icon should disappear.
* Following scenarios are covered:
  * a user is trying to order a product that is out of stock
  * a user is trying to order more products than there are in stock
  * there are issues with checkout details that a user has entered while finishing the order
* the whole mechanism has extension friendly architecture to add additional error handlers in an easy way

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case, the Developer should create a branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
In the future, it could be extended with push notification support if a user has already left the website before sync was fully finished.

A UX desing would be very helpful for this feature :)

**Comment by lukeromanowicz** [comment]
@StasiekDivante could you, please, propose some UI design for this one?

**Comment by filrak** [comment]
I think we should discuss it first before assigning Stasiek. Neat idea ;)

**Comment by filrak** [comment]
Ok so after reading this I'm up to this idea, would be very useful and will for sure improve offline experience.
I'm not totally up to proposed UX implementation parts like

> When a user gets into offline mode, an additional icon should be shown in the menu. Could be a bell, could be something like:

We have badge for this

 From my PoV there should be an icon *somewhere* that informs user that some data hasn't been yet sent to a server. I'm talking only about POST requests so newsletter subscription, user account data change, order, (what else?). Once the user is back online the "list" should clear itself and only failed requests should left there with proper indicators and error messages.

The only exception is that for orders it shouldn't replace the current mechanism (but can be stored in this actions list too) since I don't believe there is any scenario where order can be safely processed in the background and it should be handled the way it is now.

**Comment by lukeromanowicz** [comment]
> We have badge for this 
I have never noticed that although I've been working on offline browsing fixing for a few hours. I must be blind then :D 
> The only exception is that for orders it shouldn't replace the current mechanism (but can be stored in this actions list too) since I don't believe there is any scenario where order can be safely processed in the background and it should be handled the way it is now.
Agree, at the time of writing this post that mechanism was not working so I wasn't aware of it.

**Comment by filrak** [comment]
I guess it's still not working :d
