### ISSUE TITLE
Add config to set the way orders are displayed in 'My orders' (for an email address or user account)

### ISSUE THREAD

**Issue by GabiDivante** [vuestorefront/vue-storefront#2756]
## What is the motivation for adding / enhancing this feature?

**Currently, 'My orders' displays orders, which are assigned to a given email address and not to a user account.**
As a result, we always see all orders made from this email address and not only those placed from the account created for this email address.

Situations where this may be a problem:

1. After removing the user account (from the magento level) and re-creating it by the user, the 'My orders' tab will display old orders for the previous account.
1. Similarly, when I place orders without creating an account for a given email address, later when I set up an account, in 'My Orders' I will see orders that I made without creating an account. 

**Due to the fact that setting up an account does not require any confirmation - anyone can set up an account for my email and see all orders I have previously made.**

But it can also be useful:

1. If creating an account requires confirmation - after setting up an account for my email, I can see the whole history of orders placed before creating an account.

**So we should add the option of setting in the config how we want to display orders:**

* for email address
* for the user's account.
If there will be an additional authorization for creating an account, we can safely use the first option.

**Related problem: An order during which a new customer account is created is not assigned to this account**

If I create a new account while placing an order - this order is not assigned to the created account. In Magneto, the new user has no orders and the new order is visible as made by Guest. In My orders, a new order is visible only because all orders for the email are currently displayed, not for the user account.

From the user point of view, I create the order in parallel with the creation of an account, so this order should already be saved as placed by the client with the account and not as submitted by the Guest.

## What are the acceptance criteria 

* [ ] In config, you can set how orders should be displayed (for email address / for a user account).
* [ ] After choosing the option of displaying orders for the email address: in the 'My orders' tab, all orders placed to the email address for which the account was created are visible.
* [ ] After choosing the option of displaying orders for the customer's account: in the 'My orders' tab, all orders placed after logging in to this account are visible.
* [ ] After creating an account while placing an order, I can see in "My orders" first order that I made (regardless of the setting selected in the config for displaying orders). This order has displayed my account details in the 'Author' section.

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by ArturDivante** [comment]
@pkarw 
There is a problem with this concept. 

When orders are connected only with email adress (and not to the user account), then every change of user email adress, will result in losing all records of order made by that customer. 

Customer can change email adresses for many reasons:
- Lost access/password to previous mailbox
- Spam flood in old mailbox :)
- Found better email provider
- Change names after marriage  
- etc.

whatever the reason - user changing his email adddess, will also lose access to whole his order history. I don't think it's acceptable.

**Comment by GabiDivante** [comment]
@pkarw so should we always display orders for a user account?

**Comment by pkarw** [comment]
Hi thanks for the comments. I think that we should keep it as a configurable option. There is a lot of use cases around guest orders to registered customer conversions. Let’s have it configurable and probably the customer-id based filtering should be just the default option

**Comment by rain2o** [comment]
This is related to https://github.com/DivanteLtd/magento2-rest-client/issues/8. A PR has been submitted to filter by customer_id only as that is the standard way to do this.

The other scenarios you mentioned @GabiDivante regarding a customer wanting to see past orders that were placed as a guest or the bug in which the user registers in checkout and the order is seen as Guest in Magento I believe are a natural caveat to having a secure e-commerce implementation. A solution to this problem could be to implement a feature where customer's can prove a Guest order belongs to them and then assign it to their account. We are planning to implement a feature like this in our VSF/M2 shop at some point.
