### ISSUE TITLE
Define store info once and make storeId much dynamic.

### ISSUE THREAD

**Issue by Devors** [vuestorefront/vue-storefront#2785]
## What is the motivation for adding / enhancing this feature?
Make this moment much simple and dynamic.
https://github.com/DivanteLtd/vue-storefront/blob/release/1.9/src/modules/magento-2-cms/components/CmsData.vue#L57

Makes config simpler

## What are the acceptance criteria 
Always use "defaultStoreCode": "XX", then all stuff (es, tax, i18n) can be placed once in storeViews.

## Can you complete this feature request by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
I don't quite get this idea :-) Could You come with the PR please?
