### ISSUE TITLE
Doc update on multistores needed

### ISSUE THREAD

**Issue by janmyszkier** [vuestorefront/vue-storefront#2870]
* [ ] clarify what's the disabled flag for
the doc at https://docs.vuestorefront.io/guide/integrations/multistore.html#vue-storefront-and-vue-storefront-api-configuration currently lists both stores as :

```
        "disabled": true,
```

It's not clear what this flag does if setting them to disabled make them work.

* [ ] explain how to get the `storeId` from magento (possibly with images)
Right now it's not clear where to get these values from storeview? store/group? we're within storeview config node which leads to confusion since this seems to be actually about magento STORE and not storeview.
* [ ] clarify how should be `multistore` used in connection to `defaultStoreCode`
* [ ] clarify what is "default store"
the doc currently mentions some default store `en` that uses `vue_storefront_catalog` elasticsearch index, but the store is never defined in storeviews. Why? this "magic" should be explained to the enduser.

**Comment by FaustTobias** [comment]
The outdated documentation also caused some trouble for us. We tried setting the italian storeView to `disabled` using the flag (which is still documented like this btw). But the [Upgrade notes from 1.10 -> 1.11](https://docs.vuestorefront.io/v1/guide/upgrade-notes/#_1-10-1-11) state, that this flag is no longer supported.

In the end, we had to remove the italian store from the `default.json`, which the docs also do not recommend.
