### ISSUE TITLE
Links in the changelog.md

### ISSUE THREAD

**Issue by ResuBaka** [vuestorefront/vue-storefront#2951]
# Summary
[summary]: #summary

Add a hyperlink to the user and PR. To have them when you open the changelog.md 

# Motivation
[motivation]: #motivation

This would be grade to have so when you clone the repository or open the changelog file directly you can go the the PR and not need to search it or go the the releases page. 

One why this could be done without having long lines is to use a [reference-style link](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links).

**Comment by cnviradiya** [comment]
Yesh @ResuBaka 
It's great if an add anchor link

@jablpiotrek, Should I generate PR for the same?

**Comment by lukeromanowicz** [comment]
Github does it automatically. Not sure if it's necessary
