### ISSUE TITLE
Per module configs instead of one big json

### ISSUE THREAD

**Issue by Zanuff** [vuestorefront/vue-storefront#2967]
## What is the motivation for adding / enhancing this feature?
Currently the configs are kept in one big file, which may quickly increase in size, resulting in hard to read huge config chunk.

## What are the acceptance criteria 
Keep module config files per module for better separation. The architectural design is up to vue storefront team.

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Thanks! This sounds good to me, however it makes the docs/initial config a little bit less straightforward. I belive we should discuss it or implement at first stage as an optional feature (so we don’t scatter the main config but rather extend the module API to let the developers to provide their own config providers)

**Comment by pkarw** [comment]
Related to #2760

**Comment by filrak** [comment]
This is actually idea we talked about with @patzick.i believe it is something we should think about in vs 2.0. It was proven to work well with Vue itself
