### ISSUE TITLE
cli: proxy support, similar to vue-cli

### ISSUE THREAD

**Issue by fancydev18** [vuestorefront/vue-storefront#2974]
## What is the motivation for adding / enhancing this feature?

Please support devServer & devServer.proxy options in the upcoming cli, just like vue-cli:
https://cli.vuejs.org/config/#devserver

I think this functionality is built into webpack.

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

This would enable working locally without CORS. The same vue storefront host can also take API requests and pass them through to a proxy, then return the answer seamlessly back to client.

**Comment by pkarw** [comment]
@filrak I bet we need Your feedback on that :)
