### ISSUE TITLE
[ Nicer to have ] Optimize webpack build time

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#3140]
* removing unnecessary loaders
* minimize the scope of loaders

https://webpack.js.org/guides/build-performance/

**Comment by lukeromanowicz** [comment]
It's also worth to add PNP. I'm working on it but unfortunately, it requires a lot of effort :)

**Comment by jissereitsma** [comment]
I dived into this a bit: The `babel-loader` could be improved a bit by adding a `cacheDirectory` flag to it: 
```js
loader: 'babel-loader?cacheDirectory',
```

Disabling the following line speeds up a bit as well (and obviously disables source mapping, but maybe this is not needed by everyone):
```js
devtool: 'source-map',
```

**Comment by pschaub** [comment]
Maybe the devtool `source-map` should be replaced with something else from this list with faster build time:
https://webpack.js.org/configuration/devtool/
