### ISSUE TITLE
Can't install bootstrap, bulma and external vue css component 

### ISSUE THREAD

**Issue by wdrdres3qew5ts21** [vuestorefront/vue-storefront#3149]
I had problem with css rendering. Here I use vue-boostrap but after Vue-Storefront render complete my boostrap button will got override by Vue-Storefront css ?!
So how can I install it properly with external vue-component or css framework ?
How I can install external component properly do you guy have any advice because this is very important to many people.
![image](https://user-images.githubusercontent.com/25000903/60254895-f9b1c800-98f8-11e9-863a-310bec09c037.png)

**Comment by Gotsira** [comment]
I am having the same problem too. There is some problem with the babel/polyfill but still wondering how to solve this issue.

**Comment by psmyrek** [comment]
@wdrdres3qew5ts21 @Gotsira I just installed `bootstrap-vue` and `bootstrap`:

`yarn add bootstrap-vue bootstrap`

then I imported `bootstrap-vue` with styles in default theme in `src\themes\default\index.js`:

```
import BootstrapVue from 'bootstrap-vue'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-vue/dist/bootstrap-vue.css'

Vue.use(BootstrapVue)
```

and finally I edited the `Error.vue` component similarly like you did:

```
<div class="container">
  <div>
    <b-button variant="success">It works!</b-button>
    <b-button variant="warning">It works!</b-button>
    <b-button variant="danger">It works!</b-button>
  </div>
  <h2>
    {{ $t("Something went wrong ...") }}
  </h2>
</div>
```

and it works. Bootstrap styles are not overwritten by vue-storefront styles.

![bootstrap-vue-is-working](https://user-images.githubusercontent.com/56868128/69419182-453b9700-0d1c-11ea-810c-1ede6c333548.png)

Could you provide more details on how to reproduce your issue? Have you changed files or styles other than shown on screenshot?
