### ISSUE TITLE
Simplify config

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#3177]
* Put only config options that are mandatory in local config, document others,
* Lower the number of config options required for the user

**Comment by nuovecode** [comment]
I believe there could be 2 different configuration files. 
- Those of environment that are different between dev, stage and prod and that shouldn't change during upgrades. Example: Server, elastic and Magento url
- Those of application that change during the upgrade but they usually remain the same among the evironments.

**Comment by juho-jaakkola** [comment]
I don't think this is necessarily needed. The [config](https://github.com/lorenwest/node-config) package already [supports](https://github.com/lorenwest/node-config/wiki/Environment-Variables#node_config_env) splitting of the config files.

In my current project we simply define the `NODE_CONFIG_ENV` environment variable for each environment.

If I for example define this for the staging environment:
```
export NODE_CONFIG_ENV=shared,staging
```
it will make the `config` library to automatically combine these three configuration files:
 - `config/default.json`
 - `config/shared.json`
 - `config/staging.json`

Thanks to this I don't have to use a `local.json` file that contains all the entries from `default.json`. Instead I can override only the entries that I want to be different in my own project.
