### ISSUE TITLE
Reposition Add to Cart button to an always visible position in Mobile view

### ISSUE THREAD

**Issue by pmaojo** [vuestorefront/vue-storefront#3272]
## What is the motivation for adding/enhancing this feature?
When using a mobile to browse the app, on the product view, it would be easier to purchase an item if the Add to Cart is visible. This way the user won't have to look for the Add to Cart button, it will be accessible.

## What are the acceptance criteria 
* [  ] Add to cart button pops up from on the bottom of the screen when the user scrolls under the title.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for the developer.
This is an idea needs design and implementation. It is an easy good first request.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
This is a quick and not detailed mockup

![Captura de pantalla 2019-07-23 a las 12 12 26](https://user-images.githubusercontent.com/411551/61743474-46b87b00-ad8d-11e9-8ba2-e89034127cce.png)

**Comment by bilawal0** [comment]
I will take care of this issue.

**Comment by mentizm** [comment]
i will have a look on this issue at hackathon #17 in brunswick
