### ISSUE TITLE
IE 11 : Buttons and images

### ISSUE THREAD

**Issue by CompactCodeEU** [vuestorefront/vue-storefront#3307]
## Current behavior
The buttons are not clickable on Internet Explorer like the login button, cart button and add to cart button.
Also the add to cart does not work.

Furthermore the images are not loaded.

This has been tested on Internet Explorer 11 on https://demo.storefrontcloud.io and confirmed on our own testing enviroment.

## Expected behavior
We suspect it has something to do with local caching and Service workers. It should always have a fallback for browser that do not support that.

We also can not find a compatibility list but found another issue that stated 'We support all major browsers'. Not sure if IE is still in that list.

## Steps to reproduce the issue
Open Internet Explorer 11

1. Surf to https://demo.storefrontcloud.io
1. Go to a product --> see placeholder images
1. Try to open menu, add a product or login --> buttons not working

## Can you handle fixing this bug by yourself?
* [X ] YES
* [ ] NO

But with no time limit. We are building a Vuestorefront project for one of our customers and frontend development will occur after the API connection  is implemented.

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
* Browser: Internet Explorer 11
* OS:  Windows 10
* Node:  NA
* Code Version: NA

**Comment by pkarw** [comment]
This is related to https://github.com/DivanteLtd/vue-storefront/issues/1266

**Comment by pkarw** [comment]
It requires tweaking the Babel configs - please check the comments to #1266

**Comment by CompactCodeEU** [comment]
Ok thanks for the reference!

**Comment by CompactCodeEU** [comment]
I will keep this issue open as a reference for people who are searching the same until it has been resolved.

**Comment by pkarw** [comment]
OK i'll change it to feature request as it well .. it's not a bug :)
