### ISSUE TITLE
Social Media Login

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#3316]
Feature Request here moved from https://github.com/DivanteLtd/vue-storefront-api/issues/318

## What is the motivation for adding / enhancing this feature?
Logging to and fetching data through social media like facebook.

## What are the acceptance criteria 
* Login with facebook
* Login with google
can be separate modules + nice layer for implementing additional ones

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by dixitdeepak** [comment]
We can use the firebase for social media login. 
https://firebase.google.com/docs/auth/web/firebaseui
