### ISSUE TITLE
Problems storing products added to the Wishlist

### ISSUE THREAD

**Issue by alinadivante** [vuestorefront/vue-storefront#3362]
##Relates to:
#3348 

## Steps to reproduce the issue
**Scenario 1:**

1. Log in into vsf
1. Add any products to wishlist 
1. Log out
1. Make sure that wishlist is empty now
1. Refresh page

**Scenario 2:**

1. Log in into vsf
1. Add any products to wishlist 
1. Log out
1. Make sure that wishlist is empty now
1. Again add any products to wishlist (as guest)
1. Log in into vsf (use the same account as in step 1)
1. Check Wislist

## Current behavior
**Scenario 1:**
After refreshing the page, products occur again on Wishlist  (despite the user being logged out)

**Scenario 2:**
There are only products added by guest (in step 5). The previously added products (in step 2) are gone.

## Expected behavior
If logged in customer add products to the wishlist, the list will be stored in Magento i.e. products within the list will not disappear unless customer removes it manually. 

If not-logged in customer add products to the wishlist, the list will be stored in browser cache i.e. products within the list will not disappear unless customer clears the browser cache. 

If the customer will add products as a not-logged in and then logged into his account, products added to the wishlist before the login will be merged with products in the stored wishlist. 

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by pkarw** [comment]
@alinadivante the thing is that wishlist is not being synced with Magento there is still a FR for that waiting to be implemented. So we’re having just single source of wishlist which is browser cache

**Comment by pkarw** [comment]
@patzick i'm not sure if this is an issue or just a feature request but it'd be better to double-check it

**Comment by pkarw** [comment]
Related: #709
