### ISSUE TITLE
Theme upgrade CLI tool

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#3406]
## What is the motivation for adding/enhancing this feature?
When updating VueStorefront we also have to update the theme. Due to copying the whole default theme and modifying it, we usually have to manually track down all the changes even in components that were not modified. We need a tool that will do it automatically. We will solve it with the fallback mechanism in 2.0 but a walkaround for now is highly needed. 

## What are the acceptance criteria 
* CLI tool shipped along with the application that helps with a painless upgrade of preexisting theme that was created by copying and modifying the default one.
* the tool asks for the base vsf version (by commit id, branch or a tag)
* the tool asks for the target vsf version (by commit id, branch or a tag)
* the tool asks for the theme to update
* the tool automatically compares and updates unmodified theme files to the target version
* the tool creates a list of files that should be manually updated because they were modified
* the tool should be implemented as part of vue storefront cli but also can be a standalone script
* there are docs how to use it
* the tool should be shipped as dev dependency

## Can you complete this feature request by yourself?
* [x] YES, but not anytime soon
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Hi @lukeromanowicz this idea is really cool; however, I don't see a chance to have it before 19 of September (release date of 1.11); switching the milestone to 2.0rc1

**Comment by juho-jaakkola** [comment]
See also: https://github.com/DivanteLtd/vue-storefront/issues/3519

**Comment by lukeromanowicz** [comment]
@pkarw after 2.0 it's not needed anymore cause there will be the theme fallback
