### ISSUE TITLE
Add unit tests for `core/modules/catalog`

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#3459]
## What is the motivation for adding/enhancing this feature?
Add unit tests for the module. Reference/example: 

* https://github.com/DivanteLtd/vue-storefront/tree/develop/core/modules/catalog-next/test/unit
* https://github.com/DivanteLtd/vue-storefront/blob/develop/core/modules/url/test/unit/formatCategoryLink.spec.ts

## What are the acceptance criteria 
* [ ] all the actions should be tested
* [ ] all the helpers should be tested
* [ ] all the mutations should be tested

**Comment by lukeromanowicz** [comment]
@pkarw not sure if there is much point in writing tests for the old catalog. It's a legacy module anyway.

**Comment by pkarw** [comment]
It’s still being used by Product.vue page and nothing shows it’s going to disappear in foreseeable future :)
