### ISSUE TITLE
Integrate conventional commits with commitlint

### ISSUE THREAD

**Issue by defudef** [vuestorefront/vue-storefront#3476]
## What is the motivation for adding / enhancing this feature?
When I checked commits, everyone writes them in a different way.
Conventional commits help keep them simple, short and in the same format. This convention speed up understands what kind of changes have been done.
To validate commit messages I suggest using Git pre-commit hook.

Conventional commits spec: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
Example commit message: `feat: commitlint integration`
This package is well known and helpful: https://www.npmjs.com/package/commitlint
But I'm open to suggestions.

## What are the acceptance criteria 

* [ ] Integrated and configured the commitlint
* [ ] Developer is not able to commit an invalid message

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by lukeromanowicz** [comment]
Great idea :+1:

@filrak @patzick @pkarw  What do you guys think?

**Comment by pkarw** [comment]
I like the idea 👍
