### ISSUE TITLE
Move translations from core to theme

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#3481]
## What is the motivation for adding / enhancing this feature?

Translations are tightly coupled with theme therefore should be in a theme. Different themes could have different translations.

## What are the acceptance criteria 

* [ ] Move translations from `core/i18n/resource/i18`n to `{themeroot}/i18n`

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Totally removing it from the core? I mean: we’ve got translations in theme that can override the core ones (I belive); i thought we should keep them in the core for a fallback if anyone is using vsf core and just misss the i18n setup etc. however I’m up for discussion @andrzejewsky @patzick @lukeromanowicz wdyt?

**Comment by lukeromanowicz** [comment]
IMHO we should put them into separate src/* modules - language packs. Ofc theme can have some translationsas well, that should be able to override module values as, but there is a set of standard values that are commonly used everywhere.

**Comment by patzick** [comment]
I completely agree with this issue. All translation files should be theme-specific.
However, we should leave in core translations which are strictly from the core, like messages throw as errors from actions etc. I don't have notifications in mind here - IMO there shouldn't be any of them in core, just in theme and theme can decide what to notify about and how.

To sum up - leave core-specific translations in core and not let to modify them, the rest of it is the theme and can be modified and changed.
Let's not forget about modules - how do you see it? Maybe module could have their own translation files already compiled?
