### ISSUE TITLE
yarn stuck on building fresh packages

### ISSUE THREAD

**Issue by saeed-abdul-rahim** [vuestorefront/vue-storefront#3808]
# Executed docker-compose up
And the terminal is stuck on building fresh packages
Which version of yarn should I use?

**Comment by pkarw** [comment]
Please make sure you've got the https://github.com/nodejs/node-gyp package installed which is required by `sharp` library

**Comment by pkarw** [comment]
@andrzejewsky maybe we should add some note or dependency on node-gyp(?) @kkdg do we have anything on that in the installation tutorial?
