### ISSUE TITLE
In mobile and desktop safari special_price = 0

### ISSUE THREAD

**Issue by dmytrokravch** [vuestorefront/vue-storefront#3810]
## Prerequisites
I noticed that in Safari doesn't show me the special_price both on the category and product page.
Could it be because Safari does not support date comparison which you use in `tax.ts`: `if (fromDate && toDate)`.
Also when i check `app.__vue__.$store.state.product.current.special_price` on product page, it return me `0`
Please answer the following questions for yourself before submitting an issue. 

* [x] I am running the latest version
* [x] I checked the documentation and found no answer
* [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

# Can't find what you're looking for?

## Keep the problem description concise and include:
* [ ] A brief description of the problem,
* [ ] Where the problem is occurring,
* [ ] The length of time the problem has been occurring,
* [ ] The size of the problem.

**Comment by pkarw** [comment]
Good point, let's try it out.

**Comment by andrzejewsky** [comment]
@dmytrokravch could you tell us which version of Safari did you use?

**Comment by dmytrokravch** [comment]
@andrzejewsky ios: 13.0, macOS: 13.0

**Comment by gibkigonzo** [comment]
TODO: we can use `dayjs`
