### ISSUE TITLE
Implement parallel building

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#3819]
## What is the motivation for adding / enhancing this feature?
Building takes a lot of time. We can try to reduce it with parallel building

## What are the acceptance criteria 
SW, Translations, Client, and Server are being built in parallel. 

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
Tested https://github.com/trivago/parallel-webpack in building production set and observed ~30% decrease of building time.

**Comment by lukeromanowicz** [comment]
Although there is a solution for building prod thanks to @gibkigonzo, running it in dev might still be improved. Reopening

**Comment by lukeromanowicz** [comment]
I've tried applying `thread-loader` but it doesn't seem to cause any major improvement.
Now I am trying to implement parallel-webpack but it requires some heavy dev-server modification. I will update this issue if I get to some positive results.

**Comment by gibkigonzo** [comment]
I've changed priority but lets continue it in 1.13. There needs to be added some improvement in dev mode.
