### ISSUE TITLE
Multistore routes w/ dispatcher & `appendStoreCode: false`

### ISSUE THREAD

**Issue by oskar1233** [vuestorefront/vue-storefront#3844]
## Current behavior
`setupMultistoreRoutes` sets up routes with names without prepended store code. However `prepareDynamicRoute` & `mappingFallback` use routes with names with prepended store code.

E.g. we have `de` store in config and it has `appendStoreCode: false`. Route name generated with `setupMultistoreRoutes` will be e.g. `category`, while `mappingFallback` and `prepareDynamicRoute` will try to reach out `de-category` route.

## Expected behavior
`setupMultistoreRoutes` sets up routes with names with prepended store code regardless of `appendStoreCode`.

`appendStoreCode` IMO should apply only to path, not name.

## Steps to reproduce the issue
1. Setup store with `appendStoreCode: false`.
1. Enable URL dispatcher.
1. Try to navigate to the store, it will throw "route not found" in the console.

## Can you handle fixing this bug by yourself?
Yup

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to?
This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.

## Environment details

* Browser: Chrome 78
* OS: macOS Catalina
* Node: 12.10
* Code Version: `develop` branch

## Additional information
Works if I remove the condition `if (storeCode && appendStoreCode)` and map routes to `localizedRouteConfig` anyway - not sure if it doesn't brake other use cases, though.

```
export function setupMultistoreRoutes (config, router: VueRouter, routes: RouteConfig[], priority: number = 0): void {
  const allRoutes: RouteConfig[] = []
  const { storeCode, appendStoreCode } = currentStoreView()
  if (storeCode && appendStoreCode) {
    allRoutes.push(...routes.map(route => localizedRouteConfig(route, storeCode)))
  } else {
    allRoutes.push(...routes)
  }
  router.addRoutes(allRoutes, true, priority)
}

**Comment by pkarw** [comment]
@lukeromanowicz can you please take a look at this one?

**Comment by AdKamil** [comment]
Be careful, because it may not work with nested routes.

**Comment by pkarw** [comment]
Related to #3614

**Comment by gibkigonzo** [comment]
Hey @oskar1233 I think it works as it should, but it can be a bit confusing. If you set `appendStoreCode: false` then your store internal navigation (SPA navigation) will be `/`. In opposite you can have internal navigation `/<storeCode>` with `appendStoreCode: true`. And thats all. 
`url` is supposed to be used **only** to switch between stores. If you set `url: "/de"` and `appendStoreCode: false` then it gonna fail, because internal navigation for german store will be `/` in that case. `appendStoreCode: false` can be used If you want to use **domain only** as store url. If we have`appendStoreCode: true` then `url` must be `url: "/<store-code>"`
Here are some examples:
```
// In that case in language switcher we will have localhost:3000 as external store
// when we reach to that store we will use `/` as internal navigation.
// localhost:3000/checkout
      "storeCode": "de",
      "url": "localhost:3000",
      "appendStoreCode": false,
```
```
// here German store will be default store
      "storeCode": "de",
      "url": "/",
      "appendStoreCode": false,
```
```
// here German store will be on `/de`, but if you navigate
// for example from Italian store to German it will fail,
// because it will try to reach German store on `/` and it is on `/de`
      "storeCode": "de",
      "url": "/",
      "appendStoreCode": true,
```

Maybe we could change it :thinking: but it would require breaking changes. I think that `storeCode` has too much power :smile: because it shouldn't be responsible of building internal navigation. It should be only as some kind of id for storeView. Then `url` can build any internal navigation
```
"storeCode": "de" // only used to identify store
"url": "/german" // build internal navigation and used to recognize store in ssr from url
"external-url": "localhost:3333" // optional - only for switching to external store
// "appendStoreCode" - removed
// "mapStoreUrlsFor" - removed

**Comment by oskar1233** [comment]
> If you set ... then it gonna fail
IMO that means design mess up. All you write makes sense but it is 1) undocumented (afaik) 2) too complicated.

Reproduce steps are IMO basic configuration and shouldn't make the store fail.

Also there are few backwards incompatible changes on `develop` so I wouldn't care much.

Anyway, I understand it is major design decision so I'll leave it up to core team - just dropped my thoughts & provided hackfix.

**Comment by rain2o** [comment]
Has anyone made any progress on this issue? I'm trying to update to the latest version, and would like to avoid modifying core files again to accomplish this need if at all possible.
