### ISSUE TITLE
Auto-deployment on our testing / stagins environment

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#3856]
I've noticed our QA team have no possibility to test current / latest version on the real production usage because of these version are usually not deployed yet. The problem is that we have to do this manually so often nobody does it, unless we have new either RC or stable version.

In order to improve this process, I'd like to introduce something like auto deployments feature:

* Merge to develop -> deployment to `test`
* Merge to release branch -> deployment to `next`
* Release on github (that is not RC) -> deployment to `demo` (or maybe we want to keep it as manual process)

What do you think alinadivante ArturDivante pkarw patzick mkoszutowski ?

To achieve this we can use github webhooks I think.

**Comment by kkdg** [comment]
This is something I need too! every time it's changed/updated, I need an automated notice. having an idea on this, just I don't know when it will ripen though ;)
