### ISSUE TITLE
Incorrect update the qty of cart item

### ISSUE THREAD

**Issue by dimasch** [vuestorefront/vue-storefront#3867]
## Current behavior
Update the qty - nothing to change. See only visually updated.
The Vuex state not updated.

## Expected behavior
Update the qty from frontend - then check Vuex state changed.

## Steps to reproduce the issue
Try to change the qty for some item in cart.

## Repository
https://github.com/DivanteLtd/vue-storefront/blob/1fd1cf4414b65a049401c3a8011344f462de29cf/core/modules/cart/store/mutations.ts#L47

https://github.com/DivanteLtd/vue-storefront/blob/1fd1cf4414b65a049401c3a8011344f462de29cf/core/modules/cart/store/actions.ts#L578

`dispatch('updateItem', { product: { qty: cartItem.prev_qty } })`

Need pass the `sku` property to product option.

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by andrzejewsky** [comment]
@dimasch Hey, could you tell us which version of VSF did you use?

**Comment by georgiev-ivan** [comment]
I would like to take this issue

**Comment by georgiev-ivan** [comment]
Hey @dimasch tested it on 1.11 branch and it works fine, but on 1.10 branch the getter returns different quantity as you have mentioned

**Comment by andrzejewsky** [comment]
ok so seems like we have to backport a bugfix thanks @georgiev-ivan

**Comment by pkarw** [comment]
@andrzejewsky can we quickly fix this one and close it (the solution is provided in the comment)

**Comment by gibkigonzo** [comment]
@dimasch Hey :) I've check this in 1.10.6 and it seems working ok. Can you check if this still occurs? 
![Peek 2020-04-06 09-45](https://user-images.githubusercontent.com/42383376/78534908-888a3400-77eb-11ea-9690-73dc5b4785df.gif)
