### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by leon0399** [vuestorefront/vue-storefront#3876]
## What is the motivation for adding / enhancing this feature?

Provide an option to boot up a Kubernetes deployment via Helm Chart

## What are the acceptance criteria 

* [ ] Helm chart
* [ ] Option to select own Docker image

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by NandoTheessen** [comment]
Hi 👋 
Is this a feature you'd be open to merge?

**Comment by rfaa-se** [comment]
Hello!

Any progress on this?
