### ISSUE TITLE
Newsletter token

### ISSUE THREAD

**Issue by tdugue** [vuestorefront/vue-storefront#3878]
## Prerequisites
Please answer the following questions for yourself before submitting an issue. 

* [x] I checked the documentation and found no answer
* [x] I am running the latest version
* [x] I checked to make sure that this issue has not already been filed

## Newsletter token
I have a concern for the subscription to the newsletter with magento 1. Distinction between guest and customer.

**Ex 1:**

I am not connected and no customer I want to register to the newsletter on the home page no problem.

In magento I would be registered as a guest

**Ex 2:**

I am a customer and therefore magento forces me to connect to subscribe to the newsletter.

That's when there is a problem. Because it is necessary token to find the current user and to be able to modified this customer information.

Otherwise we can do it without verifying that it is already a customer but we lose the information if it is a guest or not in magento.

My question is whether you will implement the token additions in the request ?

Thanks

**Comment by andrzejewsky** [comment]
Hmm actually we haven't planned something like that. @pkarw Have you heard about that issue before? @TigerWhite1 Maybe we can change this question to the regular issue / feature request?

**Comment by TigerWhite1** [comment]
Yes sorry for long answer times.

even without speaking of magento for the modification of information of a customer account even a newsletter they would be more prudent to send a token to verify that it is the user who is at the request.

Of course only in the case of a customer who has an account. Otherwise no need token

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
