### ISSUE TITLE
Add cache-tag like functionality to static page generator to limit amount of pages to be processed

### ISSUE THREAD

**Issue by nhp** [vuestorefront/vue-storefront#3897]
## What is the motivation for adding / enhancing this feature?
This is usefull when a full index takes a long time for all pages (like a couple of minutes for product pages alone) and you have a lot of changing data all the time and need to regenerate your pages because of that.
In this case you only want to generate the pages that were affected by the last update.

## What are the acceptance criteria 
* [x] Keep something like a "page-tag" as is done with cache tags, to map what change should trigger which page-object to rebuild
* [x] Multiple "tags" per page-object
* [x] Multiple page-objects per "tag"
* [x] Implement this in a scale able style, like in a real queue with process-workers that take care of the queue-items and that can be adjusted on demand #3899 
* [x] The whole process needs to take care that only the last change-request to a given object is valid. If you change multiple products in a category, the category should only be processed once and not for every product, every "old" job needs to be ignored. (also needs handling in #3899 )

## Can you complete this feature request by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
In our case, 50k+ products, within 2k of categories, the whole process takes about 10-15 minutes. If change happens during this period of time (sell something so a products may go out of stock) this is really dangerous. 
I could imagine that the trigger for queuing this could be like the cache-invalidation trigger that is used to purge the output cache in case something changes in Elastic, so maybe couple it to the Elastic change calls? Single page generation should be fast, to prevent huge differences between an "old" page and the current information within Elastic.

**Comment by pkarw** [comment]
Plus: parallel rendering would be awesome (multiple processes) - but actually by having those tags you can easily do this by starting 2-3 cli scripts each for different tag/partition

**Comment by nhp** [comment]
I think having it in a "poor-mans" way, to prevent the need of a queuing service should be for this ticket and the queuing implementation should be handled in #3899 but the general functionality should be possible without the "worker-implementation".
