### ISSUE TITLE
Configuration mismatches when building once for many environments

### ISSUE THREAD

**Issue by michael-bouvy** [vuestorefront/vue-storefront#3937]
## Current behavior
When building in production mode, using `yarn build` the client-side configuration is generated based on `default.json`, `local.json` and `production.json` (taken from `NODE_ENV`), and written in both `dist/app.*.js` and `dist/core-service-worker.js`.

This is an issue as a single build may be (re)usable on several environments (ie. staging, preprod, prod), leveraging the `NODE_CONFIG_ENV` environment variable, ie:

```bash
NODE_CONFIG_ENV=staging yarn start
```

It actually works fine for server-side calls, as `node-config` loads the config at runtime upon current configured environment.

## Expected behavior
Configurable values (ie. URLs) should not be hardcoded at build time in generated code (`dist/` directory), so that a single application build can be usable (in a Docker image for instance) on several stages/envs.

## Steps to reproduce the issue
* Set `.graphql.host` to `graphql-default` in `config/default.json`
* Set `.graphql.host` to `graphql-staging` in `config/staging.json`
* Set `.graphql.host` to `graphql-prod` in `config/production.json`
* Run `yarn build` (which will run in production mode, as `NODE_ENV=production` in `package.json` config for `build` command)
* Run `NODE_CONFIG_ENV=staging yarn start`

:arrow_down:

* On server-side (VSF to VSF-API), VSF is using `graphql-staging` hostname :white_check_mark:
* On client-side (VSF to VSF-API), VSF is using `graphql-prod` hostname, taken from `dist/*.js` files :x:

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
* Browser: Chrome 79
* OS: macOS Mojave / Docker 
* Node: 10
* Code Version: 1.8.4

**Comment by pkarw** [comment]
Hi there! There is a config option: dynamicConfigReload which is set by default to false. Try just switching it to true - it will cause the config reload by each SSR request which apparently should solve this issue

**Comment by michael-bouvy** [comment]
Thanks @pkarw!

I actually had this option in mind, but didn't think it could help. Will give it a try.

**Comment by michael-bouvy** [comment]
Gave this a try, but I don't get expected result: GraphQL API endpoint used is still production one (as `NODE_ENV=production`), despite having set `NODE_CONFIG_ENV=my-env` (with `config/my-env.json` existing with env-specific conf).

Here is my `default.json` conf:

```json
{
  "server": {
    "dynamicConfigReload": true,
    "dynamicConfigContinueOnError": false,
    "dynamicConfigExclude": ["entities", "localForage", "shipping", "boost", "query"],
    "dynamicConfigInclude": []
    },
    ...
}
```

**Comment by michael-bouvy** [comment]
I guess this issue should be reopened, @pkarw ? 🙂

**Comment by pkarw** [comment]
Sure, reopening

**Comment by pkarw** [comment]
Please check if this won’t solve the isssue: https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables


We’re using this solution in storefront cloud to pass the variables via env to prebuilt docker containers

**Comment by michael-bouvy** [comment]
This is an interesting feature, but does not fit the need: environment variables are only processed on server side, and from what I can see, once the JS is bundled at build time with a given environment-specific config, values are not reloaded, even with `dynamicConfigReload`

**Comment by pkarw** [comment]
I’m changing this issue to feature request; the config file is bei ng compiled into app bundle it’s our basic feature from the very beginning; so the suggested solution is to build the app once per ENV because it also involves some code level optimizations, different webpack config, including/excluding source maps. Pretty complex one.
