### ISSUE TITLE
Update eslint package for typescript

### ISSUE THREAD

**Issue by ResuBaka** [vuestorefront/vue-storefront#4039]
## What is the motivation for adding / enhancing this feature?

The current version is only 100% compatible unit version <3.5.0 and with @typescript-eslint/eslint-plugin Version 2.* it is valid until version <3.8 (3.8 is currently in beta). This should be updated to have 100% support from the plugin and a maybe 100% support as they say there could be some cases where there could be problems. 

This is the warning that the current typescript eslint plugin throws when you use it on a typescript version that is not officially supported. 

# ```
WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.5.0

YOUR TYPESCRIPT VERSION: 3.7.5

Please only submit bug reports when using the officially supported version.

=============

```

## What are the acceptance criteria 
<!-- List the acceptance criteria for this task in a form of a list. -->

* [ ] Update @typescript-eslint/eslint-plugin and @typescript-eslint/parser to the lastest 2.* version

## Can you complete this feature request by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
<!-- If you think that any additional information would be useful please provide them here. -->
These are the rules that are added/changed which are all errors:


*  'prefer-const'
*   '@typescript-eslint/ban-ts-ignore'
*   'no-var'
*   '@typescript-eslint/no-empty-function'
*   '@typescript-eslint/no-this-alias'
*   '@typescript-eslint/no-inferrable-types'
*   'prefer-rest-params'

About these there should be some discussion on how to handle it if there should be moved to warning, be disabled or stay the same as the default and just fix them in the code?

**Comment by lukeromanowicz** [comment]
I would say that '@typescript-eslint/ban-ts-ignore', '@typescript-eslint/no-empty-function' are very very problematic for testing. The rest, in my opinion, should be treated as errors and fixed upon updating the dependencies.
What do you guys think @gibkigonzo @andrzejewsky @pkarw

**Comment by simonmaass** [comment]
@pkarw i can take this - guess related to https://github.com/DivanteLtd/vue-storefront/issues/4126

**Comment by pkarw** [comment]
Cool! Go on @simonmaass

**Comment by simonmaass** [comment]
this is an absolute nightmare :) there are so many rules that need decision making... i believe this should be done by core team!
