### ISSUE TITLE
Update config to latest

### ISSUE THREAD

**Issue by maikel-code** [vuestorefront/vue-storefront#4048]
## What is the motivation for adding / enhancing this feature?

Using latest & optimized version of config

## What are the acceptance criteria 

* [ ] ...

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by maikel-code** [comment]
Can someone grant me permissions to create a PR?

**Comment by pkarw** [comment]
@maikel-code you can create a PR that's not a problem. You mean updating config in the docs?
