### ISSUE TITLE
Make "remember me" checkbox during login actually do anything

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#4057]
## Current behavior
I am probably missing something because it looks like checkbox "remember me" is hooked up to data property "remember" which... is not used anywhere.

## Expected behavior
"remember me" checkbox actually does some impact

## Steps to reproduce the issue
login with and without "remember me" selected

## Suggested solution
* if checkbox is not selected then put the token in some storage with more limited lifetime (short living secure cookie/session storage)

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
Changed label to feature request as this feature hasn’t been implemented yet. We can remove the checkbox from the UI as for now
