### ISSUE TITLE
Add `gzip` / `gunzip` for cache keys for `vsf` and `vsf-api`

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#4076]
## What is the motivation for adding / enhancing this feature?

For some more complicated pages the cache keys for SSR cache can go into MBs (I saw an instance with a single page of 5MB text stored into Redis). It can be easily saved using gzip compression + minification applied to the

## Vue Storefront -`core/scripts/server.ts`:
1. https://github.com/DivanteLtd/vue-storefront/blob/4341ceaafe0fa221d6b59ae34bdc6ebf3768d830/core/scripts/server.ts#L212
1. https://github.com/DivanteLtd/vue-storefront/blob/4341ceaafe0fa221d6b59ae34bdc6ebf3768d830/core/scripts/server.ts#L245

## Vue Storefront API - `src/api/catalog.js`:
1. https://github.com/DivanteLtd/vue-storefront-api/blob/875ed27ad949c7a5e6db90cc8700761e8602a636/src/api/catalog.js#L131
1. https://github.com/DivanteLtd/vue-storefront-api/blob/875ed27ad949c7a5e6db90cc8700761e8602a636/src/api/catalog.js#L11

**Comment by pkarw** [comment]
Related to: #3949

**Comment by jonathanribas** [comment]
@pkarw we need to make sure that gzip / gunzip do not use too many resources in NodeJS.
