### ISSUE TITLE
Add an option to the sidebar menu to reset location when closed

### ISSUE THREAD

**Issue by themreza** [vuestorefront/vue-storefront#4088]
## What is the motivation for adding / enhancing this feature?

When choosing a sub-category via the sidebar menu, Vue Storefront remembers the last selected location in the menu even after the user has clicked on the menu item and the sidebar has been closed.

The commonly expected behavior from sidebar menus is to always go back to the root menu list when the menu is closed. I think the current behavior is reasonable given the new store-based web app technology, but we need to have an option in the config to allow switching to the traditional UX.

Initially I thought it made sense for category navigation, if the user wants to go back and select a parent category, but even after the homepage icon is clicked, the sidebar menu stays at the same location.

Current behavior:
![](https://i.imgur.com/dCfl5Ao.gif)

## What are the acceptance criteria 

* [ ] The sidebar menu should optionally reset its state `depth` and `path` upon being closed

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by themreza** [comment]
The implementation of this feature is quite simple. This is how I achieved it in my project (without the config option):

SidebarMenu.js:

* [Add `this.$store.commit('ui/resetSubmenu')`](https://github.com/DivanteLtd/vue-storefront/blob/master/core/compatibility/components/blocks/SidebarMenu/SidebarMenu.js#L31)

* [Add a new mutation `resetSubmenu (state) { state.submenu.path = [] state.submenu.depth = false },`](https://github.com/DivanteLtd/vue-storefront/blob/master/src/themes/default/store/ui.ts#L31)

![](https://i.imgur.com/vpnbZnp.gif)

**Comment by simonmaass** [comment]
I think there are merrits for both behavior... so if you would add a config parameter it would be nice
