### ISSUE TITLE
Improve the search functionality

### ISSUE THREAD

**Issue by themreza** [vuestorefront/vue-storefront#4146]
## What is the motivation for adding / enhancing this feature?

While testing the search panel, I noticed that although there is fuzzy searching in ElasticSearch queries, it doesn't always behave as intended (doesn't autocomplete some product name searches). Also, many of our products contain non-ascii characters and are not included in the search.

I tried playing around with the provided `fuzziness` and `prefix_length` values in `multimatch.js`, and there are possibilities of introducing custom token analyzers, but the easiest way I figured out is to add a couple `or` queries of the type `prefix`, taking advantage of the `slug` field to overcome the non-ascii problem.

In [elasticsearchQuery.js](https://github.com/DivanteLtd/vue-storefront/blob/master/core/lib/search/adapter/api/elasticsearchQuery.js), add the following:

```
 .orQuery('prefix', 'name', queryText)
 .orQuery('prefix', 'slug', queryText)
```

It's best to add config file options to selectively enable this feature.

## What are the acceptance criteria 

* [ ] ...

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by didkan** [comment]
A very cool feature would be to introduce some sort of synonym analyzer. Would that be at all possible? @themreza

**Comment by themreza** [comment]
@didkan Indeed, anything that's possible with the current ElasticSearch is also possible in Vue Storefront.
The synonym feature, however, requires a minimum ElasticSearch version of 6.8.
The stable version of Vue Storefront is on ElasticSearch version 5.6, but there are plans to use 7.x soon (https://github.com/DivanteLtd/vue-storefront-api#elastic-7-support).
