### ISSUE TITLE
Remake order is not possible for bundle products

### ISSUE THREAD

**Issue by akrajna** [vuestorefront/vue-storefront#4148]
## Current behavior
The remake order does not work if the ordered products have a bundle product. And so it happens on hotfix/v1.11.2  and https://demo.storefrontcloud.io/
![RemakeOrderPic](https://user-images.githubusercontent.com/57936972/75860709-91f33b80-5dfc-11ea-9ca1-7fac9b289f89.png)

## Expected behavior
It is possible to remake order for bundle products

## Steps to reproduce the issue
Initial condition:  user is logged in and he has in 'My account-My orders' at least one order with bundle product

1. Go to My account
1. Click on 'My orders'
1. Click on  '...' drop down next to any order with bundle product
1. Click 'Remake' order
1. See the error

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.
* [x] This is a bug report for hotfix/v1.11.2

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by pkarw** [comment]
Unfortunately it was always like this so I’m changing the type to feature request. We can work around this by skipping the bundle products / displaying error msg or adding full support. The problem is that bundle products so use the virtual skus that make the product search impossible and therefore the addItems call raises an error
