### ISSUE TITLE
Kubernetes support - upgrade

### ISSUE THREAD

**Issue by samueldervis** [vuestorefront/vue-storefront#4193]
https://github.com/DivanteLtd/vue-storefront/blob/53a27a6d9971bc5bce1a26f818d0adf07f58ff6b/kubernetes/vue-storefront-deployment.yaml#L16

This image was last updated 2years ago in docker hub.
Please provide documentation of building a custom image

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
