### ISSUE TITLE
Special price = 0€ not showing

### ISSUE THREAD

**Issue by simonmaass** [vuestorefront/vue-storefront#4199]
## Current behavior

If price is 75€ for example and you have a special price = 0€ then special price is not shown in ProductPrice.vue component.

![Unbenannt](https://user-images.githubusercontent.com/32599710/77525839-ecc30480-6e89-11ea-9cae-f0b517e33392.png)

As you can see in vuex initialPrice.special is 0€ and in price.special it is 75€ again...

## Expected behavior

Show special price as 0€ and inital Price of 75€ as crossed out

## Steps to reproduce the issue

Create product with price >0€ and set special price to 0€

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: Chrome 
* OS: 
* Node: 10
* Code Version: 1.11.2

**Comment by pkarw** [comment]
VSF by design is not letting you to have prices = 0. That's why the behavior is like this. I guess it can be easily extended by amending the logic in the `tax.ts`. Maybe there should be a config option just for that. Changing to `feature request`

**Comment by pkarw** [comment]
... the other thing is that you'll need to modify `cart/addItems` method to let the products with zero price to be added to the cart anyway

**Comment by simonmaass** [comment]
@pkarw I will have a look into this - also maybe create PR... 

I would kinda disagree with it being a feature request but ok ;-) As an e-commerce tool having products on sale that sometimes even are 0€ - so basically just giving them away - is not totally uncommon... but lets just fix it and move on :)
