### ISSUE TITLE
Consider (re?)introducing dependabot for automatic version bumps

### ISSUE THREAD

**Issue by jpkempf** [vuestorefront/vue-storefront#4256]
## What is the motivation for adding / enhancing this feature?
I work for a software consultancy and my team is using Vue Storefront as the basis for a client project. Being a service company, we are responsible for the services we provide to customers and this includes the safety and stability of the software we deliver. Keeping a project's dependencies up to date is a basic hygiene task that we are expected to perform in this context.

Our code is based on a fork of the core VSF repository, which means we can perform this task on our fork. However, we would like to diverge as little as possible from the upstream repository, which is why I'd be interested in hearing your opinion about enabling dependabot directly here on the core repo. This would allow anyone maintaining a fork of the repo to get version bumps by simply updating their fork.

I've noticed that there were in fact [a number of issues raised by dependabot in mid-2019](https://github.com/DivanteLtd/vue-storefront/issues?q=dependabot), so apparently this has been tried at least once already in the past? I would be interested in your experiences from that prior phase and what prompted you to abandon it. I recognize that dependabot can tend to create a lot of noise for minor and fix version bumps and that it sometimes suggests major version bumps that may not be 100% safe to merge without a certain amount of testing, so I could understand if that is part of the reason why you're not currently using it.

Thanks so much for your time, looking forward to the replies! :slightly_smiling_face: 

## What are the acceptance criteria 
* [ ] dependabot is configured for the `DivanteLtd/vue-storefront` repository and version bump PRs are frequently getting merged

## Can you complete this feature request by yourself?
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to?
* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
