### ISSUE TITLE
sidebar menu performance

### ISSUE THREAD

**Issue by yaroslav-zenin** [vuestorefront/vue-storefront#4257]
## Current behavior

Sidebar menu works very slow, delay 5-10 sec, very often browser freeze
Total amount of categories included nested: 19528 (max level is 6)
Total amount of unique categories: 4605

## Expected behavior

works fast without any delays

## Steps to reproduce the issue

click on hamburger menu
freeze 5-10 sec

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO
* [x] NOT SURE

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: last chrome, FF
* OS: Linux 
* Node: v12.13.0 
* Code Version: v1.11.1

**Comment by themreza** [comment]
Lazy-loading will solve this issue.

To improve performance while maintaining fluidity, the sidebar can auto load the current level + `n` levels of its children, with `n` being definable in the config and will be sent to the API in the request.

For example, on the homepage:
* `n=0` Only load the root categories
* `n=1` Load the root categories + immediate children
* `n=2` Load the root categories + immediate children + children of immediate children
etc.
