### ISSUE TITLE
Add support for Fresh Relevance via new module

### ISSUE THREAD

**Issue by dhendo** [vuestorefront/vue-storefront#4259]
## What is the motivation for adding / enhancing this feature?
Add support for [Fresh Relevance](https://www.freshrelevance.com/) script injection and data collection using existing hooks.

## What are the acceptance criteria 
* [x] Fresh Relevance Loader script included when Website ID configuration is included and module enabled
* [x] Data passed down to Fresh Relevance script

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information
Implemented following a discussion with Raymond. -followed the hotjar and GTM modules as a guide.

Currently implemented using a mix of hooks (core, cart, catalog) and some inspection of the event bus:

```store
    if (type === 'ui/setMicrocart' && payload === true) {
      // Opening the cart sidebar
      afterCartVisited(store);
    } else if (type === 'checkout/SET_THANKYOU' && payload === true) {
      afterPurchaseComplete(store);
    } else if (type === 'product/product/SET_CURRENT') {
      productVariantSelected(store);
    } else if (type === 'route/ROUTE_CHANGED') {
      if (payload.to.name === 'checkout') {
        afterCheckoutVisited(store);
      } else {
        otherPageVisited(payload.to);
      }
    }
  });
```

It would be preferable to extend core to add core to add new hooks for these to cleanup this workflow - should I create a separate issue for discussion?

PR to follow.

**Comment by gibkigonzo** [comment]
@dhendo Thanks for pr :) We can add those hooks for each module. For example, for this `checkout/SET_THANKYOU` we can add hook in `order` module. And trigger it for each step of checkout. I think that its good idea. In future we can replace EventBus.$emit from checkout with hooks.

**Comment by dhendo** [comment]
@gibkigonzo Thanks, shall I create a separate feature request issue to track that?
