### ISSUE TITLE
[Docs] Add hosting server requirements section on docs

### ISSUE THREAD

**Issue by ktopouzi** [vuestorefront/vue-storefront#4269]
## What is the motivation for adding / enhancing this feature?

I recently wanted to test my VSF shop in production but didn't exactly knew the requirements so I just bought a vps with 4GB or RAM and 2 CPUs. After some testings I saw that 4GB RAM was clearly not enough. So I wondered, what's the **requirements** for a VSF app?

It would be quite useful, especially for first timers out there, to have a dedicated section in docs where we list some use cases and suggestions for server requirements.  I know that traffic also have a great impact on performance so maybe we can ask for current users and get some feedback from live projects? 

I believe that would add some value, what do you think?

**Comment by pkarw** [comment]
Hi @ktopouzi sure, it makes a lot of sense. However, we're not sure what numbers should we specifically put in these areas. The only thing we have at our disposal is the performance tests for Storefront Cloud: https://blog.vuestorefront.io/vue-storefront-performance-tests-and-architecture-ready-for-traffic-peaks/

Maybe you could do some benchmarking and put some numbers into the docs? It would be much appreciated

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
