### ISSUE TITLE
[AYC] Write unit tests for api-client

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#4283]
## What is the motivation for adding / enhancing this feature?
Cover AYC api-client with unit tests.

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-71) by [Unito](https://www.unito.io/learn-more)

**Comment by konradovsky** [comment]
https://github.com/DivanteLtd/vue-storefront/issues/4283
