### ISSUE TITLE
[AYC] implement products search

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#4304]
Implement product search page in AboutYou Cloud integration using backbone interfaces implemented in api-client and vsf core logic. Make sure that test coverage stays 100%. For core implementation (fi not yet ready, mirror category page UI and logic)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
