### ISSUE TITLE
Add to cart  broken for new users with server sync on

### ISSUE THREAD

**Issue by AgarvaiN** [vuestorefront/vue-storefront#4305]
## Current behavior
When a user tries to add a product to the cart from a new browser (or one with data cleared), where he doesn't already have a cart. Product gets added for a second, then it gets instantly removed.
After the button is clicked the second time, it adds the product fine.

## Expected behavior
User should be able to add a product to the cart with a single click.

## Steps to reproduce the issue
Clone VSF from Master
Copy default.json to local.json
In local.json just update the `cart` section to look like this

`"cart": {
    "thumbnails": {
      "width": 150,
      "height": 150
    },
    "bypassCartLoaderForAuthorizedUsers": false,
    "serverMergeByDefault": true,
    "serverSyncCanRemoveLocalItems": true,
    "serverSyncCanModifyLocalItems": true,
    "synchronize": true,
    "synchronize_totals": true,
    "setCustomProductOptions": true,
    "setConfigurableProductOptions": true,
    "askBeforeRemoveProduct": true,
    "displayItemDiscounts": true,
    "productsAreReconfigurable": true,`

Tried with default theme, and demo.vuestorefront.io as API 

Run the app
Open the browser in Incognito or Clear Application Data and reload the page
Try to add product to cart

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: Chrome 81.0.4044.122 and others
* OS: All (Mac OS, Windows 10, Ubuntu Server, Linux Mint)
* Node: 10-13 (Currently 13.13.0)
* Code Version: Master - 1.11.3

## Additional information
Important setting
`"serverSyncCanRemoveLocalItems": true`

* I think this is the one that breaks it

But it is related to the whole Add to cart chain of events and async process, probably await missing somewhere

**Comment by gibkigonzo** [comment]
by default this option `serverSyncCanRemoveLocalItems` is set to false and with that is related all sync process. I think that it is much more complicated then just adding await. It is better to fix this bug after 1.12 release

**Comment by gibkigonzo** [comment]
I think we should remove `serverSyncCanRemoveLocalItems` and `serverSyncCanModifyLocalItems`. Instead of those configs we should check if this is first cart pull (not related with add/remove actions). On that pull we should set `forceClientState` on `false`. Which is now always set on true, because `serverSyncCanRemoveLocalItems` is always false
