### ISSUE TITLE
Main Product Duplicate in Product Related Section

### ISSUE THREAD

**Issue by clinton-origin** [vuestorefront/vue-storefront#4308]
## Current behavior
When accessing a product details page the current product still appears in the related products section and the "you might like section"

## Expected behavior
The selected product should not appear in the "related product section" or the "you might also like" section.

## Steps to reproduce the issue
https://next.storefrontcloud.io/men/tops-men/hoodies-and-sweatshirts-men/hoodies-and-sweatshirts-15/bruno-compete-hoodie-99.html?childSku=MH03

Bruno Compete Hoodie is the selected product and appears in both "related product section" or the "you might also like" section.

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
N/A

**Comment by clinton-origin** [comment]
My fix, for reference, was to add the product id to the related products component 

`<related-products type="upsell" :productID="getCurrentProduct.id" :heading="$t('We found other products you might like')" />`

Then just filter by the ID

`getCurrentRelatedProducts () {
      return this.getProductRelated[this.type].filter(c => {return c.id !== this.productID}) || []
    },`

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
