### ISSUE TITLE
[Next] breadcrumbs not updated when navigating categories

### ISSUE THREAD

**Issue by carlokok** [vuestorefront/vue-storefront#4313]
## Current behavior
On https://vsf-next-demo.storefrontcloud.io/c/cat when clicking the top menu items, the breadcrumbs under it keep showing Home | Women (in my case); when clicking men or kids.

## Expected behavior
Should show "men" or "kids" or "blazors" or whatever the selected thing is.

## Steps to reproduce the issue
On https://vsf-next-demo.storefrontcloud.io/c/women

![afbeelding](https://user-images.githubusercontent.com/238568/80681878-d24ffc80-8ac1-11ea-9416-87c4c2a9aeca.png)

Click men, note that the highlighted section still says men.

## Repository
Next.

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.

## Environment details
* Browser: Chrome and Firefox
* OS: Windows
* Node: (no idea; uses demo)
* Code Version: (no idea; uses demo)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
