### ISSUE TITLE
[AYC] Implement wishlist factories

### ISSUE THREAD

**Issue by lukeromanowicz** [vuestorefront/vue-storefront#4316]
Implement wishlist factories based on cart factories. Remember to keep code coverage at 100%. Place them in **AYC composables**

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-80) by [Unito](https://www.unito.io/learn-more)

**Comment by konradovsky** [comment]
https://github.com/DivanteLtd/vue-storefront/pull/4331
