### ISSUE TITLE
When visiting product link in browser, I get these errors in console

### ISSUE THREAD

**Issue by imnas** [vuestorefront/vue-storefront#4360]
## Prerequisites
Please answer the following questions for yourself before submitting an issue. 

* [x] I am running the latest version
* [x] I checked the documentation and found no answer
* [x] I checked to make sure that this issue has not already been filed

# Is there something you don't understand? What is it? Describe it.	

Hi Guys, I've been modifying the code and keep coming across this issue when trying to access a product page from the URL

![e9704563df4b88ab1bd5d059b8a25c49](https://user-images.githubusercontent.com/19938321/81441679-1d28de80-916a-11ea-9c49-eb71b2304d49.png)

**Comment by imnas** [comment]
![3bdfc53f74958439512f82e58bf58616](https://user-images.githubusercontent.com/19938321/81442134-f0c19200-916a-11ea-9bc9-cfccef6e118d.png)

**Comment by imnas** [comment]
![df6d8199e16988d487f27b77c8ad7db8](https://user-images.githubusercontent.com/19938321/81442176-059e2580-916b-11ea-930a-1014670dfc48.png)

**Comment by gibkigonzo** [comment]
@imnas check your requests, probably you are missing some data in product. Also check what data do you get for product page in `mappingFallback`

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
