### ISSUE TITLE
[CT] Implement missing features in the my account section

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#4397]
My account must have implemented the following sections:

* address book - all of address management
* order view - order details view in the  orders history
* changing password
* remove  areas  that are not supported by commercetools (eg. reviews, loyalty card etc.)

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-120) by [Unito](https://www.unito.io/learn-more)

**Comment by carlokok** [comment]
Note that commercetools does support reviews; they're just not exposed in mc. https://docs.commercetools.com/http-api-projects-reviews
