### ISSUE TITLE
[CT] Improve checkout

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#4402]
We have implemented  MVP of the checkout so far,  but it needs some improvements and it must be well tested. There are a few things left to stabilize it:

* cover all scenarios of checkout flow: (guest, logged user, a guest who creates an account, pre-load address from the account)
* add loading states and handling errors
* implement a way of providing payment systems
* create some core interfaces*

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-124) by [Unito](https://www.unito.io/learn-more)

**Comment by janmyszkier** [comment]
one of the things not specifically mentioned here, but important:
https://github.com/DivanteLtd/vue-storefront/issues/4449
