### ISSUE TITLE
Wrong prices after coupon code in cart/checkout

### ISSUE THREAD

**Issue by simonmaass** [vuestorefront/vue-storefront#4460]
## Current behavior

When entering a coupon code in checkout that has the setting in magento 2: "Deduct 5€ for whole cart" then the prices on the products are wrong:

![image](https://user-images.githubusercontent.com/32599710/82841110-1ffb3180-9ed5-11ea-81c4-09e42ecce8bb.png)

## Expected behavior

The price of the products in cart should not change if the coupon deducts from grand total... only if coupon is for product

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:  1.11.4

**Comment by pkarw** [comment]
Are you sure this is a bug @simonmaass ? I mean - we're taking the totals from Magento directly. The prices shown in the cart are deducted from `totals.items.final_price` - `totals.items.regular_price`

Isn't it something you need to just re-configure in Magento2 backend?

**Comment by simonmaass** [comment]
ok well i found the problem... @pkarw 

in src\themes\craftsoles\components\craftsoles\blocks\Microcart\Product.vue

this is hardcoded to show the price:
```
<div class="prices" v-else-if="isOnline && product.totals">
            <span class="h4 serif cl-error price-special" v-if="product.totals.discount_amount">
              {{ product.totals.row_total - product.totals.discount_amount + product.totals.tax_amount | price(storeView) }}
            </span>
            <span class="h6 serif price-original" v-if="product.totals.discount_amount">
              {{ product.totals.row_total_incl_tax | price(storeView) }}
            </span>
            <span class="h4 serif price-regular" v-if="!product.totals.discount_amount">
              {{ product.totals.row_total_incl_tax | price(storeView) }}
            </span>
          </div>
```

but if you have: 
"finalPriceIncludesTax": true,

then it should be:

```
<div class="prices" v-else-if="isOnline && product.totals">
            <span class="h4 serif cl-error price-special" v-if="product.totals.discount_amount">
              {{ product.totals.row_total_incl_tax - product.totals.discount_amount | price(storeView) }}
            </span>
            <span class="h6 serif price-original" v-if="product.totals.discount_amount">
              {{ product.totals.row_total_incl_tax | price(storeView) }}
            </span>
            <span class="h4 serif price-regular" v-if="!product.totals.discount_amount">
              {{ product.totals.row_total_incl_tax | price(storeView) }}
            </span>
          </div>
```

i believe no calculations or business logic should exists in the vue compontents... this should be in core...

**Comment by pkarw** [comment]
Cool. Can you please propose a pull request with a fix?

**Comment by simonmaass** [comment]
@gibkigonzo  Tomasz, would you agree that the calculation should not be done in the vue component?

**Comment by gibkigonzo** [comment]
@simonmaass I agree, this should be in core. Probably best place is to create helper in `core/modules/cart/helpers`. Can you propose pr?

**Comment by simonmaass** [comment]
@gibkigonzo @pkarw will do

**Comment by teuma86** [comment]
I just wanted to check if there is any update on this.  As I am looking into the same issue for a website I am developing.

**Comment by teuma86** [comment]
Just to further explain the fix as this theme is no longer available to review the code

` <div class="prices" v-if="!displayItemDiscounts || !isOnline">
            <span class="h4 serif cl-error price-special" v-if="product.special_price">
              {{ product.price_incl_tax * product.qty | price(storeView) }}
            </span>
            <span class="h6 serif price-original" v-if="product.special_price">
              {{ product.original_price_incl_tax * product.qty | price(storeView) }}
            </span>
            <span class="h4 serif price-regular" v-else data-testid="productPrice">
              {{ (product.original_price_incl_tax ? product.original_price_incl_tax : product.price_incl_tax) * product.qty | price(storeView) }}
            </span>
          </div>
          <div class="prices" v-else-if="isOnline && product.totals">
            <span class="h4 serif cl-error price-special" v-if="product.totals.discount_amount">
              {{ product.totals.row_total - product.totals.discount_amount + product.totals.tax_amount | price(storeView) }}
            </span>
            <span class="h6 serif price-original" v-if="product.totals.discount_amount">
              {{ product.totals.row_total_incl_tax | price(storeView) }}
            </span>
            <span class="h4 serif price-regular" v-if="!product.totals.discount_amount">
              {{ product.totals.row_total_incl_tax | price(storeView) }}
            </span>
          </div>
          <div class="prices" v-else>
            <span class="h4 serif price-regular">
              {{ (product.regular_price || product.price_incl_tax) * product.qty | price(storeView) }}
            </span>
          </div>
        </div>`

Note displayItemDiscounts is a computed property which returns config.cart.displayItemDiscounts

If this is true, you will fall into the else-if section which uses product.totals.discount_amount

With Magento storing cart item discounts against the quote item as discount_amount.  This results in the issue reported.

Thanks

Jamie

**Comment by lukaszjedrasik** [comment]
@Fifciu all 3 PR's are ready for review.
