### ISSUE TITLE
Production Nginx configuration referenced in docs blocks robots indexing

### ISSUE THREAD

**Issue by trabulium** [vuestorefront/vue-storefront#4477]
## Current behavior

https://raw.githubusercontent.com/DivanteLtd/vue-storefront/develop/docs/guide/installation/prod.vuestorefront.io

Contains the line: 	add_header X-Robots-Tag none; 

This is the equivalent of "noindex,nofollow"

## Expected behavior

The line shouldn't be included in a production nginx config

## Steps to reproduce the issue

1. Load nginx config up
1. curl -s -I  "https://yourdomain.com/" | grep "X-Robots-Tag"

## Repository

https://raw.githubusercontent.com/DivanteLtd/vue-storefront/develop/docs/guide/installation/prod.vuestorefront.io

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by pkarw** [comment]
@kkdg can you please fix it?
