### ISSUE TITLE
[Bug][Next]  FATAL  ENOENT: no such file or directory, scandir '/Users/ael/Github/vsfnext/packages/commercetools/theme/lang

### ISSUE THREAD

**Issue by by-tech** [vuestorefront/vue-storefront#4504]
AELMAC:vsfnext ael$ yarn dev:ct
yarn run v1.22.4
$ cd packages/commercetools/theme && yarn dev
$ nuxt
ℹ VSF Starting Vue Storefront Nuxt Module                                                                                          01:29:06
✔ VSF Installed Composition API plugin for Vue 2                                                                                   01:29:06
✔ VSF Installed SSR plugin for composables                                                                                         01:29:06
ℹ VSF Vue Storefront core development mode is on [coreDevelopment]                                                                 01:29:06
ℹ VSF Using raw source/ESM for @storefront-ui/vue [useRawSource]                                                                   01:29:06
ℹ VSF Using raw source/ESM for @storefront-ui/shared [useRawSource]                                                                01:29:06
ℹ VSF Using raw source/ESM for @vue-storefront/commercetools [useRawSource]                                                        01:29:06
ℹ VSF Using raw source/ESM for @vue-storefront/core [useRawSource]                                                                 01:29:06
ℹ VSF Starting Theme Module                                                                                                        01:29:06
ℹ VSF Adding theme files...                                                                                                        01:29:06

 FATAL  ENOENT: no such file or directory, scandir '/Users/ael/Github/vsfnext/packages/commercetools/theme/lang'              01:29:06

  at Proxy.readdirSync (fs.js:790:3)
  at getAllFilesFromDir (/Users/ael/Github/vsfnext/packages/core/theme-module/scripts/getAllFilesFromDir.js:12:20)
  at copyThemeFiles (/Users/ael/Github/vsfnext/packages/core/theme-module/scripts/copyThemeFiles.js:18:22)
  at ModuleContainer.DefaultThemeModule (/Users/ael/Github/vsfnext/packages/core/theme-module/index.js:46:5)
  at process._tickCallback (internal/process/next_tick.js:68:7)
  at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
  at startup (internal/bootstrap/node.js:283:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

   ╭────────────────────────────────────────────────────────────────────────╮
   │                                                                        │
   │   ✖ Nuxt Fatal Error                                                   │
   │                                                                        │
   │   Error: ENOENT: no such file or directory, scandir                    │
   │   '/Users/ael/Github/vsfnext/packages/commercetools/theme/lang'   │
   │                                                                        │
   ╰────────────────────────────────────────────────────────────────────────╯

**Comment by filrak** [comment]
Hye, I think this might be caused by this PR https://github.com/DivanteLtd/vue-storefront/pull/4469 I'll check it ASAP

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
