### ISSUE TITLE
DOMException on url with multiple trailing slashes

### ISSUE THREAD

**Issue by aloupfor** [vuestorefront/vue-storefront#4507]
## Current behavior
I open: https://demo.vuestorefront.io// (notice trailing `//`).
Page does not load properly.

https://demo.vuestorefront.io/////////////////////////// has the same behavior.

## Expected behavior
I open: https://demo.vuestorefront.io// (notice trailing `//`).
Page load properly.

I do not know if it should display the same content as https://demo.vuestorefront.io or be a 404 error.

## Steps to reproduce the issue
Open: https://demo.vuestorefront.io//

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
* Browser: Chromium Version 73.0.3683.75
* OS: Debian 9

## Additional information
Error displayed in browser console tab:

```
vue-router.esm.js:1697 Uncaught (in promise) DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https:' cannot be created in a document with origin 'https://demo.vuestorefront.io' and URL 'https://demo.vuestorefront.io//'.
    at it (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:20:13257)
    at new e (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:20:19375)
    at new Dt (https://demo.vuestorefront.io/dist/vendor.e0b36c61b90a056a40d7.js:20:23038)
    at s (https://demo.vuestorefront.io/dist/app.e0b36c61b90a056a40d7.js:1:293169)
    at https://demo.vuestorefront.io/dist/app.e0b36c61b90a056a40d7.js:1:346891
    at https://demo.vuestorefront.io/dist/app.e0b36c61b90a056a40d7.js:1:346507
    at Object.next (https://demo.vuestorefront.io/dist/app.e0b36c61b90a056a40d7.js:1:346612)
    at https://demo.vuestorefront.io/dist/app.e0b36c61b90a056a40d7.js:1:345548
    at new Promise (<anonymous>)
    at j (https://demo.vuestorefront.io/dist/app.e0b36c61b90a056a40d7.js:1:345293)
```

**Comment by gibkigonzo** [comment]
@aloupfor thanks for reporting this issue. It is related with vsf-router https://github.com/vuejs/vue-router/issues/2593 As I see it is fixed in v4 so I think that best way is just wait for it
