### ISSUE TITLE
check performance issues useHtmlMinifier/clientManifest

### ISSUE THREAD

**Issue by gibkigonzo** [vuestorefront/vue-storefront#4527]
## Current behavior

config `useHtmlMinifier` can multiply response time
with `useHtmlMinifier`:
![](https://user-images.githubusercontent.com/42383376/84108279-1ff44900-aa20-11ea-8e05-ef9a7c2f0d33.png)

without `useHtmlMinifier`:
![](https://user-images.githubusercontent.com/42383376/84108305-2aaede00-aa20-11ea-9afe-72c3e658a85f.png)

We need to check memory consumption after 
`const clientManifest = require(resolve('dist/vue-ssr-client-manifest.json')) in core/scripts/server.ts`

Memory dump before and after this :point_up: line in v1.8.0:
![](https://user-images.githubusercontent.com/42383376/84108538-ba548c80-aa20-11ea-8b3a-2df163b39aca.png)

Same on the v1.11.0 :
![](https://user-images.githubusercontent.com/42383376/84108557-c3ddf480-aa20-11ea-8794-3f6c569a12ee.png)

## Expected behavior

much smaller response time increase

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Environment details

* Browser: 
* OS: 
* Code Version: 

## Additional information

* check on demo instance
* check alternatives or what different flow we can apply

**Comment by pkarw** [comment]
The first one - you can safely disable the `htmlMinifier`  - that's not an issue. It can significantly increase the response time depending on the HTML Document length; however, this feature was intended to work with some form of output cache enabled - to overcome this issue

**Comment by pkarw** [comment]
The later one - from 1.9x on we're generating the `clientManifest` because it's required for the lazy-loading. I'm not sure if lazy-loading is doing well without this `clientManifest` imported. Do you have any observations regarding this? Reference: https://ssr.vuejs.org/guide/build-config.html#generating-clientmanifest
