### ISSUE TITLE
Region id is passing as 0 on vue storefront checkout

### ISSUE THREAD

**Issue by darshanperpule** [vuestorefront/vue-storefront#4531]
## Current behavior
Region id is passing as 0 when placing an order.

## Expected behavior
On vue storefront checkout, for region dropdown should display instead of a textbox.

## Steps to reproduce the issue
1) Go to vue storefront checkout
2) Go to the shipping address
3) try to add region

## Can you handle fixing this bug by yourself?
* [x] NO

## Environment details

* Browser: Google Chrome
* OS: Linux mint
* Node: 12.16.3
* Code Version: master branch

**Comment by pkarw** [comment]
Can you be more specific o nthis? I mean what do you mean by "try to add region"?

**Comment by darshanperpule** [comment]
Hi @pkarw 

I want to display region dropdown on the checkout page. Currently, it's a textbox. So it's passing region_id as 0 in both shippingAddress and billingAddress. That will throw an error in Magento 2 while placing an order "Region id is a required field".

**Comment by AishwaryShrivastav** [comment]
Hey guys, 
I am working on modifying the state input field to country based drop-down, and we can have JSON files for states, like we have for countries, and we will show the list of state based on default config and selected country. In starting we can have US state, people can add more.

**Comment by AishwaryShrivastav** [comment]
Will create a issue regarding this in capybara, will add states.json in core/i18n/resources in vsf and logic for the dependable dropdown in capybara. Make sense ?
