### ISSUE TITLE
separate server config from client config

### ISSUE THREAD

**Issue by gibkigonzo** [vuestorefront/vue-storefront#4546]
## What is the motivation for adding / enhancing this feature?

I think it would be great if we will have separated server config from client config. We can create `server.config.json` where we can move all properties that should be used only on server. Also we should add possibility for modules to have own config. For example in module there can be `server.config.json` and `default.config.json` which will be merged with app config.
I'm not sure if this can be done by node-config.

## What are the acceptance criteria 

* [ ] - create config that will be used only on server (for example `server.config.json`)
* [ ] - move properties related with server from default.config.json to server.config.json
* [ ] - add possibility to create config in module

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by philippsander** [comment]
I think having 2 files with duplicate content is the wrong approach since some config are needed in the client and the server.
Or am I understanding something wrong? What is actually the benefit of this and how would you define which settings are client only and which are server only?

From a security perspective I totally agree that some config settings should not be exposed to the client. I had the idea of implementing a "blocklist" of configs that are not exposed to the client. This is something I could implemented myself soon.

**Comment by philippsander** [comment]
Awesome! didn't know about this setting
