### ISSUE TITLE
vue-storefront-api installation issue on windows 10

### ISSUE THREAD

**Issue by boichoi** [vuestorefront/vue-storefront#4557]
## Prerequisites
i have installed latest version of vue-storefront-api
and follow the instuctions as provided in https://docs.vuestorefront.io/guide/installation/windows.html#installation-of-vue-storefront-api

but for some reason docker-compose up command not working.
ERROR: Service 'es7' failed to build: image operating system "linux" cannot be used on this platform

i m using Docker for windows version 2.2.0.3

regards

saleem

janmyszkier

**Comment by boichoi** [comment]
and in latest version of Docker it generate error like:

$ docker-compose up
Creating network "vue-storefront-api_default" with the default driver
Building es1
Step 1/2 : FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.11
 ---> b99307834e26
Step 2/2 : RUN bin/elasticsearch-plugin remove x-pack --purge
 ---> Running in 92a5c2cf3d37
-> removing [x-pack]...
ERROR: Service 'es1' failed to build: The command '/bin/sh -c bin/elasticsearch-plugin remove x-pack --purge' returned a non-zero code: 4294967295: failed to shutdown container: container 92a5c2cf3d375e0cae2ffcbead1aaa377401d4b86d7acc455d744178fb8703c3 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110): subsequent terminate failed container 92a5c2cf3d375e0cae2ffcbead1aaa377401d4b86d7acc455d744178fb8703c3 encountered an error during hcsshim::System::waitBackground: failure in a Windows system call: The virtual machine or container with the specified identifier is not running. (0xc0370110)

**Comment by pkarw** [comment]
@gibkigonzo do we still need this `'/bin/sh -c bin/elasticsearch-plugin remove x-pack --purge` ? maybe to avoid the issue we could have a second version of `docker-compose` setup just wor windows (?)

**Comment by pkarw** [comment]
@vue-kacper I know you had some  exp. on windows docker setup, hasn't you?

**Comment by vue-kacper** [comment]
@boichoi If you are on Windows 10, Version 2004, Build 19041 or higher, try WSL2 - it integrates well with Docker for Windows. Apart from better performance you'll get a much better development experience. 

Here you can find step-by-step instructions on how to install WSL2 and configure Docker:

https://code.visualstudio.com/blogs/2020/03/02/docker-in-wsl2

**Comment by andres-linares2211** [comment]
I'm using WSL2 and it runs without problems, just to confirm :smile:
