### ISSUE TITLE
Optimize price display formatting

### ISSUE THREAD

**Issue by simonmaass** [vuestorefront/vue-storefront#4564]
## What is the motivation for adding / enhancing this feature?

core/filters/price.js line: 35

why dont we leverage the function toLocaleString more?

`const options = { style: 'currency', currency: currencyCode, minimumFractionDigits: fractionDigits, maximumFractionDigits: fractionDigits };`

if we insert style and currencyCode we dont need to applyCurrencySign for example.... what do u think?

the seperators are also set fine... so why use replaceSeparators?

and if we dont do the Math.abs the negative sign is also included fine for me:

```
(-99).toLocaleString('de-DE', { style: 'currency', currency: 'EUR' })
"-99,00 €"
```

## What are the acceptance criteria 

* [ ] Price display formatting simplified

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a normal feature request. This should be available on https://test.storefrontcloud.io and then after tests this can be added to next Vue Storefront version. In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] (**Pick this option only if you're sure**) This is an important improvement request for current Release Candidate version on https://next.storefrontcloud.io and should be placed in next RC version. In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] (**Pick this option only if you're sure**) This is a critical improvement request for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version. In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pkarw** [comment]
@simonmaass won't it increase the bundle size?

**Comment by simonmaass** [comment]
browser support is not that great... would therefore maybe not recommend in the end...

![image](https://user-images.githubusercontent.com/32599710/93325897-4f350600-f818-11ea-88af-3ec0bcc5a6d3.png)

and pollyfil would indeed increase bundle size... i will just close this...

**Comment by Qrzy** [comment]
@simonmaass I think you missed the `BigInt` when you checked caniuse.com for support. 
It doesn't list support for `Number.prototype.toLocaleString`, but MDN says it's supported from very early versions and the only problem with IE/Edge is limiting precision to 15 decimal digits:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
After all, I don't think using more of its options would increase bundle size.

**Comment by simonmaass** [comment]
@Qrzy good point - thank you!

**Comment by simonmaass** [comment]
![image](https://user-images.githubusercontent.com/32599710/93337639-b0b1a080-f829-11ea-9ea4-cccf95fc1e14.png)

**Comment by simonmaass** [comment]
@pkarw @gibkigonzo here my suggestion...
