### ISSUE TITLE
Order History Pagination Not Working Properly 

### ISSUE THREAD

**Issue by AishwaryShrivastav** [vuestorefront/vue-storefront#4599]
## Current behavior

**Issue** : While viewing order history, the user can not see more than 20 orders.

**Why its not working** : lazyLoadOrdersOnScroll implemented on the order history page, calls getOrdersHistory,
which previously used to fetch all the orders, but on introducing pagination support in "getOrdersHistory", it only fetches 20 orders, which is its default value. 
Still, the order history page calls it only once, trying to fetch all the results, and on those results, it applies lazyLoadOrdersOnScroll.

Due to which the user can not see more than 20 orders. 

## Expected behavior

User should be able to see all the orders while scrolling through the order history page.

## Steps to reproduce the issue

1. Login with a valid user having more than 20 orders.
1. Go to profile.
1. Click on order history.
1. Scroll down to view more orders.

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by AishwaryShrivastav** [comment]
Here is a video for this issue's fix for better understanding of everyone  https://www.youtube.com/watch?v=rjjcb3-AfII&feature=youtu.be

**Comment by Fifciu** [comment]
@AishwaryShrivastav this issue has been solved using your code base by @lukaszjedrasik . Both of you are marked as authors of the fix.
