### ISSUE TITLE
Why are the polyfills used the way they are?

### ISSUE THREAD

**Issue by domideimel** [vuestorefront/vue-storefront#4612]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

I'm looking to get a better bundle size so our performance gets even better. Don't get me wrong, the performance improvements with 1.12.X are incredible!!

I made a test build on my machine and enabled BundleAnalyzer to get an overview over my bundles and whats in them. There I discovered that in vendor ist a big portion of core-js polyfills. 

After seeing this i started looking why this is and found this:
https://github.com/DivanteLtd/vue-storefront/blob/b02d06cb798f2bff65b38a9e5ddd04b11e27930a/core/build/webpack.base.config.ts#L80
But there is a babel.config.js in the root too?

When using the default way of applying polyfills a get this as a bundle 
![before](https://user-images.githubusercontent.com/32941053/87126922-56c2b680-c28d-11ea-862d-abd740b21f5b.png)

But when using it the follwing a get a smaller, but polyfilled bundle.
- remove https://github.com/DivanteLtd/vue-storefront/blob/b02d06cb798f2bff65b38a9e5ddd04b11e27930a/core/build/webpack.base.config.ts#L80
- change babel.config.js

```javascript
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        'modules': false,
        'useBuiltIns': 'usage',
        'corejs': 2
      }
    ]
  ],
  plugins: ['@babel/plugin-syntax-dynamic-import'],
  env: {
    test: {
      plugins: ['transform-es2015-modules-commonjs', 'babel-plugin-dynamic-import-node'],
      ignore: [/node_modules\/(?!lodash-es|@vue\/test-utils)/]
    }
  }
}
```
![after](https://user-images.githubusercontent.com/32941053/87126652-da2fd800-c28c-11ea-9706-9ffd3a33e2ca.png)

With the babel.config.js way I got a ~ 60% improvement of polyfill sizes compared to before!

Is there a reason for you to not use the second way I described?

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [x] A brief description of the problem,
- [x] Where the problem is occurring,
- [ ] The length of time the problem has been occurring,
- [ ] The size of the problem.

**Comment by cartok** [comment]
Looks like core-js is not even installed. Also there is version 3 out there. https://babeljs.io/docs/en/babel-preset-env

**Comment by domideimel** [comment]
CoreJS is installed. I think it's a dependency of the Babel polyfill.

I know CoreJS 3 is out but unfortunately I can't get it work. I installed it and changed the CoreJS to 3 and during compilation there came always an error that some the files are not found.

**Comment by cartok** [comment]
Yes thats true but that does not mean that it is used properly.

**Comment by domideimel** [comment]
I've actually no idea why it behaves like this.. 
maybe someone from the core team can tell us more

**Comment by pkarw** [comment]
I think this is just something we need to get fixed. This snippet is with us from 0.3 I guess and no body jus realized it’s causing bigger bundle! :-) great hint. Can you propose a PR @domideimel  please?

**Comment by Fifciu** [comment]
Unfortunately, removing `'@babel/polyfill'` from webpack config breaks app for most users.

**Comment by cartok** [comment]
I think in this PR it got removed but not replaced. It's just deprecated since babel 7.4 as you can see on the top of https://babeljs.io/docs/en/babel-polyfill  

Replacing should works like this: https://www.thebasement.be/updating-to-babel-7.4/  

But propably it's better to clean up the dependencies first. Many of the dependencies in core/package.json can be set as peerDependency to get rid of confusion.
