### ISSUE TITLE
Does it make sense to add kind of AntiXSRF tokens between VSF and VSF-API?

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#4624]
I was wondering about adding a validation/auth tokens between VSF and VSF-API. I'm writing only about the **open catalog queries**. So this is more about **anty-scrapping** (not letting the external users to query more data than VSF is requiring) and probably adding a per-requesting token filtration, quotas etc. 

How it could potentially work? It could work like Anti-CSRF tokens ([OWASP reference](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html))

1. `vue-storefront-api` has a special, configurable secret-key within the `config/default.json` - `config.auth.client_access_key`
1. `vue-storefront` has a special, configurable secret-key within the `config/default.json`  which is in sync with the `vue-storefront-api` - the same value and variable name: `config.auth.client_access_key`
1. `vue-storefront-api` exposes an endpoint over `/api/token` that generates time-sensiteve AntiCSRF tokens that need to be added to all sub-sequent queries
1. `vue-storefront/core/scripts/server.ts` is requesting the AntiCSRF token with a first SSR request (Caching can be a huuuuuuuge complication here; please remember that we're using SSR cache. The token should be obtained whetever the request is cached or not - and then should be [injected into cached HTML dynamically here](https://github.com/DivanteLtd/vue-storefront/blob/6aa904c655b9c77b6734dc2939a021b33298227f/core/scripts/server.ts#L267) or [here](https://github.com/DivanteLtd/vue-storefront/blob/6aa904c655b9c77b6734dc2939a021b33298227f/core/scripts/server.ts#L226). The HTML with injected AntiCSRF token shouldn't be cached). The injection can be made by simply adding a `context.output.renderToken()` to the SSR [context object](https://github.com/DivanteLtd/vue-storefront/blob/6aa904c655b9c77b6734dc2939a021b33298227f/core/scripts/utils/ssr-renderer.ts#L109) the same way [the state is being rendered](https://github.com/DivanteLtd/vue-storefront/blob/6aa904c655b9c77b6734dc2939a021b33298227f/src/index.template.html#L14). This method can simply output the `window.__SSR_TOKEN__={{tokenFromTheAPI}}`. Another option would be to modify the [`applyAdvancedOutputProcessing`](https://github.com/DivanteLtd/vue-storefront/blob/6aa904c655b9c77b6734dc2939a021b33298227f/core/scripts/utils/ssr-renderer.ts#L65) function, however it's not being applied after the Cache HIT.
1. The `SearchAdapater` must add this AntiCSRF token from `window.__SSR_TOKEN__` to all subsequent request. It could [be added here](https://github.com/DivanteLtd/vue-storefront/blob/6aa904c655b9c77b6734dc2939a021b33298227f/core/lib/search/adapter/api-search-query/searchAdapter.ts#L84) or [here](https://github.com/DivanteLtd/vue-storefront/blob/6aa904c655b9c77b6734dc2939a021b33298227f/core/lib/search/adapter/api/searchAdapter.ts#L85) to support both `api` and `search-query` adapters.
1. The `vue-storefront-api` or `storefront-api` must validate the token (using the `config.auth.client_access_key` used to initially generate it) if it came from the `vue-storefront-api` within the [`catalog.js` endpoint](https://github.com/DivanteLtd/vue-storefront-api/blob/7c2cf9b845fe93f761f3fb526d48e689a3afc42a/src/api/catalog.ts#L70)

**PROS**

* you can't query `vue-storefront-api` without a proper token which is generated based on secret key (as it's `core/scripts/server.ts` generating the token, the secret key is not exposed to the users)
* you can limit how tokens are generated or for whom (throttling etc)
* tokens are time-sensitive (eg. 24h) so they change a lot
* this give you higher probability ratio that the query coming to `vue-storefront-api` was authentic and really created by `vue-storefront`

**CONS**

* if the user is pretty  much motivated they can still just **parse out** the `window.__SSR_TOKEN__` from the HTML document and subsequently use it for querying the API

gibkigonzo andrzejewsky lukeromanowicz what do you think about it? do you find another way to secure and authenticate the catalog requests?

ps1. Users can simply [limit the scope of the data that can be accessible via `vue-storefront-api` with this PR](https://github.com/DivanteLtd/vue-storefront-api/pull/476) and Elastic DSL is by [default disabled within VSF1.12](https://github.com/DivanteLtd/vue-storefront-api/pull/390/files#diff-1c1dccf8e51ee40b3321b647cee837b8R56)

ps2. All the user-related actions are secured with javascript tokens, this is not a RFC about security in general but about securing the catalog operations

**Comment by lukeromanowicz** [comment]
CSRF is a domain of Multi-Page Apps and badly designed APIs. As far as I remember our API doesn't do any actions over GET and requires auth token for all user-related actions. I would rather go towards implementing two tokens JWT auth than adding needless complexity for issues we don't deal with.

Anti-scrapping should be handled by external WAF.

**Comment by knightfoxapps** [comment]
We just went through a PCI Audit and CSRF was flagged. So I do believe something to that effect should be added.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
