### ISSUE TITLE
Performance Imporvement Required for Mobile Website for https://capybara.storefrontcloud.io/

### ISSUE THREAD

**Issue by karan0227** [vuestorefront/vue-storefront#4643]
![Capybara Coverage Report](https://user-images.githubusercontent.com/5475470/87943645-f1a46780-cabb-11ea-831f-f00b07c9d509.png)
[CapybaraPageSpeedReport.pdf](https://github.com/DivanteLtd/vue-storefront/files/4947970/CapybaraPageSpeedReport.pdf)

Hi ,
Please have a look at the coverage report and Page Speed insights reports for https://capybara.storefrontcloud.io/.
I see 2 things 

1. Basis the PageSpeed Report the score for mobile website is very low 33. Would like to increase this is to close to 90.
1. If you look into the coverage report there is lots unused js in bundled js(Some close to even 90% unused) files even after using tree shaking sideEffect for the capybara theme.

We are customising the capybara theme for our product . So if the performance is improved for capybara.storefrontcloud.io . We can incorporate those changes in out product and improve our performance.

Please rectify this at the earliest.

Thanks ,
Karan Kesarwani

**Comment by pkarw** [comment]
Hi, we all should be working on the performance optimization howevet this is a pretty complex task. Can you please work on this issue more in details adding more granular issues rather than one single one as this? I think it's not very couraging people to take care of this issue: it's too complex and not actionable

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
