### ISSUE TITLE
Shorten the compilation times with `vsf1-local-webpack`

### ISSUE THREAD

**Issue by pkarw** [vuestorefront/vue-storefront#4646]
Reference: https://www.yireo.com/blog/2020-05-22-improving-vue-storefront-compilation-times

Thanks to jissereitsma we've got a really awesome, new webpack configs to speed-up the development times by an order of magnitude. The magic happens when you disable the SSR (which is very rarely required for development mode, local deployment)

VSF1 local webpack: https://github.com/yireo-training/vsf1-local-webpack

Acceptance Criteria:

1. We've got this new webpack build files included in the core within the `core/build`
1. The **existing development command** (`yarn dev`) now starts the dev mowde with the new webpackfiles - so it's the equivalent of [`happydev`](https://github.com/yireo-training/vsf1-local-webpack#installation)
1. The **new command** is added for the development mode including the SSR: `yarn dev:ssr` or `yarn dev-with-ssr`

**Comment by jissereitsma** [comment]
I would be honored if this could be added. The only thing that was really bugging me when putting together the Webpack configuration was that `dayjs` needed to be downgraded: It is in the core and their later release was containing a bug which required TypeScript, while actually my Webpack script would run with regular Node instead. Perhaps this is fixed already, but one would notice simply when firing up the `yarn` command.

What needs to be done?
