### ISSUE TITLE
[BUG] Styles built in reverse when NODE_ENV=production

### ISSUE THREAD

**Issue by slri** [vuestorefront/vue-storefront#4663]
**Describe the bug**
The style order is reversed in production. Higher importance styles should be at the bottom of the compiled CSS, but they're at the top instead. Using SfTabs makes them take `sf-button` and `sf-button--pure` over `sf-tabs__title` making them look the opposite of what they should look like.

**How to reproduce**

1. Setup a VSF instance
1. Include Storefront UI as a dependency for default theme
1. Add dummy SfTabs to Home.vue (just an example, in theory it could be anywhere) 
1. Set NODE_ENV to production
1. Rebuild
1. Check styles and at what point are they rendered (sf-tabs__title should be rendered somewhere near the top)

**Expected behavior**
The order of the styles doesn't change.

**Actual behavior**
Order of styles is reversed.

**Devices (please complete the following information):**

* Device: Any
* OS: Any
* Browser: Any

**Additional context**
node 10.20.1
vsf 1.12.0
vsf-default 1.12.0
sfui/shared 0.7.17
sfui/vue 0.7.18

**Comment by mohammad-k8** [comment]
I am experiencing similar kind of issue on prod env with version 0.7.11 too.

**Comment by mohammad-k8** [comment]
@slri any fix/clue on this?

**Comment by slri** [comment]
This issue is still ongoing, but I come here with more info.
First thing's first, I should describe the issue in a bit more detail: What I mean by styles being built in reverse is that style chunks' order is in reverse. Lets use the example from above. We have 1 chunk which contains the class `.sf-tabs__title`, and another which contains `.sf-button` and `.sf-button--pure`.
What it looks like when `NODE_ENV=dev` (correct order):
```
.sf-button
.sf-button--pure
...
.sf-tabs__title
```
What it looks like when `NODE_ENV=production` (incorrect order):
```
.sf-tabs__title
...

.sf-button
.sf-button--pure
```

This only happened on vsf-default theme (to my knowledge). vsf-capybara **doesn't** have this issue. For this and many other reasons we've decided to switch to vsf-capybara, abandon vsf-default completely, and so I won't be able to give you any more info on the issue going forward.

**Comment by szduda** [comment]
We have experienced differences in styles order when in production mode as well. Unfortunately I cannot provide any helpful information since I could not find any clue or reason behind that. In our case it was enough to append `!important` modifier to few colliding styles, but this is not a proper solution.

**Comment by enzo-vezzaro-eleva** [comment]
any news about this. I'm having the same issue
