### ISSUE TITLE
[RFC] Discuss Form Builder

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#4681]
We have an alignment that forms are a pretty common part of the app and creating them each time is repetitive work. Additionally, for some cases creating a form, becomes very specific thing for the platform (eg. address form - can be different in each eCommerce platform) which can break our agnostics. 

The goal is, to create a generic form builder where we can delegate creating a form to and provide an interface for creating certain form fields in each eCommerce platform.

# Proposal
## Agnostic form type
First of all, our composables will return an additional field called `form`

* that field will contain a form object using a new agnostic type `AgnosticForm`.

```ts
interface AgnosticFormField {
 name: string;
 type: string;
 value?: any;
 group?: string;
 options?: any[];
 onChange?: (field: AgnosticFormField, currentDataModel: AgnosticForm) => {};
}

interface AgnosticForm {
 name: string;
 fields: AgnosticFormField[];
}
```

## Defining and extending form fields
In order to configure our fields, we need to introduce a data model defining mechanism. That's the way how we can configure a form fields inside of specific integration, An example of that system can look like this:

```ts
const factoryParams = {
  loadCheckoutCustomer () {
    const customer = await customerAPiCall();

    return { customer };
  },
  form ({ customer }) {
    return {
     firstName: { type: 'input', value: customer?.value.firstName ?? '' },
     lastName: { type: 'input',  customer?.value.lastName ?? '' },
    country: { type: 'select', options: [1, 0] }}
   }
}
```

So inside of the factory params, we are able to define what form we want to see on the UI. Our form building mechanism will take care of everything in order to render it properly.

Furthermore, there is also a way to extend that form across the app, if there is a need to change some of the fields across the app.

```ts
import { extend, formDataModels } from '@vue-storefront/commercetools`

extend(formDataModels.checkout, async (currentDataModel: AgnosticForm)  => {
  ...currentDataModel,
  firstName: { type: 'input', },
  isCompany: { type: 'radio' },
  country: { type: 'select', options: currentDataModel.countries.options }
})
```

We are calling a function `configureFormDataModel` that takes as a first argument an identifier of the data model we want to define and function which define that data model as second. Given function is an async one because of supporting dynamic form in the future (eg. adding a field on demand, react on some response, etc.). As an argument of this function, -  we have current configured data model which opens a way for overriding that form (use dot notation for re-use or skip if you want to totally override the form).

## Rendering
First of all, our core of form builder will be an agnostic component that takes form object (AgnosticForm) and renders it according to the configured data model. The following example presents that situation:

```ts
<template>
 <FormBuilder :dataModel="form" @submit="handleSubmit" />
</template>

export default {
 setup() {
   const { form, saveShippingAddress } = useShippingAddress();
   const handleSubmit = async (formData) => {
    // form data here is a pure json structure { fieldName: value }
    saveShippingAddress(formData);
   }

  return {
    form,
    handleSubmit
  }
 }
}
```

We are taking a `form` property from `useShippingAddress` and passing it into the template where `FormBuilder` does its job. Secondly, we have implemented `handleSubmit` function that is responsible for sending the form fields. Please notice that `handleSubmit` we have pure json structure of the form representation where keys are the field names and the values are the corresponding field values.

Once we have this there are two issues that need to be solved:

1. Rendering fields within one line
1. Custom markup

The general idea of rendering that form is to use `render` function with `createElement` helper. That simplifies a lot. Let's assume that we'll be rendering the form in the following schema:

* all form is closed inside of tag `form`
* each field is rendered in the one div
* fields that need to be in the same line are wrapped in additional div
* for styling, we can add another field in our form model or define it directly using a prop `<FormBuilder :classFor="{ fieldName: className }" />

_First problem: rendering fields in the one line._
That's pretty simple to solve, adding a group property into the form model definition. The fields labeled with a same group name will be rendered within one line

_Second problem: custom markup_
That one is more complicated, but I think we can use slots for this. We can define slots for each case of rendering: single field, row (fields in the one line) or specific field name:

```ts
<template>
<FormBuilder :dataModel="form" @submit="handleSubmit">
  <template #sigleField="{ field }">
    <div>single field markup</div>
  </template>
  <template #row="{ fields }">
    <div>fields row markup</div>
  </template>
  <template #firstName="{ field }">
    <div>markup for specific field (firstName in this case)</div>
  </template>
</FormBuilder
<template>
```

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-200) by [Unito](https://www.unito.io/learn-more)

**Comment by filrak** [comment]
Ref https://github.com/DivanteLtd/vue-storefront/issues/4576
