### ISSUE TITLE
Incorrect load of default address in checkout

### ISSUE THREAD

**Issue by ArturDivante** [vuestorefront/vue-storefront#4682]
## Steps to reproduce the issue
1. Open https://next.storefrontcloud.io/
1. Prepare an account with existing, filled shipping details, and login to it
1. Add some products to cart and proceed to checkout
1. In checkout, click "continue to shipping'

## Current behavior
Even though default address checkbox is checked, form is not filled with data, it only contains names and country.

It only gets correctly filled, when we uncheck and check the box again.
![Default Address](https://user-images.githubusercontent.com/47415585/88669202-e5379480-d0e3-11ea-90e3-060527205f59.gif)

## Expected behavior
Shipping form should be correctly filled at once, if shipping address is available for this account

## Version of Vue Storefront
next.storefrontcloud.io

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Environment details

* Browser: Latest Chrome
* OS: Ubuntu

**Comment by dSurprenant** [comment]
It happen when in the Local Storage you dont have all the appropriate value : 

**(this is when your not log and never whent to the cart)**
![image](https://user-images.githubusercontent.com/29876551/89725350-95f33d00-d9dc-11ea-974f-5e354705fb80.png)

**(this is when you pass the profile and are about to enter details in the shipping forms...)**
![image](https://user-images.githubusercontent.com/29876551/89725361-c5a24500-d9dc-11ea-9ea9-79f27fe3249f.png)



in the file `core/modules/user/index.ts`

make your logic and dispatch to "checkout/saveShippingDetails"

![image](https://user-images.githubusercontent.com/29876551/89725314-2bda9800-d9dc-11ea-844e-3dfdc6873cc3.png)
