### ISSUE TITLE
Cart sync issue - wrong totals

### ISSUE THREAD

**Issue by szduda** [vuestorefront/vue-storefront#4690]
## Current behavior
Quickly removing subsequent products from cart ends up with sending multiplicated api requests. Some of those (surprisingly it is not every second and over) ends up with 404 response since they have already executed. At this point sync actions payloads get messed up and we end up seeing wrong totals in cart. Below I post a screen of what we get after repeating the simple scenario (add 4 products to cart, delete 3 of them quickly).

![image](https://user-images.githubusercontent.com/22805347/88809971-07e5ae00-d1b5-11ea-974f-b2bf3fd592fd.png)

## Expected behavior
* Each request deleting product should be sent once.
* Totals should be calculated correctly

## Steps to reproduce the issue
* Add 4 products to cart
* Remove 3 of them quickly

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by pablogiralt** [comment]
@szduda in case it helps, in our project we disabled the delete button while cart is busy to prevent this behaviour

**Comment by szduda** [comment]
@pablogiralt Thanks, I think we have chosen the very same solution in the end. But to be honest I don't like it. One of the reasons to try VSF was to provide better responsiveness, more async features. Waiting few seconds so it can complete&confirm every CRUD operation can drive me crazy, but I understand its a rare case to delete 5+ products from cart at once (unless you are a dev). If any wait for sync is required it should be only in "totals" IMO. Now it looks like for the sake of easiness in handling edge case scenarios we agree to noticeably lower the UX of more regular scenarios.

**Comment by pablogiralt** [comment]
@szduda Im not happy either with the solution... but it is what I came up quickly until we have time to check it properly...

Also, even with that, we where still having issues with cart trying to sync several time simultaneously. We end up creating a custom mutation and checking for this when syncing cart to prevent it to execute twice at the same time: 

In our sync action (we use a custom action for this):
```
if (state.isCartSyncing) {
      Logger.warn('Cart busy, cant execute sync', 'cart')()	    
      return false;
}
```

And the custom mutation:
```
[CART_SYNC_STANCE] (state, stance) {
   state.isCartSyncing = stance
}
```
