### ISSUE TITLE
[RFC] Command pattern based composables and extensibility

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#4726]
Right now we are on the way to implement extensibility mechanism, that will give us the ability to extend either integration or core code. Recently I was experimenting with how the command pattern can help us with that and I have the following proposal:

* let's keep just state in the composables
* rest of logic is moved to the commands
* as composables must pass the interfaces for the agnostic theme we need to have set od default commands that always needs to be implemented
* each of command is exported so it can be reused or extended (explain later)

## Implementation
Let's consider the following cart factory

```ts
const createUseCart = factoryParams => {
  const cart = ref([]);
  const loading = ref(false);

  const execute = async command => {
    await command({ cart, loading });
  };

  const useCart = () => {
    const addToCart = async ({ product, query }) => {
      await execute(factoryParams.addToCart({ product, query }));
    };

    const removeFromCart = async ({ product, query }) => {
      await execute(factoryParams.removeFromCart({ product, query }));
    };

    return { cart, addToCart, removeFromCart, execute };
  };

  return useCart;
};
```

We are sharing `addToCart` and `removeFromCart` as it's needed for agnostic theme but please notice that the implementation of these is moved to the commands that come from `factoryParams`. We also share the `execute` function to call whatever command you want on this composable so you are able to inject and change all of the states inside.

Now, let's move to the integration part. The usage of that factory can look like this:

```ts
export const addToCartCommand = ({ product, query }) => async ({ cart, loading }) => {
  loading.value = true;
  cart.value = await fakeApiCall(product, query);
  loading.value = false;
};

export const removeFromCartCommand = ({ product, query })  => async ({ cart, loading }) => {
  loading.value = true;
  cart.value = await fakeApiCall(product, query);
  loading.value = false;
};

const defaultCommands = {
  addToCart: addToCartCommand,
  removeFromCart: removeFromCartCommand
};

const factoryParams = {
  ...defaultCommands
};

export default createUseCart(factoryParams);
```

All of the business logic is encapsulated in the dedicated commands. As they are pure functions, it's super easy to test them. We also expose all of them (including an object with default ones) so you can import if there is such a need. 

## Usage
Considering that we are working on a project that uses some integration, so we want to use it:

```ts
import { useCart } from '@vue-storefront/integration'

const { addToCart, removeFromCart } = useCart();
```

Nothing changes even though we have changed the implementation, but let's move forward.

### Extending addAddToCart
What if you want to extend addToCart function or maybe override it totally? Here is an example:

#### Overriding
```ts
import { defaultCommands } from '@vue-storefront/integration'

const addToCartCommand = ({ product, query }) => async ({ cart, loading }) => {
  // some extended logic
  loading.value = true;
  cart.value = await fakeApiCall(product, query);
  loading.value = false;
};

const factoryParams = {
  ...defaultCommands,
 addAddToCart: addToCartCommand
};

const useCart = createCart(factoryParams)

const { addToCart, removeFromCart } = useCart(); // still passing same interface
```

#### Extending
```ts
import {
 defaultCommands,
 addToCartCommand as oldAddToCartCommand // 1
} from '@vue-storefront/integration'

const addToCartCommand = ({ product, query }) => async ({ cart, loading }) => {
  // some extended logic
  const oldCommand = oldAddToCartCommand({ product, query }) // 2
  loading.value = true;
  cart.value = await fakeApiCall(product, query);
  loading.value = false;
  oldCommand({ cart, loading }) // 3
};

const factoryParams = {
  ...defaultCommands,
 addAddToCart: addToCartCommand
};

const useCart = createCart(factoryParams)

const { addToCart, removeFromCart } = useCart(); // still passing same interface
```

Using that you can change the behavior of the composable function: extend or override it totally

### Extending addAddToCart query
In case if you want to change just one argument to the command such as query to the API or something else you can achieve it by doing something like this:

```ts
import { defaultCommands, addToCartCommand } from '@vue-storefront/integration'
const query = {} // some query

const factoryParams = {
  ...defaultCommands,
 addAddToCart: ({ product }) => addToCartCommand({ product, query })
};

const useCart = createCart(factoryParams)

const { addToCart, removeFromCart } = useCart(); // still passing same interface
```

In this case, we simply override just one argument, the most likely some API params (query, limits etc.)

### Extending entire composable
That's the most powerful thing in command pattern - you are able to add any functionality to the existing code without touching it. Assuming that you need to add a new function to the existing composable that will modify the internal state, you can simply do it by the implementation of your own command, example:

```ts
import { useCart } from '@vue-storefront/integartion'

const myOwnCommand = ({ product }) => async ({ cart, loading }) => {
 // do something
};

const { execute } = useCart();

execute(myOwnCommand({ ... }))
```

Because we share also `execute` function so it's possible to call any command you need without even do any changes in the original composable.

#### Summary
it's just an idea maybe only some of the small pieces of that is feasible or maybe it's great but we need to challenge that if it covers our needs. The biggest advantage of the command pattern is we have separation of concerns and encapsulated logic which comes with easier testing and less code actually. On the other hand, it's a new API and using that may look complex at first sight. Feel free to comment.

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-218) by [Unito](https://www.unito.io/learn-more)

**Comment by lukeromanowicz** [comment]
To me it sounds like another take on Vuex with a little bit more flexibility in mind. What buggs me is:
> let's keep just state in the composables
as some shared state is kept outside composables. I'm also worried about the possibility to add new properties while extending a composable.

Other than that it looks pretty promising! (because every action needs to be treated a promise :grinning: )
