### ISSUE TITLE
Wrong grand total in cart if cart gets manipulated by different browser tabs. (same session, sync works only partial)

### ISSUE THREAD

**Issue by NicolasHofmairT23** [vuestorefront/vue-storefront#4733]
## Current behavior

Grand Total is wrong in browser tab 1 if user adds product in browser tab 2 (same session). The cart list of products gets synced but grand total not. (Side note: In https://vsf-next-demo.storefrontcloud.io/ the cart sync between browser tabs seems not to work at all)

## Expected behavior

Micro Cart (including grand total) should be always in sync and same state in all browser tabs.

## Steps to reproduce the issue

1. Add product to cart. f.e. this one https://demo.vuestorefront.io/didi-sport-watch.html

2. Open new browser tab, then open Micro cart. Everything looks fine.

3. Change cart by changing quantity or adding another product from PDP in one of the browser tabs.

4. Product list gets synced to the other browser tab session. Grand total stays old and is therefore wrong.

## Repository
https://demo.vuestorefront.io/

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
- Browser: Chrome, latest version
- OS: IOS
- Node: https://demo.storefrontcloud.io
- Code Version: https://demo.storefrontcloud.io

**Comment by andres-linares2211** [comment]
Hi all, I'm thinking in a solution for this and maybe the path we could take is to store the totals in localstorage.
It sounds a bit absurd as we are calculating the grand total when we are offline and therefore not even using localstorage. But with localstorage we can share the data among different tabs.

by the way, is not only the grand total but all the totals in the object `platformTotalSegments` that are not sync

**Comment by Fifciu** [comment]
Done. I've used localStorage as @andres-linares2211 suggested
