### ISSUE TITLE
Add meta tags to product page

### ISSUE THREAD

**Issue by gund** [vuestorefront/vue-storefront#4743]
## Prerequisites
Please answer the following questions for yourself before submitting an issue. 

* [x] I am running the latest version
* [x] I checked the documentation and found no answer
* [x] I checked to make sure that this issue has not already been filed

Is it possible to add meta tags like description to the product page that is set from the API?
I could not find any information on this topic in documentation.

**Comment by gibkigonzo** [comment]
yes, you can do this here https://github.com/DivanteLtd/vsf-capybara/blob/develop/pages/Product.vue#L214-L230 Load data in asyncData and then just use getters to use it in `metaInfo`.
