### ISSUE TITLE
VSF NEXT: useCheckout `loading` is not reliable

### ISSUE THREAD

**Issue by EugeneHlushko** [vuestorefront/vue-storefront#4752]
## Current behavior

```
const {
      billingDetails,
      shippingDetails,
      setBillingDetails,
      loadDetails,
      loading
    } = useCheckout();
onSSR(loadDetails);
```

Now if i print out the value of loading, it is always `false` for each of the loading indicators available in `useCheckout()`:

```
       console.log(loading.value.shippingAddress); // false
        console.log(loading.value.billingAddress); // false
        console.log(loading.value.personalDetails); // false
        console.log(loading.value.paymentMethods); // false
        console.log(loading.value.shippingMethods); // false
        console.log(loading.value.order); // false
```

Now say you are looking at loading indicator, it is `false`. But, looking at `billingDetails.value.country` and `shippingDetails.value.country` changes without loading indicator changes or user input, it does look like a race condition or a problem with how you populate the value of a reactive property such as in function `createSetBillingDetails`. Here is a log output when billingDetails and `billingDetails.value.country` and `shippingDetails.value.country` change in moments of time after mounting the component with the above code:

          // right after checking that loading is `false` for all loading indicators shown above.
          console.log(billingDetails.value.country); // undefined
          console.log(shippingDetails.value.country); // undefined
          // next time billingDetails has updated value without other calls or user input, ie in a few ms
          console.log(billingDetails.value.country); // US
          console.log(shippingDetails.value.country); // US## Expected behavior

I can rely on loading indicators to know that current value of billingAddress has loaded and its either empty or has data when loading indicator stays `false`.

## Steps to reproduce the issue

**example.vue**

```vue
<template>
  <div v-if="logLoading()">
    {{ JSON.stringify(billingDetails) }}
  </div>
</template>

<script>
import { useCheckout } from '@vue-storefront/commercetools';
import { onSSR } from '@vue-storefront/core';
export default {
  setup(props, context) {
    const {
      billingDetails,
      shippingDetails,
      loadDetails,
      loading
    } = useCheckout();

    onSSR(async () => {
      await loadDetails();
    });

    return {
      billingDetails,
      shippingDetails,
      loading,
      logLoading: () => {
        console.log(loading.value.shippingAddress); // stays false
        console.log(loading.value.billingAddress); // stays false
        console.log(loading.value.personalDetails); // stays false
        console.log(loading.value.paymentMethods); // stays false
        console.log(loading.value.shippingMethods); // stays false
        console.log(loading.value.order); // stays false
        console.log(billingDetails.value.country); // changes from undefined to US in next consecutive log without user interaction
        console.log(shippingDetails.value.country); // changes from undefined to US in next consecutive log without user interaction
        return true;
      }
    };
  },
}
</script>

```

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by filrak** [comment]
Will most likely be fixed with the new checkout https://github.com/DivanteLtd/vue-storefront/issues/4576. If we won't get into that topic this month we will first solve this issue with old API. Is that ok?

**Comment by EugeneHlushko** [comment]
@filrak it is breaking the user experience in case of page reload on payment step/shipping steps, so either way we'd need this in vsf by early September latest to have time to upgrade on our side and re-test/adjust logic.

**Comment by filrak** [comment]
@EugeneHlushko got it, will be taken care of

**Comment by EugeneHlushko** [comment]
@filrak was there any progress on this issue? Did anyone have a look?

**Comment by filipsobol** [comment]
`useCheckout` composable was removed in `1.2.0`
