### ISSUE TITLE
Make sure api-client should work independently

### ISSUE THREAD

**Issue by aureate-labs-team** [vuestorefront/vue-storefront#4755]
## What is the motivation for adding/enhancing this feature?
* The `api-client` should work independently without composables

## What are the acceptance criteria 

* [x] Move some necessary code from `composables` to `api-client`

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [ ] YES
* [ ] NO

## Additional information

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-229) by [Unito](https://www.unito.io/learn-more)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
