### ISSUE TITLE
Move cookie part from `composables` to `api-client`

### ISSUE THREAD

**Issue by aureate-labs-team** [vuestorefront/vue-storefront#4756]
## What is the motivation for adding/enhancing this feature?
* Do not modify the output of composables directly in it.

## What are the acceptance criteria 

* [ ] Set and get Cookie should in api-client

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [ ] YES
* [ ] NO

## Additional information

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-230) by [Unito](https://www.unito.io/learn-more)

**Comment by filrak** [comment]
actually please hold on with that. We're discussing the best approach with @andrzejewsky

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
