### ISSUE TITLE
Cleanup or implement blank methods. Correct name for some methods.

### ISSUE THREAD

**Issue by aureate-labs-team** [vuestorefront/vue-storefront#4757]
## What is the motivation for adding/enhancing this feature?
* The code of `clearCart` and `isOnCart` is missing
* Rename the method name `fetchCartLineItem` as its finding not fetching

## What are the acceptance criteria 

* [x] Implement clean code

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [ ] YES
* [ ] NO

## Additional information

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-231) by [Unito](https://www.unito.io/learn-more)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
