### ISSUE TITLE
Source maps are not working for shopify integration on branch next

### ISSUE THREAD

**Issue by bitforcesrl** [vuestorefront/vue-storefront#4761]
## Current behavior
no source map available for shopify connectors

## Expected behavior
source maps available

## Steps to reproduce the issue
yarn build:sp & yarn dev:sp

## Version of Vue Storefront
Vue Storefront Next

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
