### ISSUE TITLE
Phone number validation on shipping and payment form

### ISSUE THREAD

**Issue by AshishSuhane** [vuestorefront/vue-storefront#4767]
## Current behavior

No validation on phone number in shipping and payment form, user can number as well as alphabets with no limit

## Expected behavior

Should have validation where user can enter only number with limit (max: 10-14 digit)

## Steps to reproduce the issue

1. Select any product, and navigate to product detail page.
2. Add it in a cart and checkout it from cart.
3. Enter personal detail and continue.
4. Fill shipping details and enter phone number ex: ddgafdgahfdgha236153617361.

Expected: should have validation on phone number

## Version of Vue Storefront

- [] Vue Storefront 
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser:  Chrome
- OS:  Mac Catalina version 10.15.6
- Node:  10.16.0
- Code Version:  1.12.2

## Additional information

![Screenshot 2020-08-22 at 6 56 38 PM](https://user-images.githubusercontent.com/34393306/90957467-5849e600-e4ab-11ea-8497-3bc25d92b19b.png)

![Screenshot 2020-08-22 at 6 57 01 PM](https://user-images.githubusercontent.com/34393306/90957472-5f70f400-e4ab-11ea-82b3-aec5148b5203.png)

**Comment by Fifciu** [comment]
As I have to publish VSF-Capi fix asap - I had to remove this validator from VSF-Capi because it bases on changes from hotfix/1.12.3 while current capi uses `master` branch
