### ISSUE TITLE
413：request entity too large

### ISSUE THREAD

**Issue by ldc321** [vuestorefront/vue-storefront#4782]
## Current behavior

When I have about 20 items in my cart, I get an error when I go to the billing department！
Request URL: https://demo.storefrontcloud.io/api/order
Request Method: POST
Status Code: 413 

## Expected behavior

I have about 20 items in my cart,  checkout 

## Version of Vue Storefront

* [ ] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by talalus** [comment]
re-opening this, need to remove 'attributes_metadata' from placing order payload because it include all the attributes details which make the payload so big when the website has lot of attributes and there are multiple products in the cart

**Comment by artemskyi** [comment]
@talalus as a workaround solution for this issue would be to set the following setting in **local.json**:
`"bodyLimit": "1mb"`
**1mb** is an example value so the exact limit size depends on your particular project.
