### ISSUE TITLE
Load available regions and use select HTML tag

### ISSUE THREAD

**Issue by Fifciu** [vuestorefront/vue-storefront#4784]
## What is the motivation for adding / enhancing this feature?

Currently, State/Region is text field. In my opinion, it should be `select` with loaded regions from the backend.

## What are the acceptance criteria 

* [ ] Fetching regions from the backend
* [ ] Show them in select on both shipping & billing step
* [ ] Make sure it is being validated properly
* [ ] Make sure it is being sent properly to backend with the order

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

**Comment by hcmlopes** [comment]
@Fifciu I made a comment related to this in https://github.com/vuestorefront/vue-storefront/pull/4770 

My question is. Should we use the countries endpoint in magento directly or should this be something that gets entered into the Elastic index?

Also have you started any work and do you have any further guidance on this, it is a feature I need and I was going to tackle it starting today as a separate module called `vsf-countries-and-regions`

**Comment by Fifciu** [comment]
I've implemented it in many shops in the previous job. However, nowadays I wonder if it would not be better to hardcode list of available ones.

Putting it in ES might be a good idea. However, I've fetched it directly from Magento2 and cached response for the very long time
