### ISSUE TITLE
GraphQL query for product uses deprecated field to get product attributes

### ISSUE THREAD

**Issue by timbenniks** [vuestorefront/vue-storefront#4790]
## Current behavior
When doing a query for a product the attributes that come back are wrapped in an object called `attributeList`. When commercetools has attributes on the product that are not of the `StringAttribute` but an ENUM for example, these attributes are not returned.

## Expected behavior
All type of attributes are expected to return in the `attributeList` object.

## Steps to reproduce the issue
Check the Query and see that not all attributes return.

## How to fix
Use the new `attributesRaw` property in the GrapQL query. `attributeList` is deprecated.

Change the GraphQL fragmant to this and it starts to work.

```
fragment Attributes on ProductVariant {
  attributeList: attributesRaw {
    name
    value
  }
}
```

Beware, the returned values are not typed. Lot's of critical code in VSF next will need to be changed.

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Environment details
* Code Version:  latest `next` branch at the time of writing.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
