### ISSUE TITLE
Product with custom option quantity increase

### ISSUE THREAD

**Issue by dsengsqli** [vuestorefront/vue-storefront#4819]
## Current behavior
When I add the same product but with different custom options the quantity are increasing automatically.

One simple product added with custom options
![image](https://user-images.githubusercontent.com/70597258/91884448-568bd980-ec86-11ea-8f37-8460216236d4.png)

Second simple product added with custom options (first one has increased and should not)
![image](https://user-images.githubusercontent.com/70597258/91884646-b6828000-ec86-11ea-927b-d27fd4d4ec12.png)

On page refresh the first one quantity increase again and each time I refresh
![image](https://user-images.githubusercontent.com/70597258/91884684-cac67d00-ec86-11ea-8f4a-ddb75023b9b8.png)

## Expected behavior
The product quantity should not increase why I add the same product with different custom options and on refresh.

## Steps to reproduce the issue
* Create Magento 2 shop
* Create a product with custom options
* Go on VSF page and select multiple custom options and 1 qty
* Add the product to the cart
* Change the selected custom options
* Add the product to the cart (first product quantity has increased to 2)
* Refresh the page (first product quantity has increased to 3)

## Version of Vue Storefront
* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: Version 83.0.4103.116 (Official build) (64 bits)
* OS: Ubuntu 21
* Node: v10.21.0
* Code Version: v1.12.2

## Additional information
Similar to this issue on a side note 
"In addition I just realized that if you refresh the page the quantities of products with custom options are doubled while the quantities of the other products are not affected."
https://github.com/DivanteLtd/vue-storefront/issues/3976

**Comment by luiscmmarques** [comment]
Do you've some news on the progresss of this ticket ? Thanks in advance
