### ISSUE TITLE
Function "isOptionAvailable()" should have option "fullMatch"

### ISSUE THREAD

**Issue by simonmaass** [vuestorefront/vue-storefront#4831]
## Current behavior

the function core\modules\catalog\helpers\variant\isOptionAvailable.ts uses the function findConfigurableVariant()

This function will ALWAYS return a variant... not really the expected behavior

## Expected behavior

The function findConfigurableVariant() should also have an option "fullMatch" true/false... with default "false" to not have a breaking change...

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:  1.12.3

**Comment by gibkigonzo** [comment]
@simonmaass can you please make a pr?

**Comment by simonmaass** [comment]
@gibkigonzo done
