### ISSUE TITLE
How does the <raw-content> tag works for generating the XML output?

### ISSUE THREAD

**Issue by pratik149** [vuestorefront/vue-storefront#4836]
I'm referring this part of the documentation..
https://docs.vuestorefront.io/guide/core-themes/layouts.html#generating-the-xml-output

As mentioned in the doc section of "Generating the XML output", I'm not able to find the
below example file in the repo.
`You can find some examples in the "src/extensions/raw-output-example" example.`

And also not able to visit this example url, after setting everything up in my local system.
`Example URL: http://localhost:3000/raw-output-example.xml`

I'm essentially trying to understand how the `<raw-content>` tag works in vue-storefront
app, and how does it render the XML content, as it is, without any html.

`<raw-content>` tag does not seem to be a part of Vuejs, so I'm curious to know its working,
because I want to achieve the same in one of my vanilla vuejs project.

It will be really appreciated if someone throws more light on this topic, beyond what is
mentioned in the docs. Thanks!

**Comment by vladislav-sevostyanov** [comment]
I think you need to replace `<raw-content>` tag with your `xml` root tag.

**Comment by vladislav-sevostyanov** [comment]
App.vue =>
```
<template>
  <router-view />
</template>
```

layouts/Empty.vue =>

```
<template>
  <router-view />
</template>
```


The xml component =>
```
<template>
  <raw-content>
    This page is using empty layout set in routes + no html template
  </raw-content>
</template>

<script>
export default {
  name: 'MyRawXmlComponent',
  components: {},
  data() {
    return {
      exampleData: 'Data from base component',
    };
  },
  asyncData({ store, route, context }) {
    context.server.response.setHeader('Content-Type', 'text/xml');
    context.output.template = '';
    return new Promise((resolve, reject) => {
      resolve();
    });
  },
};
</script>
```

Routes =>

```
...
{
  name: 'my-xml',
  path: '/myxml.xml',
  component: MyRawXmlComponent,
  meta: { layout: 'empty' },
},
...
```
http://localhost:3000/myxml.xml

It works for me. But i don't know how to define it. For example:
```
<?xml version="1.0" encoding="UTF-8"?>
  ...other document content
```
or
```
<?xml version="1.0" encoding="windows-1251" standalone="no"?>
  ...other document content
```
Because vue templates can contain only one root element.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
