### ISSUE TITLE
Broken Windows build of "commercetools/api-client"

### ISSUE THREAD

**Issue by filipsobol** [vuestorefront/vue-storefront#4843]
## Current behavior
Running `yarn dev:ct` on device running Windows results in the page showing following error:

```
Cannot read property 'uri' of undefined
(src/helpers/createCommerceToolsLink/index.ts:11)
```

**This issue doesn't occur on Linux / Mac devices.**

## Additional information
Output files of package `@vue-storefront/commercetools-api` (`packages/commercetools/api-client/lib/index.(cjs/es).js`) instantiate `apiClientFactory` and `apolloClient` twice (variables `apolloClient` / `apolloClient$1` and `_a` / `_a$1`. Ones without `$1` at the end are actually populated with config, but the others (empty) are exported to other packages.
This is likely caused by https://github.com/rollup/plugins/issues/526

Build from Linux device doesn't have this issue.

## Expected behavior
Windows build should work.

## Steps to reproduce the issue
1. Run `yarn build:core`
1. Run `yarn build:ct:tools`
1. Run `yarn dev:ct`
1. Open page in the browser

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
* Browser: Tested on latest Chrome, Edge and Firefox
* OS: Windows 10
* Node: Tested on 10 and 14
* Code Version: @vue-storefront/commercetools-api@0.0.10

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-265) by [Unito](https://www.unito.io/learn-more)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
