### ISSUE TITLE
Middleware layer for API communication

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#4854]
Due to security reasons and others, such as bundle size, backend synchronization etc. we would like to introduce proxy API as a sort of bridge between front-end and commerce API. That proxy will give us flexibility for the upcoming integrations, and first of all, it can cover the following features:

* react on any changes - every time you do some action on the UI that triggers some backend action, you will be able to react on it (eg. add to cart, add coupon etc.)
* extend API - you will be able to add other endpoints to the API
* transformation - you will be able to do some response transformation if you need it in your project (but we'll keep data format as it is in our integrations)
* API will be a part of nuxt module that already exists in the integrations

### Developer API
As a developer, once you have installed integration, you will be able to extend the API in the following way:
Inside of the` buildModules` section in your nuxt.config.js you need to configure the integration module:

```
  buildModules: [
    ['@vue-storefront/comercetools/nuxt', {
      extendApi(app) {
         app.get('/new-api-endpoiint', (req, res) => {
            ....
         })
      }
    }]
  ],
```

The extendApi takes as an argument the express.js `app`

* you can do whatever you want with the API.

### Integrator API
As an integrator, you need to provide the middleware that covers the needed API. In order to do this, we'll provide a core mechanism and its usage will look mostly like this:

```
import { createApiMiddleware }  from '@vue-storefront/core'

const apiMIddleware = createApiMiddleware((app) => {

  app.get('/cart', () => {
    ...
  })

  return app
})


export default apiMIddleware
```

### Migradion guide & next steps
* only API/proxy created - We are starting with introducing this middleware / API only as a proxy, so it will be transparent from the project perspective, we will only change the endpoint from the current one to the endpoint exposed from our middleware
* (CT) move GQL to the backend - Once we have API middleware implemented, in the case of commercetools we'll move all of GQL communication to the backend - it should reduce the bundle size by 10%; commercetools API-client will do simple rest/HTTP interaction, with given variables and probably the name of query that you want to call
* Other integration - we'll try to do the same thing with other integrations, but there is no graphql API, out middleware will work only as a proxy
* events and reaction - once integrations are ready, we can introduce events system that will give the possibility to react on each API call from projects (eg. you have a project based on comemrcetools and you want to send the information about an added product to the cart somewhere - that's the API for it)

**Comment by pkarw** [comment]
This is a great idea. I'm buying it 100%

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
