### ISSUE TITLE
Create composable for ui-state.ts

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#4876]
As we have created composable for UI helpers (ref: https://github.com/DivanteLtd/vue-storefront/pull/4853), would be nice to create a composable that handles the UI state (`useUiState`) that currently is as a separated file `ui-state.ts`

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-280) by [Unito](https://www.unito.io/learn-more)

**Comment by filrak** [comment]
Proposed API 
```ts
const {
  isCartSidebarOpen,
  isWishlistSidebarOpen,
  isLoginModalOpen,
  isCategoryGridView,
  isFilterSidebarOpen,
  toggleCartSidebar,
  toggleWishlistSidebar,
  toggleLoginModal,
  toggleCategoryGridView,
  toggleFilterSidebar
} = useUiState()
```
It should be in `theme/composables/useUiState.ts` of nuxt theme module
