### ISSUE TITLE
Deletes attributes that may be needed in other components

### ISSUE THREAD

**Issue by simonmaass** [vuestorefront/vue-storefront#4878]
## Current behavior

when setting attribute.loadByAttributeMetadata: true in the config file the vuex store is loaded with attribute data according to the product that is currently loaded on product page or category page...

when trying to display attributes in the cart for example (e.g. delivery time or something)... these attribute variants are cleared (or overriden) each time you click on a new product or other category page

## Expected behavior

if attribute data is loaded once in the vuex store via the attributemeta data... this data stays in the vuex store and doesnt get wipped again... should be merged!

this merge should also be a deep merge! so attribute options in the value array should also get merged!

## Steps to reproduce the issue

display an attribute in the microcart and load a product page of a product that doesnt share the same attribute value... then in cart this attribute value gets wiped out...

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:  1.12.2

**Comment by lukaszjedrasik** [comment]
Waiting for video with steps to reproduce from @simonmaass
