### ISSUE TITLE
Update GraphQL types

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#4900]
We need to update GraphQL types for commercetoos and add some sort of automation to do this in the future (yarn command)

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-294) by [Unito](https://www.unito.io/learn-more)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
