### ISSUE TITLE
Docs for Varnish Module

### ISSUE THREAD

**Issue by pablogiralt** [vuestorefront/vue-storefront#4902]
Write documentation for [vsf-cache-varnish module](https://github.com/new-fantastic/vsf-cache-varnish) in official VSF repo

There is a mention to using Varnish for SSR output cache in official docs [here](https://docs.vuestorefront.io/guide/installation/production-setup.html#varnish-cache-for-vsf), but nothing more about how to use it

[Docs in module](https://github.com/new-fantastic/vsf-cache-varnish) are good, however, for such a complex feature more detailed docs would be super helpful, especially for devs which have not used Varnish before.

**Comment by gibkigonzo** [comment]
@pablogiralt There is also link to repo where is description how to setup this module https://github.com/new-fantastic/vsf-cache-varnish
