### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by pablogiralt** [vuestorefront/vue-storefront#4903]
## What is the motivation for adding / enhancing this feature?

In causes where downtime on a VSF site is needed for maintenance tasks, there is currently no way to block the access to the front-end for users.
It has happened to me that when doing necessary maintenance in magento backend and setting it to maintenance mode, the front-end obviously is still accesible by users but it does not work (cart, checkout, etc...).  This is a bad experience for users accessing the site at that time.

## What are the acceptance criteria 

* [ ] Add a setting to config to enable/disable maintenance mode
* [ ] Users are redirected to a maintenance page when maintenance mode is enabled.
* [ ] Maintenance mode should work on any app route and if routes are loaded client-side or server-side

## Version of Vue Storefront

* [x] Vue Storefront
* [x] Vue Storefront Next
(could be useful for both)

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

I could handle layout and styling for the maintenance page, but not the logic

## Additional information

How to handle this in Nuxt: https://medium.com/code4mk-org/nuxt-maintenance-mode-48e158c429e2

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
