### ISSUE TITLE
configurable_item_options with custom_options is empty and vice versa

### ISSUE THREAD

**Issue by devmade** [vuestorefront/vue-storefront#4974]
### Current behavior
When there are configurable options like color selector etc with custom options (input elements), the request made is not sending all of the options. If configurable options were last to be selected, they are sent otherwise custom inputs.

![Screenshot 2020-10-06 221519](https://user-images.githubusercontent.com/30465670/95236910-27d4c600-0825-11eb-9455-87b508db57c6.png)
![Screenshot 2020-10-06 221453](https://user-images.githubusercontent.com/30465670/95236914-299e8980-0825-11eb-80f6-a4ce4a8e6675.png)

### Expected behavior
The getter product/getCurrentProduct should be updated with all of the configuration options.
![Screenshot 2020-10-06 222308 (2)](https://user-images.githubusercontent.com/30465670/95237161-7d10d780-0825-11eb-899f-bde1ab82e981.png)

### Steps to reproduce the issue
Use custom inputs with configurable product. 
I'm using Magento 2.3 store.

For now I might be able to force modify some of the methods.

**Comment by antoniogurei** [comment]
@devmade haven’t you fixed this?

**Comment by devmade** [comment]
> @devmade haven’t you fixed this?

Yes I have, but it's more of a hack. Here's how I did it

in `/core/modules/catalog/store/product/getters.ts`
I updated the getCurrentProduct code. Here's the updated one

```javascript
  getCurrentProduct: state => {
    const data = state.current

    const getOptionId = (label) => data.extension_attributes.configurable_product_options.find((item) => item.label.toLowerCase() === label.toLowerCase()).attribute_id

    const getValueId = (label) => state.current_configuration[label.toLowerCase()].id

    data.product_option.extension_attributes.configurable_item_options = ["Color", "Size"].map((label) => {
      return {
        option_id: getOptionId(label),
        option_value: getValueId(label)
      }
    })

    data.product_option.extension_attributes.custom_options = state.current_custom_options

    return data
  }
```

I studied vuex store values and this is how I was able to make it work.
