### ISSUE TITLE
uuid/v4 is deprecated as of uuid@7.x

### ISSUE THREAD

**Issue by pschaub** [vuestorefront/vue-storefront#4975]
I got this warning during `yarn build`:
> (node:19940) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.

https://github.com/DivanteLtd/vue-storefront/blob/594618a46e75be39dc03067537f41657fee34044/core/build/webpack.server.config.ts#L10

**Comment by gibkigonzo** [comment]
@pschaub thanks, can you please prepare pr? :)

**Comment by pschaub** [comment]
@gibkigonzo feel free to do it :) I have currently not enough time for it.
