### ISSUE TITLE
Support state on checkout in commercetools

### ISSUE THREAD

**Issue by sudo-at-night** [vuestorefront/vue-storefront#4992]
## What is the motivation for adding / enhancing this feature?
It should be supported, without it shipping methods cannot be fetched when `state` is set on a specific tax category.

## What are the acceptance criteria 
* [ ] Support `state` during checkout process

## Version of Vue Storefront
* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-328) by [Unito](https://www.unito.io/learn-more)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
