### ISSUE TITLE
Remove vue-lazyload from core

### ISSUE THREAD

**Issue by gibkigonzo** [vuestorefront/vue-storefront#4998]
## What is the motivation for adding / enhancing this feature?

We should not load vue-lazyload in core file, because:

* we can't change vue-lazyload options (for example I can't add path for loading or error state images)
* we don't have alternative (for example in capybara we use sfui which uses different lib. In result we load two libs)

## What are the acceptance criteria 

* [ ] - removed vue-lazyload from core
* [ ] - added vue-lazyload in default theme main file (from https://github.com/DivanteLtd/vue-storefront/blob/master/core/app.ts#L69 to https://github.com/DivanteLtd/vsf-default/blob/master/index.js#L19)

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

**Comment by gibkigonzo** [comment]
offtop: Same is with VueObserveVisibility and Vuelidate. Those are great libs but they are related with theme/components not with core logic. I can't use vee-validate instead of vuelidate.

**Comment by jahvi** [comment]
Just had a go at this one, I only removed vue-lazyload but I don't know if you want to remove the other libraries you mention as well in one go.

**Comment by gibkigonzo** [comment]
This needs to be merged to develop and released with version 1.13. Also we need to add info in upgrade notes for 1.13, because current projects may depend on this lib.

**Comment by gibkigonzo** [comment]
https://github.com/DivanteLtd/vue-storefront/issues/4998#issuecomment-712955618 I'm not sure if we can remove Vuelidate at all. This needs to be checked. We still may have core mixins where Vuelidate is used.

**Comment by lukaszjedrasik** [comment]
@Fifciu 

I have seen that `Vuelidate` is using inside `core/modules/newsletter/mixins` so I decided to not remove it from the core.

https://github.com/vuestorefront/vue-storefront/pull/5544
https://github.com/vuestorefront/vsf-default/pull/61
