### ISSUE TITLE
Support arrays for middlewares

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#5030]
## What is the motivation for adding / enhancing this feature?
Better DX, sometimes we want to have multiple middlewares and if for some reason we don't want to configure them within one, the array notation can be simpler.

## What are the acceptance criteria 
support the following (array) notation

```
['@vue-storefront/{PLATFORM}/nuxt', {
  apiMiddleware: {
     extend: [
       middleware1,
       middleware2
      ....
     ]
    }
  }
}]
```

* [ ] ...

## Version of Vue Storefront

* [ ] Vue Storefront
* [x ] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-337) by [Unito](https://www.unito.io/learn-more)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
