### ISSUE TITLE
Link bottom navigation buttons

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5053]
Link bottom nav buttons 
![image](https://user-images.githubusercontent.com/15185752/96785277-dd3f7600-13ee-11eb-924a-920871529af0.png)

Home should link to home
Wishlist and cart should open wl/cart
Account should link to my account or open login modal if user is not logged in

"Menu" can remain like it is now as we don't have a component to open with this yet

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-341) by [Unito](https://www.unito.io/learn-more)

**Comment by hansfelix** [comment]
I can help to solve this issue, @filrak  please assig me.
