### ISSUE TITLE
Bug report - config.entities.optimize not being respected in catalog-next module

### ISSUE THREAD

**Issue by hcmlopes** [vuestorefront/vue-storefront#5070]
## Current behavior
There are a couple of actions in the catalog-next module that are not respecting the `config.entities.optimize` setting.

## Expected behavior
When changing `default.json` or `local.json` property to `config.entities.optimize: false` it should then allow ES query to bring in all category attributes without any exclusions

## Version of Vue Storefront

- [x] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilization fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 87.0.4280.88
- OS: Windows 10 (Build 19041.329)
- Node: v10.23.0
- Code Version: tag 1.12.2

## Additional information
https://github.com/DivanteLtd/vue-storefront/blob/2ddac268863a6901d68c5c05dbbc0be7e7d35fb1/core/modules/catalog-next/store/category/actions.ts#L39

https://github.com/DivanteLtd/vue-storefront/blob/2ddac268863a6901d68c5c05dbbc0be7e7d35fb1/core/modules/catalog-next/store/category/actions.ts#L75

I would like to work on this issue.

**Comment by Fifciu** [comment]
Have you worked on that @hcmlopes ?

**Comment by hcmlopes** [comment]
> Have you worked on that @hcmlopes ?

I haven't but I can send a PR sometime today or tomorrow
