### ISSUE TITLE
[Next][CT] shipping method is still defaulting to first one

### ISSUE THREAD

**Issue by Qrzy** [vuestorefront/vue-storefront#5073]
## Current behavior

After #5028 the chosen shipping method is defaulted, but in memory only, to the first loaded one:
https://github.com/DivanteLtd/vue-storefront/blob/1bf6905b56160abf11134490f6042dd30e72bc9f/packages/commercetools/composables/src/useCheckout/createLoadShippingMethods.ts#L16
This ends up with showing on the UI that first shipping method is chosen which has no actual effect in cart on ct side - it's still null there.

## Expected behavior
No shipping method should be chosen by default.

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-346) by [Unito](https://www.unito.io/learn-more)

**Comment by EugeneHlushko** [comment]
But only in memory, not sent to the API right?
