### ISSUE TITLE
Using hardcoded values while creating the product gallery

### ISSUE THREAD

**Issue by ymaheshwari1** [vuestorefront/vue-storefront#5090]
## Current behavior
We are using hardcoded values for width/height in the productGallery.

## Expected behavior
We should use the config file to define the values for width and height.

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

https://github.com/DivanteLtd/vue-storefront/blob/master/core/modules/catalog/helpers/index.ts#L109

**Comment by lukaszjedrasik** [comment]
Closed, because this PR: https://github.com/vuestorefront/vue-storefront/pull/5088 fixed the issue.
