### ISSUE TITLE
Update Vue Router to the newest version

### ISSUE THREAD

**Issue by Fifciu** [vuestorefront/vue-storefront#5122]
## What is the motivation for adding / enhancing this feature?

Currently, we have hardcoded 3.1.6 version to make sure everything works properly. Unfortunately, newer versions cause issues. 

## What are the acceptance criteria 

* [ ] Update VueRouter to the newest version (today at 3rd Nov 2020 it is 3.4.8)
* [ ] Make sure everything works properly with new version, dynamic URLs, SSR, no DOM Exceptions. Currently, we know there is a bug with refreshing on category/product view with the newest version

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

**Comment by simonmaass** [comment]
just ran into issues with this - would be great if this would get updated soon!
