### ISSUE TITLE
Checkout.com : payments other than with a card

### ISSUE THREAD

**Issue by heaenwie** [vuestorefront/vue-storefront#5130]
## What is the motivation for adding / enhancing this feature?
We cooperate on the project. Client has other scope of the checkout on the designs that was provided in the integration. 

## What are the acceptance criteria 
To have the checkout.com integration as per designed options (Paypal, Venmo)

* [ ] ...

## Version of Vue Storefront

* [ ] Vue Storefront
* [x ] Vue Storefront Next - enterprise

## Can you complete this feature request by yourself?
* [ ] YES
* [ x] NO

## Additional information

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-366) by [Unito](https://www.unito.io/learn-more)

**Comment by Fifciu** [comment]
Hello,
The newest version of checkout-com module for Next supports PayPal. I am currently working on support for Klarna, so version with Klarna support will be also soon released.

https://www.npmjs.com/package/@vue-storefront/checkout-com

So as I understand - the only new thing you need is support for Venmo. Please update issue title if so
