### ISSUE TITLE
Cant run Vue-strefront from server

### ISSUE THREAD

**Issue by maulik-neosoft** [vuestorefront/vue-storefront#5140]
I am running the latest version of vue-storefront. I have checked the documentation and found no answer. 

# Is there something you don't understand? What is it? Describe it.
I'm using vue-storefront front-end and reverse proxy it from Node.js
But its showing 

```
{{{ meta.inject().title.text() }}} {{{ meta.inject().meta.text() }}} {{{ meta.inject().link.text() }}} {{{ meta.inject().script.text() }}} {{{ renderResourceHints() }}} {{{ renderStyles() }}} {{{ output.appendHead() }}} {{{ renderState() }}} {{{ renderScripts() }}}
```

# Can't find what you're looking for?
I need to know how to perly setup the vue-storefront on CentOS7
with Nginx.

**Comment by Fifciu** [comment]
Are you sure you properly enabled Node's app and configured everything? Provide some details about what did you do and in what order
