### ISSUE TITLE
Range filter in faceting

### ISSUE THREAD

**Issue by heaenwie** [vuestorefront/vue-storefront#5148]
## What is the motivation for adding / enhancing this feature?
One of our clients would like to have options of filters as per design of the page provided (with the range of prices and with the graph that presents the ranges) 
Also, the client would like to have visible in filters only the  BRANDS that are currently visible on the products page. 

## What are the acceptance criteria 
* I can filter the products by price range
* In filters, I can only see the BRANDS that are visible on the product page

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [ ] YES
* [x] NO

## Additional information

┆Issue is synchronized with this [Jira Story](https://vsf.atlassian.net/browse/NEXT-371) by [Unito](https://www.unito.io/learn-more)

**Comment by andrzejewsky** [comment]
ref: https://github.com/DivanteLtd/vue-storefront/issues/5151

**Comment by Fifciu** [comment]
For Price Range slider: https://github.com/Fifciu/vsf-price-slider

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
