### ISSUE TITLE
Custom Sorting on Category Page is not applied

### ISSUE THREAD

**Issue by domideimel** [vuestorefront/vue-storefront#5155]
## Current behavior

If the default behaviour of the categories sorting is changed in the Magento backend this is not reflected on the VSF frontend.
Vue Storefront:
![image](https://user-images.githubusercontent.com/32941053/98550922-fa07f480-229c-11eb-966a-277bda923fb1.png)

Magento:
![image](https://user-images.githubusercontent.com/32941053/98550973-0db35b00-229d-11eb-916e-e67ee56405ea.png)

## Expected behavior

The selected values from the Backend correspond 1:1 to the frontend.

## Steps to reproduce the issue

Change the default sorting for any given Category and take a look at the frontend after a hardreload.

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by pschaub** [comment]
Are you using [mage2vuestorefront](https://github.com/DivanteLtd/mage2vuestorefront) or the [magento2-vsbridge-indexer](https://github.com/DivanteLtd/magento2-vsbridge-indexer)?

**Comment by domideimel** [comment]
> Are you using [mage2vuestorefront](https://github.com/DivanteLtd/mage2vuestorefront) or the [magento2-vsbridge-indexer](https://github.com/DivanteLtd/magento2-vsbridge-indexer)?

We are using the indexer.
