### ISSUE TITLE
wait until updateItem finished in stockSync function

### ISSUE THREAD

**Issue by pschaub** [vuestorefront/vue-storefront#5172]
I have seen that inside `stockSync` of `core/modules/cart/store/actions/synchronizeActions.ts` there are 2 dispatch calls without an `await`. Please check if the missing `await` could result into weird race-condition behaviour.

Should we wait until the dispatch call finished?

1. https://github.com/OetkerDigital/belvini-storefront/blob/a5e9e9ee9c2c43444790592ae2475f436f859d01/src/pwa/core/modules/cart/store/actions/synchronizeActions.ts#L95
1. https://github.com/OetkerDigital/belvini-storefront/blob/a5e9e9ee9c2c43444790592ae2475f436f859d01/src/pwa/core/modules/cart/store/actions/synchronizeActions.ts#L102

Current:

```
dispatch('updateItem', { ... })
```

Suggestion:

```
await dispatch('updateItem', { ... })
```

**Comment by Fifciu** [comment]
Rather not but please make sure @lukaszjedrasik
