### ISSUE TITLE
Sorting doesn't work

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5191]
## Current behavior

1. Change 
![image](https://user-images.githubusercontent.com/15185752/99234198-81e98380-27f4-11eb-8212-00d98d547782.png)
1. Nothing changes
## Expected behavior

Changing sorting should sort the items

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
