### ISSUE TITLE
Default value of select is not disapeearing after selection

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5233]
![image](https://user-images.githubusercontent.com/15185752/99875365-4af9e000-2bef-11eb-84e3-58dc43d0f4d4.png)

1.  Enter `/p/38143c0c-c9b0-448c-93cd-60eb90d8da57/aspesi-shirt-h805-white`
1. Change size
1. See the error

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/NEXT-27) by [Unito](https://www.unito.io/learn-more)

**Comment by RakowskiPrzemyslaw** [comment]
I verified this, this error is no longer occuring, please check @filrak
