### ISSUE TITLE
Add Lighthouse CI to the GitHub repository

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5235]
## What is the motivation for adding / enhancing this feature?

Add Lighthouse CI for

* Home Page
* Product Page

on every PR for `next`  and `develop` branch

https://github.com/GoogleChrome/lighthouse-ci

**Comment by haikyuu** [comment]
I ran lighthouse on the capybara official theme, and this is the result
![image](https://user-images.githubusercontent.com/8558836/105151787-acaecb80-5b06-11eb-8d47-dd8868b6b33e.png)

That's a bit discouraging for an e-commerce tool.

Is the performance hit inherent to vue and nuxt.js or can we do better?

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
