### ISSUE TITLE
Price sorting doesn't work at the end on Category page

### ISSUE THREAD

**Issue by bohdan-karapet** [vuestorefront/vue-storefront#5247]
## Current behavior
Products at the end on Category page are not sorted by price.

## Expected behavior
All products should be sorted properly.

## Steps to reproduce the issue
1) go to https://demo.vuestorefront.io/default-category-2
2) pick sorting "Price: Low to high"
3) scroll to the end of products list (after last products lazy load)

![](https://user-images.githubusercontent.com/67786973/100218297-3c783500-2f1d-11eb-8e41-82416e295798.png)

## Version of Vue Storefront

* [x] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by lsliwaradioluz** [comment]
When you choose to sort the category products by price, the "finalPrice" property of each product object is taken into consideration. The "Didi Sport Watch" product object simply has no "finalPrice" property and is therefore fetched at the end of the list. So I believe the bug is not in the code itself but in the data fetched from the api. 

![didi](https://user-images.githubusercontent.com/39009379/100233226-bb736a80-2f29-11eb-996d-7e22424ebbd6.jpg)

**Comment by Fifciu** [comment]
Looks like it is already solved on the `develop`: https://test.storefrontcloud.io/default-category-2?sort=final_price
Could you check it just for sure @bohdan-karapet ?
