### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#5250]
## What is the motivation for adding / enhancing this feature?
After changes related to the context API, we have dropped the test coverage significantly. We need to go back on track and increase coverage again.

## What are the acceptance criteria 

* [ ] Unit tests until 90%+

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/NEXT-25) by [Unito](https://www.unito.io/learn-more)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
