### ISSUE TITLE
Last footer category is covered by the bottom nav

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5253]
![image](https://user-images.githubusercontent.com/15185752/100342818-d3f18c80-2fde-11eb-858c-fc09b765ead2.png)

**Comment by jakubmakielkowski** [comment]
I could try on this if @justyna-13 hasn't started working with this issue.
Is this issue strictly related with vsf-capybara repository? We could add extra padding on mobile in "vsf-capybara/components/organisms/o-footer.vue", but this implies that footer will be always the last section on page. In my opinion some users could use pages without footer (eg. checkout).
We could also add this extra padding in "vsf-capybara/layouts/Default.vue" but this component lacks of <style> section.
Maybe one of my mentioned ideas is suitable? @filrak
