### ISSUE TITLE
Create a scripts for CHANGELOG generation

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5256]
## What is the motivation for adding / enhancing this feature?

We NEED a script allowing users to easily add new entities into changelog withotu worrying that this record will become outdated (a commonc ase here si that someone is putting a recond under version X, version X is released and the PR needs adjustment)

## How this should work
1. In every project there is a directory `/changelog` (configurable through a cli arg `in`) where you put a file with a PR number with a following format

```js
export default {
  description: "Changes description"
  author: "GH handle of the author"
  isBreaking: "does it introduce a breaking changes for the public api" (true/false)
  breakingChanges: [{
    module: "affected part of the app"
    before: "how it was"
    after: "how it is"
    comment: "quick migration guide"
 } ]
}
```

1. When we release the version we're creating records on top of `CHANGELOG.md` (default but can be configured through a cli arg 'v`)  from these files under a released version number  (can be a cli argument `out`) like [here](https://docs-next.vuestorefront.io/contributing/changelog.html) in the following format

```md
**[BREAKING]** ${description} [#{PRNUMBER}](linktoPR) - [#{author}](linktoauthorsprofile)

table of breaking changes like in sfui
```

1. after the process `/changelog` dir should be empty

Example call with default `CHANGELOG.md`

```
node ./scripts/geenrateChangelog --v 1.13
```

First prepare the script to work in VSF core

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/NEXT-23) by [Unito](https://www.unito.io/learn-more)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
