### ISSUE TITLE
Add MegaMenu to theme

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5267]
Add MegaMenu to the Header in the agnostic Nuxt theme. Use `SfHeaderNavigation` from Storefront UI https://storybook.storefrontui.io/?path=/story/organisms-header--with-sfheadernavigation.

Then use `useCategory` to

1. Fetch top-level root categories
![image](https://user-images.githubusercontent.com/15185752/100710860-adea3480-33b0-11eb-897b-0fd1f71a9581.png)
1. Fetch their subcategories
![image](https://user-images.githubusercontent.com/15185752/100710910-be9aaa80-33b0-11eb-814a-666041b942c6.png)

**Comment by skirianov** [comment]
Issue is closed. Reason: Too Old (>6 months)

---

Sergii Kirianov
Developer Advocate
Vue Storefront
