### ISSUE TITLE
Pass correct server items in 'servercart-after-diff' event

### ISSUE THREAD

**Issue by bohdan-karapet** [vuestorefront/vue-storefront#5270]
## Current behavior
Now "serverItems" are always undefined in "servercart-after-diff" event.
vue-storefront/core/modules/cart/store/actions/mergeActions.ts:210

## Expected behavior
Should pass correct "serverItems" from "hookResult".

## Steps to reproduce the issue
Visible only while debugging or subscribing to 'servercart-after-diff' event.

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

**Comment by Fifciu** [comment]
Done
