### ISSUE TITLE
Changing variant on PLP doesn't work

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5281]
## Current behavior

1. enter https://lovecrafts-demo.storefrontcloud.io/p/38143c0c-c9b0-448c-93cd-60eb90d8da57/aspesi-shirt-h805-white
1. change the size
1. nothing happens

## Expected behavior

1. enter https://lovecrafts-demo.storefrontcloud.io/p/38143c0c-c9b0-448c-93cd-60eb90d8da57/aspesi-shirt-h805-white
1. change the size
1. URL is changing and the product is reloading

**Comment by RakowskiPrzemyslaw** [comment]
this bug is no longer occurring, closing
