### ISSUE TITLE
No price sign

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5282]
- https://kazupon.github.io/vue-i18n/guide/number.html format prices with vue i18n
- remove `formatPrice` UI helper

**Comment by andrzejewsky** [comment]
Let's use standard price formatting from nuxt18n in our default theme.

Acceptable criteria:
- remove `formatPrice` from useUiHelpers
- use price formating function from nuxt-i18n
- remove getFormattedPrice from all of the getters
