### ISSUE TITLE
Configure repositories and dev environment

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#5287]
## What are the acceptance criteria 
* [ ] this repo should contain only core
* [ ] each integration has a dedicated monorepo, each package inside should have the same version (monorepo versioning)
* [ ] configure CI/CD for each one
* [ ] Create a dev environment for each integration (we should start developing on the boilerplate, one command should set up for me an environment for the development process) 

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

┆Issue is synchronized with this [Jira Zadanie](https://vsf.atlassian.net/browse/NEXT-18) by [Unito](https://www.unito.io/learn-more)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
