### ISSUE TITLE
use transparent image in README

### ISSUE THREAD

**Issue by pschaub** [vuestorefront/vue-storefront#5305]
GitHub now supports dark mode. Please change the image in the README to a transparent image.

![image](https://user-images.githubusercontent.com/11846736/101528448-9f42e500-398f-11eb-8552-a6e96f6d3975.png)

**Comment by Fifciu** [comment]
Please use [this image](https://uploads-ssl.webflow.com/5e7cf661c23ac9df156d9c3d/5f804e14e571f5c30d9ffff8_Vue%20Storefront%20Logotype.png) and resize it to 100px height or 450px width with keeping current aspect ratio.
