### ISSUE TITLE
Changing user's password and email at the same time only successfully changes email

### ISSUE THREAD

**Issue by cmegalo** [vuestorefront/vue-storefront#5315]
## Current behavior
If the user changes both their email and password for their account, they are logged out (does not occur if only 1 of password or email is changed). When logging in again with the changed email/password combo, the new email is sticking, but the new password is not. Both the password and email change API requests go through without a hitch.

## Expected behavior
The new email AND password values would be changed upon save.

## Steps to reproduce the issue
Login.
Go to the my account view to edit your account email address & password.
Change your email address and password to new values.
Save.
Try to log back in with the new values.

## Version of Vue Storefront
1.12.2

## Can you handle fixing this bug by yourself?
No

## Environment details

* Browser: Chrome v87.0.4280.88
* OS: Windows 10 Pro
* Node: v10.16.3
* Code Version: 1.12.2

**Comment by Fifciu** [comment]
Done
