### ISSUE TITLE
Issue with guest quotes with TokenInHeader=true

### ISSUE THREAD

**Issue by teuma86** [vuestorefront/vue-storefront#5317]
## Current behavior
Setting users.tokenInHeader = true on both the API and VSF instance, with Magento 2 as a backend fails to create a quote if the customer is not logged in.  Thus failing to load shipping methods / payment methods.
The error returned from magento is
{"code":500,"result":"The consumer isn't authorized to access self."}

This appears to work fine for a logged in customer

This appears to work fine when setting users.tokenInHeader=false in both instances.  (VSF AND API)

## Steps to reproduce the issue
have users.tokenInHeader = true, Magento backend (M2.3 and M2.4), VSF 1.12, VSF-API 1.12

Try adding to basket when not logged in
Note the network calls / console logs.

## Version of Vue Storefront
* [ ] Vue Storefront

## Can you handle fixing this bug by yourself?
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by undefinederror** [comment]
definitely a bug

this is the fix

![image](https://user-images.githubusercontent.com/8209966/127302732-8b3e65b7-0408-4060-90fc-b87a0c416956.png)

This prevents a headers Bearer to be set at all if token doesn't exist (guest user)
Otherwise the header is set only partially `Bearer {empty token}` and VSF-API `getToken` fails
