### ISSUE TITLE
No pagination, No per page

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5327]
## Current behavior

There is no pagination/per page at the bottom of the PLP. I assume the data is not loading there for some reason because the components themselves are in the codebase.

## Expected behavior

![image](https://user-images.githubusercontent.com/15185752/102234473-9bfcab80-3ef1-11eb-901c-28ec6e181aaa.png)

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

**Comment by RakowskiPrzemyslaw** [comment]
verified, looks like this bug is no longer occuring, @filrak  
![image](https://user-images.githubusercontent.com/33127342/109392312-af79b900-791b-11eb-95b8-a68051d90030.png)
