### ISSUE TITLE
404 and infinite redirect in multistore mode

### ISSUE THREAD

**Issue by Riu** [vuestorefront/vue-storefront#5333]
## Current behavior
Mulitstore doesn't work. There is infinity loop with redirect to `page-not-found`.

## Expected behavior
After change for settings as a user I would like to see app in multistory mode (languages, url's, etc)

## Steps to reproduce the issue
1. You need fresh install of app, with stable version, default theme.
1. You need change settings/config file: set 'storeViews.multistore` to `true` and set `defaultStoreCode`.
1. Run app in browser

## Version of Vue Storefront
* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details
* Browser: Safari/Chrome
* OS: MacOS
* Node: v12.18.4
* Code Version: 1.12.2

## Additional information
It's probably the same bug as #3396 .

**Comment by gibkigonzo** [comment]
Hey @Riu `defaultStoreCode` has some bugs. Thats why I've created this refactor https://github.com/vuestorefront/vue-storefront/pull/5043 It's based on version v1.12, but will be released in v1.13. So this problem should not exist on `develop` branch.
