### ISSUE TITLE
Checkout 

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#5334]
## Interfaces
```ts
```ts
// shipping
interface UseShipping<SHIPPING, SAVE_SHIPPING_PARAMS> {
  shipping: SHIPPING;
  load: () => Promise<void>;
  save: (params: SAVE_SHIPPING_PARAMS) => Promise<void>;
}

interface UseShippingMethod<SHIPPING_METHODS, SHIPPING_METHOD_PARAMS> {
  shippingMethods: SHIPPING_METHODS;
  load: () => Promise<void>;
  save: (params: SHIPPING_METHOD_PARAMS) => Promise<void>;
}

interface UseShippingGetters<SHIPPING, SHIPPING_ADDRESS_ITEM, SHIPPING_METHOD_ITEM> {
  getAddresses: (billing: SHIPPING, criteria?: Record<string, any>) => SHIPPING_ADDRESS_ITEM[];
  getMethods: (billing: SHIPPING, criteria?: Record<string, any>) => SHIPPING_METHOD_ITEM[];
  getAddressPostCode: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressStreetName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressStreetNumber: (address: SHIPPING_ADDRESS_ITEM) => string | number;
  getAddressCity: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressFirstName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressLastName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressCountry: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressPhone: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressEmail: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressProvince: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressCompanyName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressTaxNumber: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressApartmentNumber: (address: SHIPPING_ADDRESS_ITEM) => string | number;
  isAddressDefault: (address: SHIPPING_ADDRESS_ITEM) => boolean;
}

interface UseShippingMethodGetters<SHIPPING_METHODS, SHIPPING_MEDHOD_ITEM> {
  getShippingMethods: (methods: SHIPPING_METHODS,  criteria?: Record<string, any>) => SHIPPING_MEDHOD_ITEM[];
  getMethodName: (method: SHIPPING_MEDHOD_ITEM) => string;
  getMethodDescription: (method: SHIPPING_MEDHOD_ITEM) => string;
  getMethodPrice: (method: SHIPPING_MEDHOD_ITEM) => AgnosticPrice;
  isMethodDefault: (method: SHIPPING_MEDHOD_ITEM) => boolean
}

// billing
interface UseBilling<BILLING, BILLING_PARAMS> {
  billing: BILLING;
  load: () => Promise<void>;
  save: (params: BILLING_PARAMS) => Promise<void>;
}

interface UsetBillingGetters<BILLING, BILLING_ADDRESS_ITEM> {
  getAddresses: (billing: BILLING, criteria?: Record<string, any>) => BILLING_ADDRESS_ITEM[];
  getAddressPostCode: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressStreetName: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressStreetNumber: (address: BILLING_ADDRESS_ITEM) => string | number;
  getAddressCity: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressFirstName: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressLastName: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressCountry: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressPhone: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressEmail: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressProvince: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressCompanyName: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressTaxNumber: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressApartmentNumber: (address: BILLING_ADDRESS_ITEM) => string | number;
  isAddressDefault: (address: BILLING_ADDRESS_ITEM) => boolean;
}

// payment
interface UseCheckoutPayment<PAYMENT, PAYMENT_PARAMS> {
  payment: PAYMENT;
  load: () => Promise<void>;
  pay: (params: PAYMENT_PARAMS) => Promise<void>;
}

interface UseCheckoutPaymentGetters<PAYMENT, PAYMENT_METHOD_ITEM> {
  getMethods: (billing: PAYMENT, criteria?: Record<string, any>) => PAYMENT_METHOD_ITEM[];
  getMethodName: (method: PAYMENT_METHOD_ITEM) => string;
  getMethodDescription: (method: PAYMENT_METHOD_ITEM) => string;
  isMethodDefault: (method: PAYMENT_METHOD_ITEM) => boolean
}

// order
interface UseCheckoutOrder<ORDER> {
  order: ORDER;
  placeOrder: () => Promise<void>;
}

interface UseCheckoutOrderGetters<ORDER, ORDER_ITEM> {
  getItems: (bilorderling: ORDER, criteria?: Record<string, any>) => ORDER_ITEM[];
  getTotals: (order: ORDER) => AgnosticTotals;
  getItemName: (order: ORDER_ITEM) => string;
  getItemPrice: (order: ORDER_ITEM) => AgnosticPrice;
  getItemQty: (order: ORDER_ITEM) => number;
  getItemDescription: (cart: ORDER_ITEM) => string;
  getImage: (order: ORDER) => AgnosticMediaGalleryItem;
}

```

## Composables usage
* each composable has `load` function that will load everything is needed to handle the corresponding feature
* by default `load` loads everything but we'll be able to scope it by using certain parameter eg. `load({ address: true })` will load only address, that solution is super handy when we want to load something specific for a given platform
* functions `save` gets either form data or other parameters, again parameters can determine what really we want to save

## Core theme vs usage
* when it comes to forms, the implementation of each form will be placed in integration, but core theme will share just a component that will be overridden:

```js
<template>
  <div>
    <ShippingForm @submit="save" :response="shipping" />
    <div v-for="method in shippingMethods">
      <div>{{ checkoutShippingGetters.getMethodName(method) }}</div>
    </div>
  </div>
</template>

<script>
import { checkoutShippingGetters } from '...'

export default {
  setup() {
    const { shipping, load, save } = useCheckoutShipping();

    onSSR(() => load())

    const shippingMethods = computed(() => checkoutShippingGetters.getMethods(shipping))

    return { shipping, save, shippingMethods, checkoutShippingGetters }
  }
} 
</script>
```

as you can see `ShippingForm` will be created in the integration and replaced here

* all of the parts that can be agnostic, such as shipping methods, addresses etc. will be covered by getters as usual
* the only part that's really sensitive and really hard to be agnostic is any kind of form, all of the can me totally different depending on the integration, including behavior, appearance, logic etc.
* each form has a dedicated component that implements form in the integration but always emits an event to save something and reads the data from fixed property eg, `response`

**Comment by filrak** [comment]
Can you give some exaples on how Payment Methods not coming from the eCommerce platform can be implemented for `useCheckoutPayment` ? From where the methods should load if they are not part of the eComm platform?

**Comment by Fifciu** [comment]
```
getMethodName: (method: SHIPPING_METHOD_ITEM) => string;
getMethodDescription: (method: SHIPPING_METHOD_ITEM) => string;
```
Same shipping/payment method could have different name and description in each language. We should have some `getMethodCode`.

**Comment by andrzejewsky** [comment]
> Same shipping/payment method could have different names and descriptions in each language. We should have getter like - getMethodCode to have a universal identifier.
that's api-client level, you ask the API for a certain method with given parameters such as a language. Even if you want to translate it later, you can use the current text as a translation key - we do that in other places as well

> I think shipping methods will also have options like UPS Express, UPS Normal, UPS Parcel, etc. based on shipping details.
so from our point of view, it will be a separated method, getter will take care of it, but let's try to simplify it as much as possible and in VSF we can keep this as flatten array

> UseCheckoutPaymentGetters needs getMethodPrice
yes, you are right

> How will we use UseCheckoutPayment.pay for payments that require additional action like 3DS Auth 1.0 Redirection?
as usual `pay({ 3ds: true, redirectUrl: '...'  })` - pay always gets the arguments you need to make a payment, it can be some options like 3ds or eg. form parameters. Those parameters can change per integration, but we'll try to not keep the parameters in the core components but only rely on the data flow (from integration theme components to the core, so our theme stays fully agnostic)  

> I see more things for payment methods. However, what about Shipping methods? Shouldn't we have at least an equally flexible interface (smth like UseCheckoutPayment) to prevent future BCs?
The general idea is to proceed with the right data flow, checkout is so complicated and it doesn't make any sense to introduce dedicated functions to cover certain problems (eg. loadMethods, saveMethods etc.) - instead, one function that will save something by given params. Keep in mind also that generating forms and handling them will be placed in the integration (not core theme) so the integration will implement components like ShippingForm, BillingForm, etc that will only emit an event handled by core theme (notice data flow - bottom-up)

**Comment by mkucmus** [comment]
>// payment
> interface UseCheckoutPayment<PAYMENT, PAYMENT_PARAMS> {
  payment: PAYMENT;
  load: () => Promise<void>;
  pay: (params: PAYMENT_PARAMS) => Promise<void>;
}

_pay: (params: PAYMENT_PARAMS) => Promise<void>;_
I think we could expect some output here, for isntance when the payment starts the redirection to the payment gateway (async payment after order is placed), then we could have the response like this:
```
data: {
  paymentUrl: "paypal.com/gatewat/pay/<ORDER_ID>/<TOKEN>...
}
```
or
```
data: {
 shortLifeToken: "ABCDE12234334343434"
}
```
the second thing is the stripe or other payment methods uses Payment API from the browser, and it's possible to "make a reservation of founds during the checkout (popup asks for some details, like credit card number), then we need some output from the external service to save the token in our backend (session related), then the order can be placed.

> interface UseCheckoutBillingGetters<BILLING, BILLING_ADDRESS_ITEM> {
each platform has its own validation rules, maybe we can provide a method for checking the values against the rules as a callback or sth like this? like a "dry run" mode :) 

It would be method named `validate()`...
the same for shipping I guess. 
Maybe validation is something extra and should have its own rfc instead, but it's really hard to keep backend and frontend platforms consistent in validations. many of ecommerce have a validation configs in admin panel depending on country, like zipcode.  


> interface UseCheckoutPaymentGetters<PAYMENT, PAYMENT_METHOD_ITEM> {
  getMethods: (billing: PAYMENT, criteria?: Record<string, any>) => PAYMENT_METHOD_ITEM[];
  getMethodName: (method: PAYMENT_METHOD_ITEM) => string;
  getMethodDescription: (method: PAYMENT_METHOD_ITEM) => string;
  isMethodDefault: (method: PAYMENT_METHOD_ITEM) => boolean
}

I would add sth like   `getMethodCode: (method: PAYMENT_METHOD_ITEM) => string;` just for e2e or extensibility purposes, it would be sort of humand readable ID of the method.

> interface UseCheckoutOrderGetters<ORDER, ORDER_ITEM> {
  getItems: (bilorderling: ORDER, criteria?: Record<string, any>) => ORDER_ITEM[];
  getTotals: (order: ORDER) => AgnosticTotals;
  getItemName: (order: ORDER_ITEM) => string;
  getItemPrice: (order: ORDER_ITEM) => AgnosticPrice;
  getItemQty: (order: ORDER_ITEM) => number;
  getItemDescription: (cart: ORDER_ITEM) => string;
  getImage: (order: ORDER) => AgnosticMediaGalleryItem;
}

there are additional "things" like:
- discount, for given item -> `getItemDiscount()` if the item is in type of "product" related entity - not discount, or 
- coupon codes - almost every ecommerce has it, it's discount related, but sometimes it's willingly needed on the chekout to see what coupons were applied., so `getCouponCodes` maybe?
- validation method/getter - `validate()`, `isOrderValid`? maybe it should be palced in `UseCheckoutOrder<ORDER> {` isntead

**Comment by andrzejewsky** [comment]
under development at the moment:
```ts
// shipping
interface UseShipping<SHIPPING, SAVE_SHIPPING_PARAMS> {
  shipping: SHIPPING;
  load: () => Promise<void>;
  save: (params: SAVE_SHIPPING_PARAMS) => Promise<void>;
}

interface UseShippingMethod<SHIPPING_METHODS, SHIPPING_METHOD_PARAMS> {
  shippingMethods: SHIPPING_METHODS;
  load: () => Promise<void>;
  save: (params: SHIPPING_METHOD_PARAMS) => Promise<void>;
}

interface UseShippingGetters<SHIPPING, SHIPPING_ADDRESS_ITEM, SHIPPING_METHOD_ITEM> {
  getAddresses: (billing: SHIPPING, criteria?: Record<string, any>) => SHIPPING_ADDRESS_ITEM[];
  getMethods: (billing: SHIPPING, criteria?: Record<string, any>) => SHIPPING_METHOD_ITEM[];
  getAddressPostCode: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressStreetName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressStreetNumber: (address: SHIPPING_ADDRESS_ITEM) => string | number;
  getAddressCity: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressFirstName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressLastName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressCountry: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressPhone: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressEmail: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressProvince: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressCompanyName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressTaxNumber: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressApartmentNumber: (address: SHIPPING_ADDRESS_ITEM) => string | number;
  isAddressDefault: (address: SHIPPING_ADDRESS_ITEM) => boolean;
}

interface UseShippingMethodGetters<SHIPPING_METHODS, SHIPPING_MEDHOD_ITEM> {
  getShippingMethods: (methods: SHIPPING_METHODS,  criteria?: Record<string, any>) => SHIPPING_MEDHOD_ITEM[];
  getMethodName: (method: SHIPPING_MEDHOD_ITEM) => string;
  getMethodDescription: (method: SHIPPING_MEDHOD_ITEM) => string;
  getMethodPrice: (method: SHIPPING_MEDHOD_ITEM) => AgnosticPrice;
  isMethodDefault: (method: SHIPPING_MEDHOD_ITEM) => boolean
}

// billing
interface UseBilling<BILLING, BILLING_PARAMS> {
  billing: BILLING;
  load: () => Promise<void>;
  save: (params: BILLING_PARAMS) => Promise<void>;
}

interface UsetBillingGetters<BILLING, BILLING_ADDRESS_ITEM> {
  getAddresses: (billing: BILLING, criteria?: Record<string, any>) => BILLING_ADDRESS_ITEM[];
  getAddressPostCode: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressStreetName: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressStreetNumber: (address: BILLING_ADDRESS_ITEM) => string | number;
  getAddressCity: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressFirstName: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressLastName: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressCountry: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressPhone: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressEmail: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressProvince: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressCompanyName: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressTaxNumber: (address: BILLING_ADDRESS_ITEM) => string;
  getAddressApartmentNumber: (address: BILLING_ADDRESS_ITEM) => string | number;
  isAddressDefault: (address: BILLING_ADDRESS_ITEM) => boolean;
}
```

**Comment by Fifciu** [comment]
Shipping proposal:
```ts
export interface UseShipping<SHIPPING, SHIPPING_PARAMS> {
  error: ComputedProperty<UseShippingErrors>;
  loading: ComputedProperty<boolean>;
  shipping: ComputedProperty<SHIPPING>;
  load: () => Promise<void>;
  save: (params: { params: SHIPPING_PARAMS; shippingDetails: any }) => Promise<void>;
}
export interface UseShippingErrors {
  load?: Error;
  save?: Error;
}
export interface ShippingGetters<SHIPPING, SHIPPING_ADDRESS_ITEM> {
  getAddress: (shipping: SHIPPING, criteria?: Record<string, any>) => SHIPPING_ADDRESS_ITEM[];
  getAddressPostCode: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressStreetName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressStreetNumber: (address: SHIPPING_ADDRESS_ITEM) => string | number;
  getAddressCity: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressFirstName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressLastName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressCountry: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressPhone: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressEmail: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressProvince: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressCompanyName: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressTaxNumber: (address: SHIPPING_ADDRESS_ITEM) => string;
  getAddressApartmentNumber: (address: SHIPPING_ADDRESS_ITEM) => string | number;
}
export interface UseShippingMethod<SHIPPING_METHOD_OBJECT, SHIPPING_METHOD_PARAMS> {
  shippingMethods: ComputedProperty<SHIPPING_METHOD_OBJECT>;
  error: ComputedProperty<UseShippingMethodErrors>;
  loading: ComputedProperty<boolean>;
  load: () => Promise<void>;
  save: (params: SHIPPING_METHOD_PARAMS) => Promise<void>;
}
export interface UseShippingMethodErrors {
  load?: Error;
  save?: Error;
}
export interface ShippingMethodGetters<SHIPPING_METHODS, SHIPPING_METHOD_ITEM> {
  getMethods: (methods: SHIPPING_METHODS, criteria?: Record<string, any>) => SHIPPING_METHOD_ITEM[];
  getCurrentMethod: (methods: SHIPPING_METHODS) => SHIPPING_METHOD_ITEM;
  getMethodId: (method: SHIPPING_METHOD_ITEM) => string;
  getMethodName: (method: SHIPPING_METHOD_ITEM) => string;
  getMethodDescription: (method: SHIPPING_METHOD_ITEM) => string;
  getMethodPrice: (method: SHIPPING_METHOD_ITEM) => number;
  isMethodDefault: (method: SHIPPING_METHOD_ITEM) => boolean;
}
```
