### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by j209** [vuestorefront/vue-storefront#5335]
Hi
What about [Vue 3](https://github.com/vuejs/vue-next) support in vue storefront-next?

**Comment by filrak** [comment]
Hey!

We definitely plan to use Vue 3 in VSFN but the ecosystem is not ready yet.

We're still waiting for tools like Nuxt 3 to support Vue 3 until we can start planning the migration.

I think the realistic date to start such migration is for sure not before mid of 2021 as it takes time for lib authors to adjust and we want to be sure that our users won't experience a lack of ecosystem support.

**Comment by spokospace** [comment]
Do you already know when we can expect Vue3 support?

**Comment by michael-kaufman** [comment]
Hi, this was quite a while ago. What is the status today ?  Thanks!

**Comment by filipsobol** [comment]
@spokospace @michael-kaufman We are waiting for the stable release of Nuxt 3, which is still in beta.

**Comment by ThaDaVos** [comment]
Why wait for stable? Why not start with the First Release Candidate (20 April)?

**Comment by filrak** [comment]
Hey! Unfortunately we are still waiting for Nuxt to be stable ;/

**Comment by amery** [comment]
> Hey! Unfortunately we are still waiting for Nuxt to be stable.
> 

3.0.0 good enough?

**Comment by JavaChr1s** [comment]
Is there already a roadmap for the nuxt 3 migration?

**Comment by jacobtshirt** [comment]
Patiently waiting for Nuxt 3 to be added to VSF's roadmap so I can add it to my employers roadmap...

**Comment by JavaChr1s** [comment]
> Is there already a roadmap for the nuxt 3 migration?

Maybe @filrak can give an answer on this?

**Comment by MarciB-IT** [comment]
push, in the meantime Nuxt3 is gone stable, any idea when you'll support vue3 @filrak?

**Comment by Mikephii** [comment]
Any idea when you will support vue3? and nuxt3?  VSF is starting to become tech debt
