### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by mrrobotisback** [vuestorefront/vue-storefront#5336]
## Current behavior

When navigate commercetools integration with mobile, mobile menu not working, click and nothing happen.

## Expected behavior

When navigate commercetools integration with mobile, click on menu icon and open menù with categories.

## Steps to reproduce the issue

yarn dev:ct and navigate in mobile mode.

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: Chrome (Version 87.0.4280.88 (Official Build) (64-bit))
* OS: 
 NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
* Node: v12.19.1
* Code Version: next

**Comment by omaratta212** [comment]
I can work on this

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
