### ISSUE TITLE
UnicodeAlpha field validation not working properly

### ISSUE THREAD

**Issue by pablogiralt** [vuestorefront/vue-storefront#5340]
## Current behavior

Field validation passes when any character from field value is a unicode alpha char. 
"%%" does not pass validation, which is the expected behaviour:
![](https://user-images.githubusercontent.com/9419680/102773743-08602a80-438a-11eb-8c77-3eacef8a9bc7.png)

However, "Jo$%n Do?" validates correctly:
![](https://user-images.githubusercontent.com/9419680/102774007-70167580-438a-11eb-8a59-6e0ff30f3340.png)

## Expected behavior

If string has **any** special characters it should not validate

## Steps to reproduce the issue

* Go to checkout
* Write a name with one or more correct alpha characters and with one or more incorrect special characters

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: Chrome 87.0.4280.88
* OS: Mac OS 10.13.6
* Node: v10.16.3
* Code Version: Develop

**Comment by gibkigonzo** [comment]
imo it's not related with vsf. you should use different validator, for example https://github.com/vuelidate/vuelidate/blob/master/src/validators/alpha.js

**Comment by pablogiralt** [comment]
@gibkigonzo sorry to disagree but code is in VSF core:
https://github.com/vuestorefront/vue-storefront/blob/master/core/helpers/validators/index.ts

**Comment by pablogiralt** [comment]
And this is included in capinara theme:
https://github.com/vuestorefront/vsf-capybara/search?q=unicodeAlpha
and in the default theme:
https://github.com/vuestorefront/vsf-default/search?q=unicodeAlpha

**Comment by gibkigonzo** [comment]
Yes, you are right. Since the solution is in vuelidate then in vsf those validators should be deprecrated. Other solution is just copy/paste from vuelidate 🤷
