### ISSUE TITLE
Minicart doesn't update all product data when removing from cart

### ISSUE THREAD

**Issue by yesitsmattharris** [vuestorefront/vue-storefront#5347]
## Current behavior
When removing products from the minicart, the qty doesn't update for each product row

## Expected behavior
When removing products from the minicart, all data should update for each product row

## Steps to reproduce the issue
* Add multiple products to cart
* Open minicart
* Note qty of each product (e.g. using Vue extension for Chrome)
* Remove any product except the last one
* Note how the names have updated, but the qty still reflects the row's previous product

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: Chrome 87.0.4280.88
* OS: MacOS 10.15.4
* Node: 10
* Code Version: 1.11.2

**Comment by Fifciu** [comment]
The problem is not reproducible in the way you provided. I've tried `master` and `hotfix/v1.12.3` branches. Everything works properly.
