### ISSUE TITLE
Stack recommendation

### ISSUE THREAD

**Issue by cruonline** [vuestorefront/vue-storefront#5354]
Hi,

Just a quick question about stack recommendation.
I'm building a medium-sized shop (few hundred SKUs), rather niche, so not expecting heavy traffic.

What stack would you recommend?

- Magento + VSF-API + VSF1
- Shopware 6 + Shopware-PWA

Note, I'm JS developer by trade, so I feel more comfortable in tinkering with Vue part than shop backend :)

Btw, what are current limitations of @next branch?

Merry Christmas
Piotr

**Comment by mkucmus** [comment]
@cruonline not quantity of SKUs but features you need - that matters in this case. The best you can do is to compare both backend platforms, and then check whether frontend part fits your needs. Nevertheless, from my experience: the complexitiy is way smaller in shopware6 + shopware-pwa, there is no middleware between frontend and backend, it's faster, but pwa is still in beta (we working on it constantly). From the other hand, magento ships more out of the box features... :)

**Comment by cruonline** [comment]
Thanks,
It was pretty much the answer I was looking for. Shopware it is.
I have no need for fancy features :)
