### ISSUE TITLE
useNotification

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5363]
## What is the motivation for adding / enhancing this feature?

We need a Notification system in VSFN Theme. It should work very similarly to the one from VSF1

## What are the acceptance criteria 

* [ ] put `useUiNotification` in `theme/composables/useUiNotification`
* [ ] API should be as follows:

```ts
const { notifications: UiNotification[], send: (notification: UiNotification) => void } = useUiNotification()

interface UiNotification {
   message: string:
   action: { text: string; onClick: function }
   type: // like in SfNotification
   icon: string,
   persist: boolean (false by default)
}
```

* [ ] Notification should disappear only:
  * if 3 seconds has passed (if `persist !== true`)
  * if `x` was clicked
* [ ] It should appear on the right bottom corner of the app and use `SfNotification` from [Storefront UI](https://storybook.storefrontui.io/?path=/story/molecules-notification--common) and on the bottom (right above bottom nav) in mobile
* [ ] No more than 3 Notifications at a time (others should be queued)
* [ ] Consider https://www.npmjs.com/package/vue-notification (if it makes sense)
## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
