### ISSUE TITLE
Add to cart on PDP doesn't work

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5368]
## Current behavior

1. Enter https://lovecrafts-demo.storefrontcloud.io/p/6dbfdfd5-2e34-4dd6-ac18-c0cc98b84d78/poloralphlauren-sweater-A40S4603-pink
1. Try to add product to the cart
1. see error

![image](https://user-images.githubusercontent.com/15185752/103649270-7b5acb00-4f5e-11eb-82f9-734a6df39729.png)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
