### ISSUE TITLE
Login & Registration form error/success handling and validation

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5377]
#### Errors
Use VSF Error Handling to display errors in login/registration forms.

How the flow should look like:

1. User is entering the data to the form
1. Sends the form
1. UI notification with "Something went wrong!" is being displayed
1. If the error corresponds to a certain field display it under this fields (eg email already taken under email field) (so you should do ifs based on error message therefore login/registration form are parts of integration templates)
1. For other issues add `SfAlert` on top of registration/login form with a friendly message. For example

```html
<SfAlert v-if="error.logIn.message === 'Lorem ipsum dolor'" type="danger" :message="error.logIn.message" />
```

#### Success
* If user logs in display "Successfully logged in" notification of type `success`
* If user registers successfully display "Successfully created a new account"

## What are the acceptance criteria 

* [ ] All errors are handled for Logging in according to specification
* [ ] All errors are handled for Registering according to specification
* [ ] Success messages are displayed

**Comment by skirianov** [comment]
Issue is closed. Reason: Too Old (>6 months)

---

Sergii Kirianov

Developer Advocate

Vue Storefront
