### ISSUE TITLE
CLI stops in integration - setup tutorial isn't equal?

### ISSUE THREAD

**Issue by CosmicSnow** [vuestorefront/vue-storefront#5414]
Should the `vsf init` command stop in integration?
it doesn't show anything after this!!

I tried in windows and ubuntu server, no luck,
the doc. about setup isn't working for me too, if I try it via CLI, it stops in integration part,
if I try with docker, it fails on installation of kibana in the part removing x-pack, then it dies, returning error code 1.

Am I missing something?
I want to setup front and backend locally to test it out and understand how it works,
but no luck setting demo up.

p.s. only commercetools appears.

![image](https://user-images.githubusercontent.com/59381242/104834085-fe8ff100-587b-11eb-8d90-9b23b0e5646a.png)
![image](https://user-images.githubusercontent.com/59381242/104834083-fb950080-587b-11eb-9d58-97958a0d532f.png)

**Comment by FaustTobias** [comment]
Downgrading to 0.2.1 seems to work as a workaround:

```bash
yarn global add @vue-storefront/cli@0.2.1
```

It seems like all versions matching ^2.0.0 are broken.

**Comment by CosmicSnow** [comment]
> Downgrading to 0.2.1 seems to work as a workaround:
> 
> ```shell
> yarn global add @vue-storefront/cli@0.2.1
> ```
> 
> It seems like all versions matching ^2.0.0 are affected.

isn't 0.2.1 a big downgrade from ^2.0.0 ?

**Comment by FaustTobias** [comment]
It provides the same user interface as outlined in [their documentation](https://docs.vuestorefront.io/guide/cookbook/setup.html#_2-recipe). The version history of the package jumps directly from 0.2.1 to 2.0.0. It would be nice, if the docs would mention what you actually need to do to follow the setup. I was just trying out vue storefront yesterday and that was the solution I used to "fix" the problem.

**Comment by Fifciu** [comment]
Hello.
Version 0.x.x is for VSF1
Version 2.x.x is for VSF Next

If you want to use version 0.x.x, then you have to point to the exact version as @FaustTobias said.
