### ISSUE TITLE
Doc: Guide > Authentication

### ISSUE THREAD

**Issue by Fifciu** [vuestorefront/vue-storefront#5416]
# Plan of the document
### What's the authentication?
- I want to explain what's authentication and why we need it
### Registering a new user
- Show the user how to do it (snippet) and add a simple sentence about that
### Logging in/out and sessions
- (login) Show the user how to do it and add a simple sentence about that
- (logout) Show the user how to do it and add a simple sentence about that
### What auth strategies do we follow?
- Token, JWT Token, Basic HTTP Token with links to explanations (external) and mention that it depends on the integration which strategy we use
- We prefer to keep it in the cookie

**Comment by filrak** [comment]
Looks great! I noticed It's touching the commercetools parts though  while these dos should be true for any integration.

Also would be great if you could make it a bit more detailed (outline what and how you want to explain things)

**Comment by filipsobol** [comment]
I wonder if `Loading user`, `Modifying a user` and `Changing the password` sections shouldn't be in `User Profile` docs?

**Comment by Fifciu** [comment]
I agree @filipsobol . Updated

**Comment by filrak** [comment]
@Fifciu where in this flow you will put links to integrations like this https://docs-next.vuestorefront.io/guide/configuration.html#configuring-integrations ?

**Comment by NataliaTepluhina** [comment]
@Fifciu looks like a great plan! My only comment here is let's try to keep the `what's authentication` section short and crispy (I believe we can write the whole book in this section and we definitely don't want to 😅 )

**Comment by Fifciu** [comment]
@filrak My first thought was that we should have a link in each part. But it is not so elegant. I think I should add the last part called `Detailed strategies per integration`. Wdyt @filrak @NataliaTepluhina ?

Btw. I agree with you arguments for keeping `what's authentication` short :D

**Comment by filrak** [comment]
Its okejka from me as well, please start with the doc!

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
