### ISSUE TITLE
VSF Bad command

### ISSUE THREAD

**Issue by mfamahran** [vuestorefront/vue-storefront#5420]
## Current behavior
When executing vsf init:theme an error is returned " ERROR  VSF Bad command"

## Expected behavior
Is to let me choose the directory of vuestorefront and theme to install it for me

## Steps to reproduce the issue
Blank Debian 9 server and following the production setup step by step leads to this issue 

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: NA
* OS: Debian 9
* Node: 10
* Code Version: master

**Comment by Fifciu** [comment]
Hello. I think you are using the command from VSF1 CLI and have installed VSFNext CLI. Could you check that at first?

**Comment by gautammd** [comment]
@Fifciu how do we install VSF CLI instead of VSFNext CLI. could you please let me know? I am having the same issue.

**Comment by Fifciu** [comment]
Hello.
Version 0.x.x is for VSF1
Version 2.x.x is for VSF Next

If you want to use version 0.x.x, then you have to point to the exact version, e.g:
```sh
yarn global add @vue-storefront/cli@0.2.1
```
If you want to use version 2.x.x for VSF Next, then just use:
```sh
yarn global add @vue-storefront/cli
```

**Comment by draper87** [comment]
@Fifciu I had to add "sudo" before "yarn global add @vue-storefront/cli", now it works.

**Comment by Fifciu** [comment]
@draper87 It is a bad practice to use `sudo` with `yarn global add`. If you were forced you that it might mean you had something wrong with chmods. Using sudo is not a proper solution, you should restore proper chmods.
