### ISSUE TITLE
Docs: Guide > User Profile

### ISSUE THREAD

**Issue by filipsobol** [vuestorefront/vue-storefront#5426]
# Structure of the document

## Table of Content
1. Introduction
2. Checking if user is logged in
3. Loading current user
4. Modifying user
5. Changing password
6. Managing addresses (billing and shipping)
7. Listing user orders
8. Customizing forms in the user profile
9. Protecting user profile routes

### Checking if user is logged in
Many interactions are only available or are different if the customer is logged in. In this section, I will explain how to check if we are dealing with logged-in user or guest.

### Loading current user
Explain how to get information about the current user.

### Modifying user
Explain how to modify the current user and update the frontend state.

### Changing password
Explain how to change the password.

### Managing addresses
Explain how to add, update and delete billing and shipping addresses. It might be worth mentioning why it's a good practice to allow the user to select the default address and how it shortens the checkout process.

### Listing user orders
Explain how to load a list of orders.

### Customizing forms in the user profile
Forms in the user profile are different based on used integration. In this section, I will explain how to customize them.

### Protecting user profile routes
All pages in the user profile should be protected and not accessible to guests. Code snippets from this example should also allow protecting other pages.

**Comment by NataliaTepluhina** [comment]
@filipsobol I like the logical flow here! The only nitpick is: it seems that protecting user profile routes is more connected to `Checking if user is logged in` section, so I wonder if it's possible to group them?

**Comment by filipsobol** [comment]
That was my initial thought, but checking if the user is logged in and protecting user routes are handled differently. This might change when we update to Vue 3, but right now we can't use composables in middleware, so protecting routes is done using cookies.

Additionally, I think that `Checking if user is logged in` is something that will be googled a lot, so it'd nice to have it as a separate section.

Let me know what you think.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
