### ISSUE TITLE
Doc: Guide > cart and wishlist

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/vue-storefront#5427]
# Cart and wishlist document plan:

## 1. Introduction
[short overview of what is explained in this document] 

## 2. Using cart:
1.  installation and loading
1.  basic usage scenarios:
[show on examples]
     * adding item
     * removing an item from a cart
     * checking if an item is on a cart
     * cleaning a cart
  
 3. other scenarios:
     * applying and removing coupons from a cart
     * guest carts 
 
## 3. Using wishlist:
1. installation and loading
1. basic usage scenarios:
[show on examples]
   * adding 
   * removing
   * checking 
   * cleaning 

## 4. Summary.
1. common usage example
 [one common example which includes basic usage scenarios]

2. list of available properties and getters
[list of properties and getters for useCart and useWishlist, in form of the table]

**Comment by filrak** [comment]
Why it is not based on Table of Contents from the docs?
```
8. Carts and Wishlists
  1. Loading the cart
  2. Managing products in the cart
  3. Clearing the cart
  4. Checking if item is in the cart
  5. Guest carts
  5. Wishlists
```

**Comment by AdamPawlinski** [comment]
I made my own list  only a little more detailed. The docs are prepared for every point except guest cart, cause I wonder if it depends on every integration and can be solved differntly and on core level is not much to write. Please let me know if I'm wrong.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
