### ISSUE TITLE
Doc: Commercetools > Composables API Reference / API Client Reference

### ISSUE THREAD

**Issue by lukaszjedrasik** [vuestorefront/vue-storefront#5428]
I think that this task has three main subtasks. 

- creating a script for auto-generating API Reference,
- how exactly these sections should look like (placing, UI?),
- adding References to proper places in our docs

At the moment I have used `typedoc` (I had some problems with api-extractor) for auto-generating API Reference and I have a lot of markdown files (screenshot below).

![Zrzut ekranu 2021-01-20 o 15 39 48](https://user-images.githubusercontent.com/40273258/105190128-fe227f00-5b35-11eb-9b6a-9cb387674be7.png)

The next step should be adding all(?) these files to proper places.

**Comment by NataliaTepluhina** [comment]
> creating a script for auto-generating API Reference
Yay for this! Would make updating API reference way easier on any code change

> how exactly these sections should look like (placing, UI?)
...and implementing a proper search as it's crucial when we have the full API reference (Algolia?)

The plan with subtasks looks really solid 👍🏻

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
