### ISSUE TITLE
Bug in documentation

### ISSUE THREAD

**Issue by stalker3343** [vuestorefront/vue-storefront#5429]
## Current behavior
After clicking on the "installation guide" link on the page https://docs-next.vuestorefront.io/. I go to the page https://docs-next.vuestorefront.io/general/getting-started.html where the first code block shows the comment:
// Make sure to add code blocks to your code group
![изображение](https://user-images.githubusercontent.com/42894422/105325887-25cd2200-5bde-11eb-95c6-f351c158ff89.png)

## Expected behavior

See the code for installing the CLI
![изображение](https://user-images.githubusercontent.com/42894422/105326004-4b5a2b80-5bde-11eb-9763-9b174382d999.png)

## Steps to reproduce the issue
Clicking on the "installation guide" link on the page https://docs-next.vuestorefront.io/. Go to the page https://docs-next.vuestorefront.io/general/getting-started.html

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: Firefox 84.0.2
* OS: Windows
* Node: -
* Code Version: -

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
