### ISSUE TITLE
[MIDDLEWARE] headers redirection

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#5430]
## What is the motivation for adding / enhancing this feature?
As of now, we are redirecting the traffic over our middleware, we can also redirect entire headers. Sometimes when we redirect some of them, it can cause some errors due to having reverse-proxy etc. so at this moment we redirect only the cookie header to the integrated API.

As an end-user or integrator would be nice to pick what headers we need to redirect (besides the cookies)

## What are the acceptance criteria 
* [ ] dedicated section in the config of middleware modules called `redirectHeaders` or something like this. This option is an array that contains all of the headers I want to redirect
* [ ] This option should also accept a function (instead of an array) that returns headers to redirect. As arguments, you can access the current headers or even whole request

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

**Comment by odranoelBR** [comment]
Need it!

**Comment by skirianov** [comment]
Issue is closed. Reason: Too Old (>6 months)

---

Sergii Kirianov

Developer Advocate

Vue Storefront
