### ISSUE TITLE
[MIDDLEWARE] Custom axios configuration

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#5432]
## What is the motivation for adding / enhancing this feature?
The interaction with our middleware is happening by using axios beneath. Of course we use only default settings but sometimes there is a need to implement something more, such as interceptors or other handy stuff that axios gives for us.

## What are the acceptance criteria 
* [ ] and another section in the middleware config called `axios`, everything we pass in this section, will be used as axios additional axios configuration

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [x] YES
* [ ] NO

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
