### ISSUE TITLE
Does the elastic search license change affect VSF?

### ISSUE THREAD

**Issue by joebordes** [vuestorefront/vue-storefront#5445]
I'm curious

**Comment by Fifciu** [comment]
VSF1 will stay with <7.11 version. SSPL looks ambiguous and I do not want to have anyone from our community have problems related to that. 

I think it should be okay to use 7.11+ in your projects. However, you are doing it on your own responsibility.

**Comment by joebordes** [comment]
I understand and agree. Thanks!
