### ISSUE TITLE
Typo in price sync

### ISSUE THREAD

**Issue by Cheeerd** [vuestorefront/vue-storefront#5446]
https://github.com/vuestorefront/vue-storefront/blob/827916d7c61b33b1b3dcc14d9e4becaa018d70ec/core/modules/catalog/helpers/price/syncProductPrice.ts#L15
Here instead of "original_trice" should be "original_price".

**Comment by Fifciu** [comment]
Good catch. There is a fix: https://github.com/vuestorefront/vue-storefront/pull/5391
We are still waiting for rebase from the author. If you could prepare this one for `hotfix/v1.12.3` it would be great
