### ISSUE TITLE
No shipping method in checkout

### ISSUE THREAD

**Issue by filrak** [vuestorefront/vue-storefront#5463]
## Current behavior

1. Go to checkout as a guest, go to shipping, click "choose shipping method"
1. 

![image](https://user-images.githubusercontent.com/15185752/106126590-d480dd80-615d-11eb-84b9-70023701e7cd.png)

## Expected behavior

There should be a shipping method to choose

## Version of Vue Storefront

* [ ] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by Baroshem** [comment]
I couldn't reproduce this issue.
1. Added product to cart
2. Went to checkout
3. Provided Shipping details
4. Shipping method appeared (not logged in)
![image](https://user-images.githubusercontent.com/37120330/110016876-d83bed00-7d25-11eb-8406-eff5c07d1991.png)

**Comment by andrzejewsky** [comment]
no longer up to date since we have a new checkout flow (CC: @Fifciu)

**Comment by Baroshem** [comment]
Reopening issue because after receiving more detailed explanation of the issue, bug can be reproduced.

**Comment by Baroshem** [comment]
More detailed explanation:

Fill the shipping form with dummy data:
![image](https://user-images.githubusercontent.com/37120330/110314510-3b6c9e80-8008-11eb-8a56-c3f634d2c531.png)

After that, the select shipping method button will be disabled and then the shipping method component appears without data inside:
![image](https://user-images.githubusercontent.com/37120330/110314848-b2a23280-8008-11eb-818e-428dfc060ea2.png)

Error appears in the browser console:
![image](https://user-images.githubusercontent.com/37120330/110314912-c6e62f80-8008-11eb-91e0-b85866de3d1e.png)

Error in terminal/console:
![image](https://user-images.githubusercontent.com/37120330/110308961-0e68bd80-8001-11eb-9407-b7be1bff035f.png)


Another error:
![image](https://user-images.githubusercontent.com/37120330/110314989-dfeee080-8008-11eb-8f18-83fcc18802aa.png)

After much longer time we can see an error in the template but it is not triggered by the first error with the wrong tax/shipping method but by the error below
![image](https://user-images.githubusercontent.com/37120330/110315529-ad91b300-8009-11eb-94ce-528c8d92e6d9.png)
![image](https://user-images.githubusercontent.com/37120330/110315640-d44fe980-8009-11eb-8f4f-0719f050219d.png)


Proposed solution to that was to develop a message that can be shown to the user explaining the issue.
