### ISSUE TITLE
[MIDDLEWARE] Extensions

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#5476]
# Summary
[summary]: #summary

A way of extending API-client on the middleware

# Motivation
[motivation]: #motivation

Most of the 3rd party integrations can be done on server-middleware without touching the front-end layer. Always, this is about either modifying or enhancing the response or parameters to the API we interact with. The ability to do this will open for us a flexible way to write other integrations.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

Introducing API-extension means

* new config option within the middleware module that allows you to add some extensions
* by using an extension you can interact with a lifecycle of API call: before the client is being set up, after its setup, before the call, and after the call
* each lifecycle functions gives you parameters that you can use or override which may impact the result or behavior of the API-connection

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

## 1. Configuration
To add an extension, you can use a dedicated section in middleware module options. This section takes an array of extensions that can be imported in a project (as a function) or a string that refers to the package which exposing the extension.

```
    ['@vue-storefront/middleware/nuxt', {
      integrations: {
        ct: {
          api: '@vue-storefront/commercetools-api/server',
          module: '@vue-storefront/commercetools/nuxt',
          extensions: [extension1, extension2, "@package-of-extension"]
        } 
      }
    }]
```

## 2. Writing an extension
Each extension is defined by the following interfaces:

```ts
interface ApiClientExtensionLifecycle {
  beforeCreate?: ({ config }) => any;
  afterCreate?: ({ config }) => { config; client };
  beforeCall?: ({ config, functionName, params }) => any;
  afterCall?: ({ config, functionName, params, response }) => any;
}

type ApiClientExtension = (req: any, res: any) => ApiClientExtensionLifecycle;

```

* `ApiClientExtension ` - is a function, that takes the request and response in the middleware and return `ApiClientExtensionLifecycle`
* `ApiClientExtensionLifecycle` - that's the set of lifecycle hooks where you can inject in
* `beforeCreate` - called before API-client is being created, takes the current config and must return the config, in the body, you can change some of the config properties. _Usage: change incoming parameters, adding additional configuration for sdk_
* `afterCreate` - called once API-client was created, takes config and has to return config, adds additional config options that should be exposed in the application, but may not be used in the connection itself. _Usage: add fixed options that are available in the app, but doesn't impact the connection, such as channel option, default locale etc._
* `beforeCall` - triggered before each api call, takes current config, function name, and its params as arguments, It has to return arguments as well. _Usage: Changing the original arguments of the called API-function_ 
* `afterCall` - triggered right after API-call, takes current config, function name its params and response as arguments, It has to return response as well. _Usage: changing the original response of given API-call`

Example:

```ts
const tokenExtension: ApiClientExtension = (req, res) => {

  return {
    beforeCreate: ({ config }) => ({ ...config, locale: 'de' }),
    beforeCall: ({ functionName, params }) => {
      if (functionName == 'getProduct') {
         return { ...params: id: 'XXXXX' }
      }
      
      return params
    },
    afterCall: ({ functionName, response }) => {
     if (['getCart', 'addToCart'].includes(functionName)) {
       return { ...response, discount: response.custom.thirtPartyDiscount }
     }
    
      return response
    }
  };
};
```

# Unresolved questions
[unresolved-questions]: #unresolved-questions

* Do we need also an extension for global purposes? (one per all of the integration)
* Do we need access to any additional properties on the lifecycle functions?
* Do we need any additional lifecycle function?
* Do we need a... module helper that will help the developer to add some extension from the module?

**Comment by filrak** [comment]
Few things from my side

I think there is a lot of redundancy and overcomplication here (API-wise). We already have knowledge about `api` and `module` fields, just in a different scope, same with integration tag. Also we already have  integration module and putting logic related to it elsewhere contributes to overcomplication (now I have more than 1 place that are responsible for my integrations configuration).




# Registration

There is no need for `@vue-storefront/middleware/nuxt` to be directly exposed to the nuxt config. At this point its an implementation detail and vital part of VSF therefore should be available through `@vue-storefront/nuxt`module.

I suggest just adding a `middleware` property there

It is possible to register runtime modules from buildOnly ones.

# Configuration

We're just adding `extensions` field to our nuxt module. Then we just save the data needed by the runtime module and read from it.

This way we're keeping separation of concerns

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
