### ISSUE TITLE
[Next] My Account is not aware of users authentication status.

### ISSUE THREAD

**Issue by oodgaard** [vuestorefront/vue-storefront#5482]
## What is the motivation for adding / enhancing this feature?
As an unauthorized user I should not have access or be able to navigate my-account pages.

## What are the acceptance criteria 
* [x] Unauthorized users should be redirected to a login page or modal if they access any my-account pages.
* [x] All my-account pages should be protected.

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
This depends on the direction the VSF team would like to take.

* [ ] YES
* [ ] NO

## Additional information

I believe this feature should be in core as it's a fundamental requirement to any site with user specific pages.

**Comment by filipsobol** [comment]
Hi, thanks for the report.

We are aware of this issue and already have PR to fix it #5442, which should be included in the next release.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
