### ISSUE TITLE
Error: No available storage method found

### ISSUE THREAD

**Issue by simonmaass** [vuestorefront/vue-storefront#5491]
## Current behavior

in sentry we can see quite a few erros about storage method:
![image](https://user-images.githubusercontent.com/32599710/106918104-31096d00-6709-11eb-993d-e9a6fb48308a.png)

## Expected behavior
no errors or at least a fallback

## Steps to reproduce the issue
Maybe related?
https://github.com/localForage/localForage/issues/722
https://github.com/localForage/localForage/issues/914
https://github.com/localForage/localForage/issues/705

## Version of Vue Storefront

* [x] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by didkan** [comment]
@simonmaass 
See this: https://github.com/vuestorefront/vue-storefront/pull/5097

**Comment by simonmaass** [comment]
@didkan yes baby! you are the best! thank you!

**Comment by didkan** [comment]
@simonmaass 
:) No problem.
However this didn't completely solve my issue.
I think from reading some of the reports you also referenced in this issue there seems to be an issue where IOS reports to support INDEXEDDB but has a buggy implementation which could be another cause of this issue.
Anyhow, would be great to hear back if this solves or decreases your errors

**Comment by simonmaass** [comment]
i dont know if this is due to some updates in ios in mobile but the errors has increased quite a lot:

![image](https://user-images.githubusercontent.com/32599710/129063861-5c96abdd-1349-47c7-8075-66c2a9bee415.png)


![image](https://user-images.githubusercontent.com/32599710/129063983-dec342bd-f6a9-4b76-8894-175ea8fe4bd1.png)
