### ISSUE TITLE
Cannot run VSF after fresh installation.

### ISSUE THREAD

**Issue by supakornkim** [vuestorefront/vue-storefront#5494]
I follow instruction from https://docs.vuestorefront.io/v1/guide/cookbook/setup.html 
and successfully docker-compose up- d for every container as mentioned.

it is on CentOS Linux release 7.6.1810

(have problem with phantom.js and solve by edit DockerFile to install before another. add RUN npm install phantomjs-prebuilt to line number 9)

This is docker container ls
![image](https://user-images.githubusercontent.com/19331506/106972174-e593a500-6782-11eb-8364-ccce26692397.png)

I can access api, elasticsearch and kibana by input [server IP]:[port]
but cannot access vue-storefront_app  

![image](https://user-images.githubusercontent.com/19331506/106972261-170c7080-6783-11eb-9cf3-ea65746290c0.png)

This is docker-compose logs

![image](https://user-images.githubusercontent.com/19331506/106972697-ef69d800-6783-11eb-8ead-510ac3585c9b.png)

May I know what if i missing something.

Thanks

**Comment by Fifciu** [comment]
Hello @supakornkim 
The answer is on this screen: 
![image](https://user-images.githubusercontent.com/30155292/107028147-6f586800-67ad-11eb-9838-cf97ae397b55.png)

Look at `PORTS` column. Your App is not exposed to your network from container's network. Docker-compose logs suggest it works properly but it is just inaccessible for you. 

I believe you are using both network_mode host and port mapping. But network_mode is higher so has bigger priority, and it looks like your OS does not support it. Please remove `network_mode: host` from docker-compose.yml of your PWA. Bestly, use this docker-compose.yml: https://github.com/vuestorefront/vue-storefront/blob/develop/docker-compose.yml

**Comment by supakornkim** [comment]
Thank you so much. It works now.
![image](https://user-images.githubusercontent.com/19331506/107095578-a5dcc400-683b-11eb-8b0f-7e40b252ba02.png)

by the way, the document also show the result that no port mapping.
![image](https://user-images.githubusercontent.com/19331506/107095688-d290db80-683b-11eb-8916-28d66c321cb5.png)
