### ISSUE TITLE
when i restart my mac always i need to "yarn installer" again

### ISSUE THREAD

**Issue by Khuram007** [vuestorefront/vue-storefront#5499]
<img width="1552" alt="Screenshot 2021-02-05 at 9 53 37 PM" src="https://user-images.githubusercontent.com/36439994/107064022-dfdaa580-67fc-11eb-81cb-a09663eae88f.png">
i am using mac book pro 2015 with desktop app for docker
when i restart my laptop docker start but my project not running 
i also try this "npm run dev" for "vue-strorefront and vue-storefront-api" both project 
frontend runs successfully in localhost:3000
and backend at 8080 but not working my project always i need to run this cmd "yarn installer"
please help me what is issue

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
