### ISSUE TITLE
api/cart/update - API Call Failed

### ISSUE THREAD

**Issue by sundaramnavabrinit** [vuestorefront/vue-storefront#5506]
When adding items to the cart, I am getting this error. (Checked both in Development and Production Setup)
Cart was able to pull the data, but unable to update the same.

Anyone facing this issue? Any fix on how to resolve this?

![update_api_error](https://user-images.githubusercontent.com/77771217/107327897-e35b7e80-6ad3-11eb-800e-095d2009deb1.png)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
