### ISSUE TITLE
Login/Register infinity loading

### ISSUE THREAD

**Issue by lukaszjedrasik** [vuestorefront/vue-storefront#5508]
## Current behavior
After creating a second account with the same credentials or log in with wrong data we have an infinity loader and the `customerSignMeUp` request status all the time is `pending`

## Steps to reproduce the issue
1. Create an account
1. Logout
1. Create a second account with the same email / log in with the wrong credentials
1. You will see an infinity loader. After few minutes you have got Network Error

https://user-images.githubusercontent.com/40273258/107207973-3f090780-6a01-11eb-97ff-f859bc8a0fa3.mp4

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by Fifciu** [comment]
Just for readers' information. It is caused by not serving proper response if middleware's API Request gets other response than 200
