### ISSUE TITLE
[BUG] Cart: body scroll lock on desktop doesn't work

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/vue-storefront#5514]
## Current behavior
When on desktop with cart open the scrollbar for whole page is active and still scrolls when you finish scrolling cart content. Moreover clicking on scrollbar closes the cart.

![image](https://user-images.githubusercontent.com/32042425/107438577-fa7c8980-6b30-11eb-9a61-295931f07fb5.png)

## Expected behavior
Opening the cart should lock scroling whole page. 

## Steps to reproduce the issue
1. open the cart with items
1. scroll the content in the cart and see it still scrolls the overlayed page
1. click on scrollbar 

## Version of Vue Storefront

* [ ] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by gibkigonzo** [comment]
I tried to fix it here https://github.com/vuestorefront/vue-storefront/pull/5535 but I realized that its a deeper problem. I think `overflow-x:hidden` shouldn't be applied globaly. Instead it should be applied on components that create horizontal scroll. For example RelatedProducts (probably other components with SfCarousel).

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
