### ISSUE TITLE
[BUG] PLP bugs

### ISSUE THREAD

**Issue by justyna-13** [vuestorefront/vue-storefront#5515]
## Current behavior
1. Choosing others options on select doesn’t change anything on a page 

![Screenshot from 2021-02-10 07-25-12](https://user-images.githubusercontent.com/46591755/107476528-4ef62800-6b76-11eb-83fc-0905c2a7827a.png)

1. When filters are open page can be scrolled down - also on mobile
1. Menu on mobile bottom nav doesn’t work 
1. Chosen filter doesn’t show any product
1. Categories can’t be chosen on mobile
1. Pagination should have 2 arrows visible (even when it’s 1st page) - should be changed in SFUI
1. Pagination is too close to the border (when the first arrow is visible)

![Screenshot from 2021-02-10 07-30-30](https://user-images.githubusercontent.com/46591755/107476578-69300600-6b76-11eb-86d2-24f70eda71ae.png)

1. ‘All’ subcategory should show all available products in this category 

![Screenshot from 2021-02-10 07-32-23](https://user-images.githubusercontent.com/46591755/107476604-777e2200-6b76-11eb-89fb-5b2e9bca45fb.png)

1. Horizontal products - changing quantity of product doesn’t work
1. Pagination doesn't work properly - after 2nd click shows Page not found - wrong path

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
