### ISSUE TITLE
Logged in second account after registration and refresh

### ISSUE THREAD

**Issue by lukaszjedrasik** [vuestorefront/vue-storefront#5516]
## Current behavior
When you have created a second account with credentials that already exist, after refresh you are logged in.

## Steps to reproduce the issue
1. Create an account
1. Logout
1. Create a second account with the same credentials
1. You are logged in on the first account

https://user-images.githubusercontent.com/40273258/107480435-e2caf280-6b7c-11eb-9cae-d5bf0ae0ee6b.mp4

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by davevh** [comment]
Any news on this ?
