### ISSUE TITLE
[BUG] Cart: more button on mobile doesn't work 

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/vue-storefront#5517]
## Current behavior
When on mobile click on "more" button and see no effect. 
![image](https://user-images.githubusercontent.com/32042425/107482917-a13c4680-6b80-11eb-994a-e05171af9a7d.png)

## Expected behavior
Click on more button should show the dropdown list or there should be no button at all.

## Steps to reproduce the issue
1. go to cart on mobile 
1. click in any item "more" button 

## Version of Vue Storefront

* [ ] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
