### ISSUE TITLE
[BUG] Cart: mobile view of product not adjusted to figma design

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/vue-storefront#5519]
## Current behavior
On mobile view product card looks different than in figma design:
![image](https://user-images.githubusercontent.com/32042425/107488940-5aeae580-6b88-11eb-9b63-630d4e33c9e7.png)

Figma design:
![image](https://user-images.githubusercontent.com/32042425/107488999-68a06b00-6b88-11eb-8ec7-2ee04bbb42ac.png)

## Expected behavior
Action buttons (size, color) should be justified vertically and "Remove" link should stick to the image on the left, not right edge.

## Steps to reproduce the issue
1. go to the cart and turn to mobile view
1. see cards of products added to cart

## Version of Vue Storefront

* [ ] Vue Storefront
* [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

* [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
* [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
* [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

* Browser: 
* OS: 
* Node: 
* Code Version:

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
