### ISSUE TITLE
[BUG] My Profile

### ISSUE THREAD

**Issue by filipsobol** [vuestorefront/vue-storefront#5520]
1. `My Profile > Personal data` - no notification when the request is pending, successful, or failed.
1. `My Profile > Password change` - no notification when the request is pending, successful, or failed. The form should not be cleared when the request fails.
1. `Shipping details` and `Billing details`
  * No notification when addresses could not be loaded.
  * No notification when address was successfully added.
  * No notification when adding address failed. App should not redirect to address list or clear the form when this happens.
  * No pagination.
  * "Default" address is not highlighted on the list.
1. `Order history > My orders`
  * No notification when order list could not be loaded.
  * `Start shopping` button (visible when there are no orders) is not working.
  * No pagination.
1. `Order history > Returns` - throws console errors when opened
1. Some functionalities are not implemented. Maybe we should delete them, as they provide no benefit?
  * `Loyalty card`
  * `My newsetter`
  * `My reviews`

## Version of Vue Storefront
* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [x] YES
* [ ] NO

**Comment by Baroshem** [comment]
@filipsobol Newsletter functionality -> https://github.com/vuestorefront/vue-storefront/pull/5601

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
