### ISSUE TITLE
vue-storefront-api.sh: not found

### ISSUE THREAD

**Issue by CosmicSnow** [vuestorefront/vue-storefront#5525]
Hi, I am trying to run the complete project to test it out, understand how to use, etc.
But, I am having lots of trouble to run it, I don't know why it is happening.

I am following the tutorial at:
https://docs.vuestorefront.io/v1/guide/cookbook/setup.html#_0-introduction

I do know docker, so I selected the docker tutorial, everything runs fine until the initialization of `vue-storefront-api_app`, 
if won't find the .sh file, but the image should have it right?
![image](https://user-images.githubusercontent.com/59381242/107732248-aa3f2c00-6cd6-11eb-821f-8a1282f9a065.png)

I don't know if the docker install method isn't updated or if it's something with me or my machine.

can someone please help me with the correct directions? or point me if the docs aren't updated?
Thanks in advance! :)

**Comment by Stanislavsky69** [comment]
actual 
![image](https://user-images.githubusercontent.com/22763118/108961535-8c83a680-7688-11eb-93ed-1dee413e17ed.png)
