### ISSUE TITLE
Integration with Magetno 2

### ISSUE THREAD

**Issue by shreyas-1997** [vuestorefront/vue-storefront#5529]
![image](https://user-images.githubusercontent.com/66195578/107771680-1d8d8000-6d61-11eb-9d67-891e33fb9607.png)
Hello Friends i am trying to connect vuestorefront to my magento 2 instance which is hosted on AWS lightsail
after running yarn installer and fill the magento 2 api keys and all than i am stuck in Validating Magento integration configaration ... as you can see in the image below. i waited for almost more than a hour but still it is moving furthur.What can be the issue please help me!

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
