### ISSUE TITLE
[BUG] PDP with JS disabled issues

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/vue-storefront#5536]
## Current behavior
When JS is disabled on PDP: 

- tabs in product info doesn't work and don't look good on mobile
- the carousel is broken 
- the fonts doesn't load 
- banner grid is broken on mobile

  
![image](https://user-images.githubusercontent.com/32042425/107804258-f84e4100-6d63-11eb-8f8f-b46b9e0a400f.png)

![image](https://user-images.githubusercontent.com/32042425/107804374-1caa1d80-6d64-11eb-8ada-47183d56f1e5.png)
 
![image](https://user-images.githubusercontent.com/32042425/107804457-33e90b00-6d64-11eb-9267-119b9e5c3929.png)

![image](https://user-images.githubusercontent.com/32042425/107804610-5d099b80-6d64-11eb-9d04-34fab9483df6.png)

## Expected behavior
All that should work without JS. 

## Steps to reproduce the issue
1. Go to PDP on VSF demo
2. turn off JS
3. try it on mobile and desktop

## Version of Vue Storefront

- [ ] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
