### ISSUE TITLE
VSF Next CMS integration requires use of `useRawSource`

### ISSUE THREAD

**Issue by mike183** [vuestorefront/vue-storefront#5543]
I've created a [CMS integration for LexasCMS/VSF Next](https://github.com/LexasCMS/vsf-next-lexascms) but am seeing an issue which means that users need to add `vsf-lexascms` to the `@vue-storefront/nuxt` modules `useRawSource` option.

Having spoke to @filrak on Slack, it seems like there could be a bug somewhere.

## Current behavior
If users do not add `vsf-lexascms` to the `useRawSource` option as described above, the below error is produced:

![image](https://user-images.githubusercontent.com/892020/107952814-2913bd80-6f92-11eb-9c2a-c4a58a758ec4.png)

## Expected behavior
Users should be able to install the module without needing to add it to the `useRawSource` configuration.

## Steps to reproduce the issue
1. Clone demo repo (https://github.com/mike183/vsf-next-raw-source-issue-demo)
2. Run `yarn install`
3. Run `yarn dev`
4. Load homepage to see error (http://localhost:3000)

Uncommenting lines `63` and `68` of the `nuxt.config.js` file then makes the error disappear.

## Version of Vue Storefront
- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
- [ ] YES
- [x] NO

## Environment details
- Browser: Chrome v88.0.4324.150
- OS: macOS Mojave 10.14.6
- Node: v12.14.0
- Code Version: next

**Comment by filrak** [comment]
After discussions we concluded that it has to remain like this for now as we can't consume raw ES modules without doing this.
