### ISSUE TITLE
Category.name not working in site search

### ISSUE THREAD

**Issue by clinton-origin** [vuestorefront/vue-storefront#5545]
## Current behavior
Searching for a category name does not show products that are linked to this category.

## Expected behavior
When searching for a category name it should show at the very least all products within that category

## Steps to reproduce the issue
Go to the test site under the gear category https://next.storefrontcloud.io/gear.html then search for the word gear in the search bar. You will only see 2 products in the search whereas the category has 34 products.

## Version of Vue Storefront
- [X] Vue Storefront
- [X] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [X ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [X] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Additional information

I have tried to track down the issue but with not much luck. If I set the only search attribute to category.name nothing is returned which leads me to think there is an issue with the API handling child nodes. Setting the attribute to any parent category returns results as expected.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
