### ISSUE TITLE
Infinite loading on user login with invalid credentials

### ISSUE THREAD

**Issue by krskibin** [vuestorefront/vue-storefront#5546]
## Current behavior

After providing invalid user's credentials in login form and clicking "login" button the loading takes an infinite time. The only way to stop the action is to reload the page.

## Expected behavior

After clicking "login" button with invalid user's credentials, the loading should disappear and there should be a notification about invalid user's data and no possibility to log in.

## Steps to reproduce the issue
Page: https://vsf-next-demo.storefrontcloud.io/
1. Click profile icon on top navbar
2. Change form to login form by clicking the "login in to your account" link
3. Fill the form with invalid credentials (but there should meet all input validation requirements)
4. Click "login" button

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: all
- OS: all
- Node: all
- Code Version: 1.1.x

## Additional information
The problem is probably with the Commerectools API client. It generates Apollo settings (`ApolloLink` object) using `ApolloLink.from()` function which takes an `errorRetry` object that contains `handleRetry` function which throws error when is checking for `error.result.message`. The error is not handled and causes that the response never returns any feedback. Adding error handler there should resolve the issue. The problem probably might occur in any other crucial parts of the application, so it very important to fix it quickly and give it the hight priority.

**Comment by krskibin** [comment]
We also noticed a problem with this during registration when you provide an existing email address and in other places where CT returns 400 in response, so it's very urgent for us to fix it as soon as possible.

**Comment by andrzejewsky** [comment]
@krskibin 
you always have access to the error property of a given composable and function that is being called:

```js
const { user, login, error } = useUser();

login()
error.value.login  // error for login is here
```

Clearly, you couldn't read this as there was an issue with triggering the re-try strategy (as you mention) - but just fixed that.
