### ISSUE TITLE
Types in config file

### ISSUE THREAD

**Issue by PawFV** [vuestorefront/vue-storefront#5550]
## What is the motivation for adding / enhancing this feature?
Currently 'config' package + VSF config types are not typed in TS, 'config' comes with it's own types which can be installed, but it will throw errors when using it with VSF default.json types. pr #5551

**Results inside the IDE:** 
![image](https://user-images.githubusercontent.com/44122984/108224905-ae86a180-713b-11eb-99f4-dab76783106c.png)
![image](https://user-images.githubusercontent.com/44122984/108224913-b1819200-713b-11eb-8045-f701099043c4.png)

When I finished typing it threw some descriptive type errors.
**Errors found:**
![image](https://user-images.githubusercontent.com/44122984/108224821-9a42a480-713b-11eb-885b-b4328cc7d28b.png)

## What are the acceptance criteria 

- [ ] Be able to use 'config' types along with VSF custom types

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you complete this feature request by yourself?

- [] YES
- [x] NO

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
