### ISSUE TITLE
Error while install vue storefront on local with magento

### ISSUE THREAD

**Issue by himanshutecstub** [vuestorefront/vue-storefront#5558]
Install Magento 2 on localhost in linux server and also configure redis and elasticsearch on local linux
Than start to install vue storefront in local as https://medium.com/the-vue-storefront-journal/vue-storefront-how-to-install-and-integrate-with-magento2-227767dd65b2
During installation i got error as below
`Recreating 344175b8781a_vue-storefront-api_redis_1 ... error
ERROR: for 344175b8781a_vue-storefront-api_redis_1  Cannot start service redis: driver failed programming external connectivity on endpoint vue-storefront-api_rRecreating 02ab57906257_elasticsearch              ... error
 starting userland proxy: listen tcp4 0.0.0.0:6379: bind: address already in use`
installation process there is no option for change port.
When i try to change `vue-storefront-api/docker-compose.yml` file during installation than installation process stuck on below process 

```
Removing elasticsearch
Removing vue-storefront-api_redis_1
Starting 02ab57906257_elasticsearch              ... done
Starting 344175b8781a_vue-storefront-api_redis_1 ... done
Starting vue-storefront-api_kibana_1             ... done

Importing data from Magento into ElasticSearch... 
```

in install.log file got error as `Cannot read property 'attribute_id' of null`

Please suggest for installation process

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
