### ISSUE TITLE
Want to add data from graphql

### ISSUE THREAD

**Issue by himanshutecstub** [vuestorefront/vue-storefront#5572]
Hello,

I installed vue storefront with demo store URL where i try to add data using graphql apollo client.

I already configure uri (graphql endpoint) which is set in `core/scripts/resolvers/resolveGraphQL.js` file is fine. also check `core/app.ts` where call that apolloProvider so no need to extra configuration.

in category (`src/themes/default/pages/Category.vue`) page i updated code for get data from API as below

````
<template>
  <div id="category">
    ...
          <product-listing v-else :columns="defaultColumn" :products="getCategoryProducts" />
        	<store-item v-for="store in stores" :key="store.id" :store="store"></store-item>
    ...
  </div>
</template>

<script>
...
import StoreItem from "../components/core/blocks/Category/StoreItem.vue";
import gql from "graphql-tag";
...
export default {
  components: {
    ...
    StoreItem
  },
  data () {
    return {
      ...
      stores: []
    }
  },
  apollo: {
    stores: {
      query: gql`
        query getStores {
          stores {
            id
            title
            location
            name
            person
          }
        }
      `
    }
  }
}
</script>
```` 

When i add data in `stores: []` than it's working but can't get from API.
Suggest me for that.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
