### ISSUE TITLE
Problem with filters query after upgrading CT useFacets to version 1.1.4

### ISSUE THREAD

**Issue by krskibin** [vuestorefront/vue-storefront#5575]
## Current behavior

useFacets package shows an error after an upgrade related to the category facet after upgrading to version 1.1.4

```
Malformed parameter: filter.query: Syntax error while parsing 'categories.id: substree("b2c529b5-7ad2-4248-86ac-c785ec6236b3")'. Invalid input 's', expected 't' (line 1, column 19):
categories.id: substree("b2c529b5-7ad2-4248-86ac-c785ec6236b3")
```

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

**Comment by andrzejewsky** [comment]
fixed here: https://github.com/vuestorefront/enterprise-packages/pull/63
