### ISSUE TITLE
Is it possible to use https://vitejs.dev/ for this project?

### ISSUE THREAD

**Issue by NicolasHofmairT23** [vuestorefront/vue-storefront#5582]
## What is the motivation for adding / enhancing this feature?
Server Startup and HMR take quite long on bigger projects and a more fast way would improve DX a lot.

https://vitejs.dev/ seems to be the next gen devtools for fast project startup and HMR.
I was wondering if you considered using this with VSF to improve DX?
I am not sure what the requirements are to use it and if its possible to make it work for an exisiting setup but maybe somebody knows it and can tell if its possible for VSF.

## What are the acceptance criteria 
- [ ] Vite is used in VSF

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

**Comment by Fifciu** [comment]
No, it is not possible for now without a huge effort. In VSF2, we will probably provide Vite support but not in VSF1.

To improve your development build time look at: https://github.com/vuestorefront/vue-storefront/pull/5690
