### ISSUE TITLE
vsf init shows only 'commercetools' option

### ISSUE THREAD

**Issue by Nocturnal-2** [vuestorefront/vue-storefront#5605]
## Current behavior

Running `vsf init vue-storefront ` doesn't show the options are specified in the documentation. It shows 'commercetools' as the only option

```
superadmin@superadmin-Inspiron-7537:~/workspace/vue/test2/vue-storefront$ vsf init vue-storefront
? Choose integration commercetools
```
Screenshot:

![Screenshot from 2021-03-02 16-13-49](https://user-images.githubusercontent.com/38354898/109675683-4b9ffc00-7b78-11eb-9697-a5dc6e2a3d59.png)

## Expected behavior

As per the documentation it should show the following
 
```
dex@ubuntu:~/code$ vsf init vue-storefront
  ✔ Check avalilable versions
? Which version of Vue Storefront you'd like to install? (Use arrow keys)
❯ Stable versions (recommended for production) 
  Release Candidates 
  In development branches (could be unstable!)
```

Screenshot from the documentation:

![Screenshot from 2021-03-02 16-57-29](https://user-images.githubusercontent.com/38354898/109675824-6bcfbb00-7b78-11eb-8134-4f2462b11dd9.png)

Link to documentation:
https://docs.vuestorefront.io/v1/guide/cookbook/setup.html#_2-recipe

## Steps to reproduce the issue

Run `vsf init vue-storefront ` with latest code from 'main' branch

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: NA
- OS: Ubuntu 20.04.2 LTS
- Node: 11.15.0
- Code Version: v1.12.2

**Comment by Fifciu** [comment]
It looks exactly as it supposed to for VSF Next CLI

**Comment by Braincoke** [comment]
For other people like me who encountered this issue.
As stated by Nocturnal-2, in the [documentation](https://docs.vuestorefront.io/v1/guide/cookbook/setup.html#_2-recipe) for vue-storefront V1 the steps are different from what we actually get now.

It appears that by default the cli for @next is downloaded. To avoid this, specify the version:

```bash
npx @vue-storefront/cli@0.2.1 init vue-storefront
```

I believe this answers the original question.
