### ISSUE TITLE
Adyen integration

### ISSUE THREAD

**Issue by OrionDev418** [vuestorefront/vue-storefront#5609]
# I want to integrate Adyen
I checked the following url.
https://github.com/commercetools/commercetools-adyen-integration/blob/master/extension/docs/WebComponentsIntegrationGuide.md#validate-payment
In order to integrate adyen on vue-stroefront, need to build and use custom backend api?

**Comment by andrzejewsky** [comment]
Hey, @OrionDev418 we currently work on this, that will be a part of our enterprise features.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.

**Comment by bloodf** [comment]
@OrionDev418 we have the Adyen integration as part of the enterprise package as you can check under https://www.vuestorefront.io/technology-partners/payments
