### ISSUE TITLE
Register function from CT useUser composable allows user to log in.

### ISSUE THREAD

**Issue by krskibin** [vuestorefront/vue-storefront#5613]
## Current behavior
During the registration when the user provides an email address that already exists the API returns an error related to an already existing email and then tries to reach the token auth endpoint. As a result, a bad error message is returned and if the user provides a correct password for the existing email address the registration form allows them to log in.

## Expected behavior
After providing the already existing email address the composable should return the correct error and stop any further actions.

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

**Comment by filrak** [comment]
Backport to 1.1.x is coming latest on Monday ;)

**Comment by Baroshem** [comment]
Fix to this problem is available in the following PR -> https://github.com/vuestorefront/vue-storefront/pull/5653

**Comment by krskibin** [comment]
Hey!
I added a comment to the PR. Because of that error with `!response.errors.length`, in version 1.1.6, there's no possibility to register a user.

**Comment by andrzejewsky** [comment]
@krskibin hey, this fix was released, please use the latest version, thanks for reporting!
