### ISSUE TITLE
[VSF1] A feature for canceling the order during the order processing

### ISSUE THREAD

**Issue by kkdg** [vuestorefront/vue-storefront#5615]
# Summary
[summary]: #summary

A customer may cancel the order he/she made, from `My Orders` in `My Account` before the order is fulfilled.

# Motivation
[motivation]: #motivation

I think this  is one crucial feature for the order process. Was a little shocked to see there was none for it.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation
- Customer Order Cancel 
- A customer may cancel their orders from `My Orders` page whose order status is not in `complete` 
- This might improve general UX for general customers since otherwise they wouldn't have any means to cancel their orders except phone calls. 
- This might add additional http requests for backend communication which should be implemented across `vue-storefront`, `vue-storefront-api`, and backend server (possibly Magento 2 for example) altogether.

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation
- This feature involves a quite heavy development across the whole infra. 
- This feature is normally popular, and implemented in all the other solutions so the majority and  the consensus over how this should be implemented is rather clear.

# Drawbacks
[drawbacks]: #drawbacks

I don't see any.

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

Not relatable.

# Prior art
[prior-art]: #prior-art

This is clear as fire all the other platforms employ this feature and in my personal opinion, no customers today can imagine this is not supported on their merchant shops.

# Unresolved questions
[unresolved-questions]: #unresolved-questions

I will find them out

# Future possibilities
[future-possibilities]: #future-possibilities

I think generally after-checkout-support should be implemented in VSF OOTB

**Comment by kkdg** [comment]
My team (3rd party)  is working on this feature. We will make a PR after it's complete with various tests.

**Comment by filrak** [comment]
Thanks Degi for your involvement! @Fifciu do you have anything to add here :)

**Comment by Fifciu** [comment]
Nope. Can't wait to see the PR :D

**Comment by kkdg** [comment]
It will be up in around May (working hard!)

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
