### ISSUE TITLE
Using options in Nuxt.js plugins

### ISSUE THREAD

**Issue by filipsobol** [vuestorefront/vue-storefront#5619]
Consider using `<%= serialize(options) %>` in all Nuxt.js plugins instead of `JSON.parse('<%= JSON.stringify(options) %>')`.

Please see PR comment from @Fifciu discussing this https://github.com/vuestorefront/vue-storefront/pull/5611/files/e8360180a4cb895cde5f4756529b8828e4aabd4a#r587316456

Remember to also update the docs.

## Version of Vue Storefront
- [ ] Vue Storefront
- [X] Vue Storefront Next

## Can you complete this feature request by yourself?

- [X] YES
- [ ] NO

**Comment by Fifciu** [comment]
Clarification: https://github.com/nuxt-community/community-modules/issues/170#issuecomment-346764312
