### ISSUE TITLE
Allow user to add billing or shipping address during the registration [CT]

### ISSUE THREAD

**Issue by krskibin** [vuestorefront/vue-storefront#5629]
## What is the motivation for adding / enhancing this feature?

Commercetools API allows the user to add a shipping and billing address during registration. However, the `@vuestorefront / commercetools` package in the `useUser` composable doesn't allow that. It would be a good idea not to block this option and allow users to add addresses during registration.

## What are the acceptance criteria 

* [ ] As a developer I want to be able to send to the CT a user address provided during the registration
* [ ] As a developer I want to be able set that address as the default one

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you complete this feature request by yourself?
* [ x] YES
* [ ] NO

## Additional information
`useUser `  composable can only accept firstName, lastName, email and password parameters - it should be extended also by optional address object within that you will be albe to define whether the address is the default or not.

**Comment by filrak** [comment]
Hey!

I think it ss possible right now just by using `useuserBilling` and `useUserShipping`. You can fill in the addresss forms and use the above compostables right after the registration action in the same page.

**Comment by krskibin** [comment]
Hi,
Indeed, We are currently using `useUserBilling` and `useUserShipping` right after the user register call. This solution is not optimal for us, especially when you could do that with just one query. As you mentioned, we could write a custom query for that, but the `useUser` composable is the very only one that not allows developers to override it. I would be grateful if you will allow passing the address or `customQuery` to the user register composable function.

**Comment by andrzejewsky** [comment]
seems like support for custom queries in useUser is needed here. I'm adding this to our backlog
