### ISSUE TITLE
Problems with global state in SSR during concurrently requests from different stores

### ISSUE THREAD

**Issue by cewald** [vuestorefront/vue-storefront#5639]
## Current behavior

I'm using a multistore environment and experience the following issue with parallel requests: if I request the same site in multiple stores at the same time I get 404 errors or even SSR exceptions because of a undefined/wrong store-code. Means one request seems to overwrite another. I’m using shared instances and not running store-view-dedicated nodes.

The more parallel requests I have, logs like this are appearing: `[dispatcher] Route not found de-fi-category null`  – you can see the duplicate store-code in the route-name, I guess thats wrong. But I also get exceptions like `SSR Exception: Cannot read property 'i18n' of undefined`.

This might be related to a [stateful-singelton](https://ssr.vuejs.org/guide/structure.html#avoid-stateful-singletons) where the Vuex state is global and reused by multiple requests. 

I already briefly introduced this problem in Slack to @gibkigonzo @Fifciu and got the hint that there was a similliar problem with the `device` module (#5321). And as visible in the `currentStoreView` and `prepareStoreView` methods the current store is saved inside a global variable which might lead into this problem as its a global and reused.

I'll will have a look into the solution for the device-module and try to fix it but any help and tips are appreciated.

At last, here is a good blog-post about [global state in SSR](https://medium.com/js-dojo/global-state-mutations-in-ssr-with-vue-and-node-js-97541cd1e79c).

## Expected behavior

Each request should have it's own store-code and store-view.

## Steps to reproduce the issue

I've run an [Artillery stress-test](https://artillery.io/) against the same URL and different stores and watch inside the logs of the running VSF. Then I  can see the error above and see that the categories randomly lead into 404 errors. 

This is my Artillery test:
```yaml
config:
  target: http://localhost:3000
  phases:
    - duration: 10
      arrivalCount: 100
  variables:
    storecode:
      - de
      - it
    category:
      - category-url-path.html
scenarios:
  - flow:
      - get:
          url: "/{{ storecode }}/{{ category }}"
```

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES (I try)
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Any (SSR issue)
- OS: Ubuntu LTS
- Node: Node 14 LTS
- Code Version: v1.12.2 (latest `develop`: c4ddf1e16dd3e1ba2550c88e18fdb33b43bd5928)

**Comment by didkan** [comment]
I had the same issue with a multistore environment.
I "fixed" it by commenting out the use of `global` in `core/lib/multistore.ts`:
```
...
export function currentStoreView (): StoreView {
  return rootStore.state.storeView
  // const serverStoreView = get(global, 'process.storeView', undefined)
  // const clientStoreView = get(rootStore, 'state.storeView', undefined)
  // return (isServer ? serverStoreView : clientStoreView) || buildBaseStoreView()
}

export async function prepareStoreView (storeCode: string): Promise<StoreView> {
  let storeView: StoreView = buildBaseStoreView() // current, default store

  if (config.storeViews.multistore === true) {
    storeView.storeCode = storeCode || config.defaultStoreCode || ''
  } else {
    storeView.storeCode = storeCode || ''
  }

  const storeViewHasChanged = !rootStore.state.storeView || rootStore.state.storeView.storeCode !== storeCode

  if (storeView.storeCode && config.storeViews.multistore === true && config.storeViews[storeView.storeCode]) {
    storeView = merge(storeView, getExtendedStoreviewConfig(config.storeViews[storeView.storeCode]))
  }
  rootStore.state.user.current_storecode = storeView.storeCode

  if (storeViewHasChanged) {
    storeView = coreHooksExecutors.beforeStoreViewChanged(storeView)
    rootStore.state.storeView = storeView

    // if (global && isServer) {
    //   (global.process as any).storeView = storeView
    // }

    await loadLanguageAsync(storeView.i18n.defaultLocale)
  }
  if (storeViewHasChanged || StorageManager.currentStoreCode !== storeCode) {
    initializeSyncTaskStorage()
    StorageManager.currentStoreCode = storeView.storeCode
  }
  coreHooksExecutors.afterStoreViewChanged(storeView)

  return storeView
}
...
```

**Comment by cewald** [comment]
@didkan Thanks, I tried to test it as good as I could and your solution seems straight forward and working. If I see it correctly we don't need to put the store-view inside a global. This is, as mentioned above, the reason for the conflict between multiple requests as it is the same variable for the whole process not the request instance. Also the `rootStore` is unique for each request as it is created in `createApp` during server- or client-entry. Bottom line: we don't even need to attach it directly to the Vue instance, like in the solution for the device module, as long as the `rootState` is enough. @gibkigonzo WDYT – just remove the global?

**Comment by didkan** [comment]
@cewald Just note that I also commented out the use of `buildBaseStoreView()`.
We never use the "default storeview" because all our domains have the `x-vs-store-code` header set via nginx proxy.
So probably `currentStoreView ()` should be something like:
```
export function currentStoreView (): StoreView {
  // const serverStoreView = get(global, 'process.storeView', undefined)
  const clientStoreView = get(rootStore, 'state.storeView', undefined)
  return clientStoreView || buildBaseStoreView()
}
```

**Comment by gibkigonzo** [comment]
@cewald @didkan Thanks for checking this issue. This solution with `global` was a mistake. It's shared state in global. Can you make a pr only with access to storeView from vuex store?
