### ISSUE TITLE
How to add a global style file (not in vue file) in webpack ? 

### ISSUE THREAD

**Issue by Stanislavsky69** [vuestorefront/vue-storefront#5641]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [ ] A brief description of the problem,
- [ ] Where the problem is occurring,
- [ ] The length of time the problem has been occurring,
- [ ] The size of the problem.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
