### ISSUE TITLE
Register and login don't working in version2.2.3

### ISSUE THREAD

**Issue by OrionDev418** [vuestorefront/vue-storefront#5657]
## Current behavior

When register and login, graphql api `operationName: "customerSignMeUp", "customerSignMeIn"` are successfull, but 2 console errors occurs,
![bug](https://firebasestorage.googleapis.com/v0/b/terapiapp-7a469.appspot.com/o/images%2FScreenshot_1.png?alt=media&token=363098f3-15f9-49f2-b2c0-120b110ad322)

## Version of Vue Storefront
- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: Chrome
- OS: Windows
- Node: 14.16.0
- Code Version: 2.2.3

**Comment by andrzejewsky** [comment]
seems like it's connected: https://github.com/vuestorefront/vue-storefront/issues/5613 - we have fixed that, please use version 1.1.1 of comemrcetools packages
