### ISSUE TITLE
Browser caching and releasing new version of vsf

### ISSUE THREAD

**Issue by cszczotka** [vuestorefront/vue-storefront#5668]
Hi,
Do you know how to deal with the situation where I have on production vsf in version 1.10.4 which is cached by the customer browsers. Then I release a new version of vsf 1.12.2. How do I force  customer browsers to load a new version of vsf ? Does vsf support something like that ? I see that is hash addded in webpack config 
output: {
...
    filename: '[name].[hash].js'
  },
but I'm not sure if it help. Can you advise ?
Thanks

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
