### ISSUE TITLE
Add guideline how to code in the next branch

### ISSUE THREAD

**Issue by harrytran998** [vuestorefront/vue-storefront#5680]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io.

# Is there something you don't understand? What is it? Describe it.	

I clone the next-branch of this and discover it with my highest interest, but I don't know how to code this project with the error below. Hope you guys can share this!

```
Cannot find module '@vue-storefront/core' or its corresponding type declarations
```

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [x] A brief description of the problem,
- [x] Where the problem is occurring,

## Additional information

![image](https://user-images.githubusercontent.com/24296018/111673369-7ca54f80-884d-11eb-82c9-3e60bb8f745e.png)

**Comment by andrzejewsky** [comment]
Seems like you want to run commercetools, please follow those commands:
- `yarn` - for install all of dependencies
- `yarn build:ct:tools` - for building core along with commercetools libraries
- `yar dev:ct` - that will run the development mode in the nuxt theme of comemrcetools

now it should work fine

**Comment by harrytran998** [comment]
Thank you so much <3. Hope you can add this to the guideline of the project, maybe it helps a lot of people!
