### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by mariusa** [vuestorefront/vue-storefront#5683]
There's no Discuss section, so opening a feature request to support Vue 3 (instead of current Vue 2).
Clearly the deps (eg vue-multiselect) would have to support Vue 3 first.

**Comment by andrzejewsky** [comment]
hey @mariusa we support Vue 3 (plugin at this moment) for Vue Storefront Next - you can find it on branch `next` - we don't plan to use Vue 3 in Vue Storefront 1.x (@Fifciu can you confirm?)

**Comment by mariusa** [comment]
Perfect, thanks. No need to invest more in 1.x.

If so, could this be changed to vue 3?
packages/core/core/package.json:    "vue": "^2.6.11",
(in `next` branch)

**Comment by Fifciu** [comment]
No, it couldn't.
VSF Next is based on Nuxt. Nuxt still did not release version 3 (with Vue 3 support). So we are using @nuxtjs composition API plugin to make future jump to the nuxt3 painless.

**Comment by mariusa** [comment]
Thanks for clarification

**Comment by PawFV** [comment]
I think this is probably shooting yourself in the head, Vue 3 is still a green product. VSF is a newly tech, so making a new tech based on a new tech isn't going to happen. 

I think the best thing you can do is just use the most stable/supported and well known version of a product, a few new cool features isn't going to add value to the product for the high cost of implementation they take.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
