### ISSUE TITLE
[next] Adding to cart should popup cart

### ISSUE THREAD

**Issue by mariusa** [vuestorefront/vue-storefront#5702]
When adding a product to cart now, the only indicator that it worked is cart icon having (1) qty symbol added. If that's in the current view, which usually isn't (one scrolled down to look at the product)

## What are the acceptance criteria 
Make it obvious for customers that add to cart worked.

## Additional information

Proposal: 
* Adding to cart should popup cart
* popup cart should have a "Continue shopping" button under Checkout, which simply closes the popup (same as X in top-right)

OR

* small popup which auto-hides in secods, see https://demo.vendure.io/storefront/product/skipping-rope

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
