### ISSUE TITLE
[next] Font zoom at 125% pushes cart icon half out of screen

### ISSUE THREAD

**Issue by mariusa** [vuestorefront/vue-storefront#5703]
## Current behavior

Font zoom at 125% pushes cart icon half out of screen

## Steps to reproduce the issue

Set font zoom at 125% 
![2021-03-24_10-43](https://user-images.githubusercontent.com/1283842/112280713-fa25f100-8c8d-11eb-8d19-a2c54a677694.png)

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

Local demo of current `next` tree

## Environment details

- Browser: Chrome

## Additional information

Layout should be more flexible and work properly with larger fonts.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
