### ISSUE TITLE
[next] links don't work in local demo landing page

### ISSUE THREAD

**Issue by mariusa** [vuestorefront/vue-storefront#5704]
## Current behavior

I know `next` demo is WIP, but think this is worth reporting.

Except collections, no other links at http://192.168.1.171:3000/ work: Learn more, Shop now, Match with click on product, Subscribe, Footer links.

## Expected behavior

As a potential VSF (next) user, I'd like to see a working demo.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
