### ISSUE TITLE
Products in multiple tabs crashing during cart interactions (using tab-cart-sync)

### ISSUE THREAD

**Issue by cewald** [vuestorefront/vue-storefront#5719]
## Current behavior

I recently made a bugfix for the multi-tab cart-sync (#5711) and stumbled about the following bug:  
If I open around 8 products from CLP in separat tabs and walk through this products and add them to cart after another, then – under Chrome – the tabs will freeze sooner or later or at least using an obscure amount of memory and CPU. This has a connection to the tabs-cart-sync using the storage window-event – if I disable this feature it won’t happen. There seems to be some kind of memory-leak or maybe one event calls the next mutation and causes an infinite loop. I can replicate this at our VSF but also at the VSF demo and others from the VSF showcase.

It only happens in Chrome and Chromium browsers on desktop environment – I can't trigger a crash on an iPad or iPhone either with mobile Chrome nor Safari.

Does anybody know something about this? Any help would be appreciated.

## Expected behavior

The windows shouldn't crash obviously – to solve it we might need to have a marker in the storage that prevents the local-storage update and with that the event for the other tabs until the changes at the cart are final.

## Steps to reproduce the issue

* Open a new Chrome window in private-mode
* Go to a category-list-page of the demo: https://demo.vuestorefront.io/women.html
* Open the 8 (or more) first products in new tabs
* Add the opened products after another to cart
* Now you should be able to watch the memory increase until the browser window crashes

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES (I try)
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [x] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 89.0.4389.90
- OS: Windows 10 and OSX
- Node: Each the same
- Code Version: `develop` 4dda6cc8dfd75cdde1524c1c533e826e8ad717aa

**Comment by anantsunny** [comment]
We are also facing same issue. Can we fix this?

**Comment by cewald** [comment]
Idk if anybody from VSF is looking into it. Some other memory-leaks forced me to stop my research – I'm trying to go back asap. If you have any new insights in the meantime let me know.
