### ISSUE TITLE
Next: entering category page in SSR break the app

### ISSUE THREAD

**Issue by AdamPawlinski** [vuestorefront/vue-storefront#5744]
## Current behavior
Connected with [EN-156](https://vsf.atlassian.net/browse/EN-156?atlOrigin=eyJpIjoiMmQxYWZiNDEzZjE1NDFlY2I3NTg3MmIzMGQ3YmNlMGUiLCJwIjoiaiJ9)
Entering category page shows error in console:
![image](https://user-images.githubusercontent.com/32042425/114173726-e6d67f00-9937-11eb-95da-77173f821127.png)

## Expected behavior
No error appearing.

## Steps to reproduce the issue
1. Enter https://demo-enterprise.europe-west1.gcp.storefrontcloud.io/c/women 
2. See the error in console  

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
