### ISSUE TITLE
Next: Algolia integration with Routing

### ISSUE THREAD

**Issue by ed42311** [vuestorefront/vue-storefront#5749]
## Current behavior

1. Started from: https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/vue/#combining-with-nuxtjs
2. Using: VueStorefront Next: https://github.com/vuestorefront/vue-storefront/tree/next
3. URL gets rewritten for a flash then render fires and goes back to original route

## Expected behavior

URL gets rewritten and back button works as well as in =>   https://github.com/ed42311/algolia-nuxt-routes 

## Steps to reproduce the issue
Minimal Repo: https://github.com/ed42311/algolia-vsf-routes

**To Repro:**
1. pull && yarn && yarn run dev
2. http://192.168.1.4:3000/ && go to /Search
3. URL gets rewritten for a flash then render fires and goes back to original route

**What I’ve tried:**
1. Built two repos in isolation and it seems to not be an issue with vanilla nuxt: https://github.com/ed42311/algolia-nuxt-routes 
2. Updated router handler based on @Haroenv 's suggestions:  https://github.com/algolia/vue-instantsearch/issues/916#issuecomment-817602414
3. Conditional used either search page directly or nuxt comp

## Version of Vue Storefront
- [ ] Vue Storefront
- [X] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details
- Browser: Version 1.22.71 Chromium: 89.0.4389.114 (Official Build) (x86_64)
- OS: MacOSX - 11.2.3
- Node: v15.5.1
- Code Version: https://github.com/vuestorefront/vue-storefront/tree/next

## Additional information
- hoping there is a better solution here, but maybe this is as good as any

**Comment by ed42311** [comment]
Okee this has something to do with the nuxt comp passing the route     `<nuxt :key="$route.fullPath"/>`

I was able to bypass it by doing this in the default template
```
    <div v-if="String($route.name) === 'Search___en'"><search/></div>
    <div v-else ><nuxt :key="$route.fullPath"/></div>
```

Basically bypassing the <nuxt /> comp with the key which was triggering a re-render because it uses the router under the hood... I'm guessing.

This is what eventually allowed me to use the integration code effectively: https://github.com/ed42311/algolia-vsf-routes/blob/main/layouts/default.vue#L11

I am however open to other suggestions

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
