### ISSUE TITLE
customQuery typings

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/vue-storefront#5754]
## What is the motivation for adding / enhancing this feature?

Add better typings for all occurences of customQuery.

## What are the acceptance criteria 

- [ ] ...

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
