### ISSUE TITLE
"provide" factory params function does not provide type inference.

### ISSUE THREAD

**Issue by vn-vlad** [vuestorefront/vue-storefront#5767]
## Current behavior
Usage of `provide` factory params function does not provide type inference in context argument for other factory params functions. ([composable dependencies](https://docs.vuestorefront.io/v2/integrate/integration-guide.html#composable-dependencies))

## Expected behavior
Usage of `provide` factory params function should provide type inference in context argument for other factory params functions.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
