### ISSUE TITLE
Enhance middleware to pass error's response code if available

### ISSUE THREAD

**Issue by Fifciu** [vuestorefront/vue-storefront#5790]
Enhance middleware to pass error's response code if available.

Currently, in `packages/core/middleware/src/createServer.ts` we have a part like:
```ts
try {
      const platformResponse = await apiFunction(...req.body);

      res.send(platformResponse);
} catch (error) {
      res.status(500);

      res.send(error);
}
```

Please check if we have some response code in error if so - set it to the response - otherwise set `500`

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
