### ISSUE TITLE
Test deployment on Vercel and create documentation for it.

### ISSUE THREAD

**Issue by filipsobol** [vuestorefront/vue-storefront#5797]
Someone on our Discord server tried to deploy the Shopify application to Vercel (Node 14), but it failed with the following error message:

![Vercel error message](https://user-images.githubusercontent.com/4145208/115831901-7db03a80-a412-11eb-848c-a1aedd95dd85.png)

It doesn't happen locally using the same Node version. It could have something to do with missing production dependency or `require` statements in Server Middleware.

**Once resolved, please create a tutorial on how to deploy VSF using Vercel.**

**Comment by aureate-labs-team** [comment]
We will look into this and back with the solution

**Comment by oscarmanderj** [comment]
Any temporary solution for this?

**Comment by giancarllorojas** [comment]
Any news on this? I'm trying to deploy on Vercel and I'm getting:
`FATAL  Cannot find module '/var/task/middleware.config.js'`

**Comment by filipsobol** [comment]
Unfortunately, Vercel only supports static and serverless applications. We will soon create deployment docs for other providers.
