### ISSUE TITLE
[RFC] Theme slices

### ISSUE THREAD

**Issue by andrzejewsky** [vuestorefront/vue-storefront#5816]
# Summary
[summary]: #summary

Better organization of themes and its extending in the integrations.

# Motivation
[motivation]: #motivation

We have theme inheritance from the core-level, that allows you to override any file/component in the integration. Unfortunately, that causes many issues, especially when it comes to redundant code across the themes. A very common scenario Is when some of the integrators cannot fit the UI to integration needs so he is forced to copy entire component to his theme and override it, even if he wants to change just a single line. 

That takes us to maintain a redundant code - what if we have a bug in that big component? Once we have a bug there, we need to fix that in both places: core theme and integration one.

Also, there is another issue - the developers don't know where certain component comes from, is that from the core? or from integration - they don't know until they look into the repositories.

# Introducing theme slices 
To solve that issues we can introduce a feature called "theme slices". That's not actually a new API but just a better organization of the components and pages. It assumes cut the page into small, granular slices. Each slice is a separate component that can be overridden in the integration theme. Depending on how big changes the integrator wants to introduce, he can pick which slice is for him.

### Slices
![image](https://user-images.githubusercontent.com/7943292/115901650-c216f700-a461-11eb-9565-229ad5375a13.png)

Considering this image, the integrator can pick which "slice" (part of the UI) he wants to override, which one is really custom for his case. Please notice you can select a really granular one eg. just price or something wider eg. entire product details.

From the core perspective, we can create a folder called "slices" and put each component there that can be easily overridden.

### Debuging
To improve the debugging process, for each slice (in development mode) we can add frames that on-hover will show you whether this slice is overridden and also what are the possible slices so the developer will be really aware of the origin of components.

# Drawbacks
[drawbacks]: #drawbacks

That feature needs quite a big refactor of the core theme.

# Future possibilities
[future-possibilities]: #future-possibilities

This feature will reduce the amount of work in terms of implementing any features in the UI along with code redundant issue - the developer will be able to override exactly that part of UI which is really needed, without forcing them to override everything.

**Comment by filrak** [comment]
Love the idea with frames :)
