### ISSUE TITLE
[FEATURE] Prestashop integration

### ISSUE THREAD

**Issue by lucmichalski** [vuestorefront/vue-storefront#5817]
Hi guys,

Hope you are all well !

I was wondering if a Prestashop integration was on your roadmap as I am really interested in.

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by sudarshann** [comment]
I would love to see this integration happening with prestashop

**Comment by lucmichalski** [comment]
this project is already dead by not replying ^^

**Comment by sudarshann** [comment]
[With Great Powers](https://www.vuestorefront.io/blog/vue-storefront-raises-1-5m-to-turn-the-fastest-growing-open-source-ecommerce-project-into-a-business) comes no responsibility or support for the community who made them possible.

**Comment by x0rzkov** [comment]
bullshit ! just not holding responsabilities

**Comment by x0rzkov** [comment]
1.5M$ is bullshit in the startup world

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
