### ISSUE TITLE
Fix ProductGetters type to not assume API return structure

### ISSUE THREAD

**Issue by filipsobol** [vuestorefront/vue-storefront#5844]
Currently, we assume that the `products` passed to `getAttributes` and `getFiltered` methods in `ProductGetters` is an array of `PRODUCT`, but the response from the API could be of any type. We should add a new generic to this interface that will define the structure of response.

https://github.com/vuestorefront/vue-storefront/blob/next/packages/core/core/src/types.ts#L503-L519

**Comment by skirianov** [comment]
Issue is closed. Reason: Too Old (>6 months)

---

Sergii Kirianov

Developer Advocate

Vue Storefront
