### ISSUE TITLE
create yarn scripts to publish packages in local registry

### ISSUE THREAD

**Issue by Baroshem** [vuestorefront/vue-storefront#5851]
## What is the motivation for adding / enhancing this feature?

create yarn scripts to publish packages in local registry

## What are the acceptance criteria 

- [ ] ...

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
