### ISSUE TITLE
vsf 1.12.2 product page to category page routing problem

### ISSUE THREAD

**Issue by nawafHinai** [vuestorefront/vue-storefront#5893]
## Current behavior

The current behavior is that when you navigate from product page to the category page using breadcrumbs or by clicking the back button on the browser, the app crashes and stop working due to DOM exception 

![image](https://user-images.githubusercontent.com/43580372/117552031-24731880-b05a-11eb-822b-5ba929c52f20.png)

## Expected behavior

The routing should work properly.

## Steps to reproduce the issue

I produced this bug using the latest vue-storefront and vue-storefront-api from master branches.

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ *] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by lukaszjedrasik** [comment]
@nawafHinai we have already released  v1.12.3 and I am not able to reproduce this issue. Could you recheck this one again, please?
