### ISSUE TITLE
Can't get products from commercetools

### ISSUE THREAD

**Issue by bootsmann1995** [vuestorefront/vue-storefront#5895]
## Current behavior

When i load my page with the code from the docs: 

```
  const { products, search } = useProduct()

    onSSR(async () => {
      await search({})
    })
    
    return {
      products
    }
  },
```

I don't get any producs, only an empty array.

I get this error:
![image](https://user-images.githubusercontent.com/65391517/117641670-baa45d00-b186-11eb-9680-80ba87711dff.png)

## Expected behavior

I want to fetch products simply by a function on Home.vue

## Version of Vue Storefront

* [ ] Vue Storefront
* [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?
* [ ] YES
* [x] NO

**Comment by filipsobol** [comment]
Hi,

The `search` method requires additional parameters, which vary depending on the integration you use. See [this page](https://docs.vuestorefront.io/v2/commercetools/composables/use-product.html#examples) for examples of how to use it in `commercetools`.

I will update ["Product Catalog" document](https://docs.vuestorefront.io/v2/guide/product-catalog.html#fetching-a-single-product-and-it-s-variants-with-useproduct) to better reflect that.

**Comment by filipsobol** [comment]
Update to Product Catalog - https://github.com/vuestorefront/vue-storefront/pull/5918
