### ISSUE TITLE
EventBus ssr memory leak

### ISSUE THREAD

**Issue by lukaszjedrasik** [vuestorefront/vue-storefront#5917]
## Current behavior

Something is holding on to the Vue instances created with each server request and it prevented GC, making VSF processes eat RAM and restart way too often.

## Expected behavior

- Change ```Vue.prototype.$bus.$on...``` -> 
```js
import EventBus from '@vue-storefront/core/compatibility/plugins/event-bus'

EventBus.$on...
```

- remove `EventBusPlugin`

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by didkan** [comment]
@lukaszjedrasik Thanks for adding the issue. I'll add some more context.

I found the issue when going through my custom code looking for potential memory leaks based on this issue: https://github.com/vuestorefront/vue-storefront/issues/1686.

My problem was that the `Vue.Prototype.$bus.$on(...)` registrations were done in a, custom, Vuex module in an `afterRegistration` hook. So there were no lifecycle hooks to `.$off` them with.

I found one similar use from a core module here:
https://github.com/vuestorefront/vue-storefront/blob/master/src/modules/google-analytics/index.ts#L35
(I'm not using the analytics module so I cannot confirm this would cause a memory leak, but the use is the same as I had in my custom modules).
