### ISSUE TITLE
How to get Custom Object with where condition? commercetools

### ISSUE THREAD

**Issue by muhammad-Usman85** [vuestorefront/vue-storefront#5931]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

# Can't find what you're looking for?

## Keep the problem description concise and include:
- [ ] A brief description of the problem,
- [ ] Where the problem is occurring,
- [ ] The length of time the problem has been occurring,
- [ ] The size of the problem.

**Comment by filipsobol** [comment]
Please create new issue that contains more information.
