### ISSUE TITLE
Cannot read property '__esModule' of undefined

### ISSUE THREAD

**Issue by haideritx** [vuestorefront/vue-storefront#5949]
## Current behavior
This error only appears in production mode when using it with `yarn && yarn build && yarn start`

Following is the error shown on pm2 logs, 
```
Cannot read property '__esModule' of undefined
```

```
2|server   | 2021-05-27 12:55:36: App HAVE BEEN initialized
2|server   | 2021-05-27 12:55:36: App HAVE BEEN initialized
2|server   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
2|server   | TypeError: Cannot read property '__esModule' of undefined
2|server   |     at Re (/home/haider/0_TM/1_vsfront/tilemoutain/vuestore/node_modules/vue/dist/vue.runtime.common.prod.js:6:24223)
2|server   |     at /home/haider/0_TM/1_vsfront/tilemoutain/vuestore/node_modules/vue/dist/vue.runtime.common.prod.js:6:21188
2|server   |     at /home/haider/0_TM/1_vsfront/tilemoutain/vuestore/node_modules/vue/dist/vue.runtime.common.prod.js:6:2394
2|server   |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
2|server   | 2021-05-27 12:55:45: cache tags for the request: P5896 product C10110 C5786
2|server   | 2021-05-27 12:55:45: HTML Minifier is enabled
2|server   | 2021-05-27 12:55:46: whole request [/londres-mountain-grey-luxury-click-vinyl-flooring-4mm.html]: 9773ms

```

![image](https://user-images.githubusercontent.com/26646476/119791339-2d833700-beee-11eb-8840-29f28c2c77d8.png)

## Expected behavior

It should not be throwing erros in pm2 logs.

![image](https://user-images.githubusercontent.com/26646476/119791655-71763c00-beee-11eb-899d-1e2406cc6418.png)

## Steps to reproduce the issue

Run the application in production mode using `yarn && yarn build && yarn start

## Version of Vue Storefront
- [x] Vue Storefront (1.12.2)
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: chrome, 89.0.4389.90 (Official Build) (64-bit)
- OS: ubuntu 20.04
- Node: 12.14.1
- Code Version: 1.12.2

**Comment by Fifciu** [comment]
Which theme? Have you applied any changes or it is a clear VSF1.12.2?
