### ISSUE TITLE
Strapi Integration

### ISSUE THREAD

**Issue by RikkiMasters** [vuestorefront/vue-storefront#5956]
It would be great if there was out-of-the-box support for Strapi. It would be a good combo in the headless world.

Strapi v4 is just around the corner with its revamped plugin system, so it might be possible to build a Vue Storefront eCommerce plugin that standardizes the data.

Both front and backend would be open source, Javascript based, and modern. (Magento is the only other supported backend that is open source?)

The prospect of modifying Magento for my needs isn't appealing. Strapi + Meilisearch work great.

**Comment by dimasch** [comment]
@RikkiMasters Awesome! Thanks for idea!

The Strapi integration looks like extension or module for the VSF.  The Strapi allows you to create and link different entities, I do not understand in what form even the extension can be implemented. For cms blocks by analogy with Magento?

Now we need a clear understanding of what functionality we want to do.

**Comment by bloodf** [comment]
This issue has been closed due to inactivity. 

If you want to re-open the issue, please re-create the issue, and post newer information on this problem.
