### ISSUE TITLE
Compare at price shows as 0 when it's empty

### ISSUE THREAD

**Issue by mariusa** [vuestorefront/vue-storefront#5989]
## Current behavior

Using Shopify integration
Compare at price is empty. 
VSF shows
![2021-06-14_11-59](https://user-images.githubusercontent.com/1283842/121866814-f8f1e680-cd07-11eb-9504-f50b8888417d.png)

![2021-06-14_11-56](https://user-images.githubusercontent.com/1283842/121866562-b4664b00-cd07-11eb-92b9-d631e25a22b7.png)

## Expected behavior

No compare at price shown, just the regular price
![2021-06-14_11-57](https://user-images.githubusercontent.com/1283842/121866599-bfb97680-cd07-11eb-9675-b3a058e6fa28.png)

## Steps to reproduce the issue

1. Configure VSF to use a Shopify store
2. Go to collection and product detail page 

## Version of Vue Storefront

- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer. (doesn't apply to Next)
Pick one option.

This is for current https://github.com/vuestorefront/vue-storefront

## Environment details

- Browser: Chrome 
- OS: Linux 
- Node: 14 
- Code Version: https://github.com/vuestorefront/vue-storefront as of now

**Comment by bloodf** [comment]
Hi @mariusa 

Please use the Shopify integration repository for Shopify related question :)

https://github.com/vuestorefront/shopify

I will be closing this issue as this is not related to the VSF Core or Commercetools :)
