### ISSUE TITLE
How to render Shopify Pages?

### ISSUE THREAD

**Issue by mariusa** [vuestorefront/vue-storefront#5991]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Check our forum:
https://forum.vuestorefront.io/

# Is there something you don't understand? What is it? Describe it.	

Shopify store has pages, eg 
https://test.myshopify.com/pages/about

How to render this page in VSF? I tried same URL, but it says Page not found
Doc says it can render Shopify pages by URL, but no example given.

## Keep the problem description concise and include:
- [x] A brief description of the problem,
- [x] Where the problem is occurring,
- [x] The length of time the problem has been occurring,
- [x] The size of the problem.

**Comment by bloodf** [comment]
Hi @mariusa 

Please use the Shopify integration repository for Shopify related question :)

https://github.com/vuestorefront/shopify

I will be closing this issue as this is not related to the VSF Core or Commercetools :)
