### ISSUE TITLE
Cannot add 3rd party plugins to theme

### ISSUE THREAD

**Issue by mateuszrusiecki** [vuestorefront/vue-storefront#6004]
## Current behavior

According to the documentation to import 3rd party plugins I have to register it in /src/themes/default/plugins/index.js , which I have tried to do

```
import firebaseui from 'firebaseui';
```
and I get error:
```
ERROR in ./src/themes/default/index.js
Module not found: Error: Can't resolve 'firebaseui' in '/var/www/src/themes/default'
```

## Expected behavior
the plugin should be registered

## Steps to reproduce the issue
install firebase plugin and add the above code

## Version of Vue Storefront

- [x] Vue Storefront
- [ ] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details

- Browser: Chrome 90
- OS: MacOs Big Sur
- Node: v15.2.1
- VSF: 1.12.2

## Additional information
It happens also for other 3rd party plugins

**Comment by mateuszrusiecki** [comment]
bump

**Comment by mateuszrusiecki** [comment]
bump

**Comment by mateuszrusiecki** [comment]
the issue is that: when I go to src/themes/default and do
`yarn add firebaseui` 
it adds it to package.json, but when I do 
`yarn install` 
it's not creating node_modules in src/themes/default o_O 
How I should install those dependencies then? I need to manage workspaces somehow? I have yarn 1.22, maybe I should use yarn 2? 
I can use npm fot that and then it works but would be better to use yarn it whole project

**Comment by Fifciu** [comment]
Try to add `firebaseui` to theme's package.json and then run `yarn` from the root directory.

**Comment by mateuszrusiecki** [comment]
It should be add to main package.json, not to themes one
