### ISSUE TITLE
Can't find a way to serve precompressed js files (brottli compressed files)

### ISSUE THREAD

**Issue by ouahidiomar** [vuestorefront/vue-storefront#6017]
Hello everyone,

We are trying to imporve the performance of our vue-storefront based application. We found out that one of the solutions is to decrase JS files size. 

After building the WEBAPP and generating compressed files using brotili plugin for webpack, we didn't find a way to serve these static files (existing in the dist directory) using Nginx basic brotli configuration. 

Is there any native solution to serve static compressed files ? 

PS : The nginx configuration works fine with other projects. 

Thanks !

**Comment by bloodf** [comment]
Hi @ouahidiomar you are using VSF1 or VSF2?

**Comment by filipsobol** [comment]
Closing due to invactivity
