### ISSUE TITLE
Cannot find module '@vue-storefront/cache/nuxt' 

### ISSUE THREAD

**Issue by SqrTT** [vuestorefront/vue-storefront#6053]
## Current behavior
![image](https://user-images.githubusercontent.com/1271300/124594418-71137e00-de68-11eb-950c-f667b45e55e7.png)

## Expected behavior
expecting path `@vue-storefront/cache/nuxt` to be existing

## Steps to reproduce the issue
follow steps https://docs.vuestorefront.io/v2/advanced/ssr-cache.html#installation

## Version of Vue Storefront
- [ ] Vue Storefront
- [x] Vue Storefront Next

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

version of "@vue-storefront/cache" is "2.3.4",

**Comment by filipsobol** [comment]
This issue was already fixed in https://github.com/vuestorefront/vue-storefront/pull/6027 and will be available in `2.3.5` and `2.4`

**Comment by SqrTT** [comment]
thank you @filipsobol
