### ISSUE TITLE
Refactor the vue-storefront repository in to separate repos for v1 and v2 & implement proper use of gitflow

### ISSUE THREAD

**Issue by jaydubb12** [vuestorefront/vue-storefront#6101]
## What is the motivation for adding / enhancing this feature?
1. There are technically 2 different projects being maintained in the same repository under different branches, "master" and "next"
2. As a result of the preceding, the team is not actively following a proper utilization of gitflow practices, which makes ongoing dev / contribution much more difficult to manage, maintain and collaborate on.
3. The release/next branch is at current 259 commits BEHIND next which is very concerning, if this is to be an upcoming release candidate. That said, the current version is 2.3.3 per the branch "next" however there is a release 2.3.4.1 which is listed as a patch, but is not yet released....which deviates from the preceding naming convention utilizing the "rc" designation for release candidates

## What are the acceptance criteria 
1. A new repository, under the current npmjs / github org would be created named vuestorefront/vue-storefront2 
2. The next branch will be come "master" and will be tagged with the package / project version of master at the time of release (i.e. 2.3.3 or 2.3.4)
3. The next viable release candidate will be maintained via develop branch which is tagged with the version in process, and will be promoted to a formal release candidate for testing / tracking
4. Developer documentation will be updated to reflect the procedural changes
5. Shared features and modules for v1 / v2 will be maintained in v2, and linked to v1 using git sub repositories to optimize / streamline the process of development and reduce potential for error
6. Build and package publishing processes will be updated and regression tested to validate the change(s)
7.  Release candidate packages will be released under a release branch, and subsequent release candidate branches should be maintained as hotfix branches, and then subsequently merged into the release branch itself vs being maintained as a designated release branch itself (i.e. a forth coming release branch would be set as "release/2.4.3" and any patch / fix to the release branch would be created / maintained as "hotfix/2.4.3.x" and merged into release/2.4.3.

## Version of Vue Storefront

- [X] Vue Storefront
- [X] Vue Storefront Next

## Can you complete this feature request by yourself?

- [ ] YES
- [X] NO - I am willing to contribute, but do not have administrative rights to the overall github, nor do have any other level of privileged access

## Additional information
1. The lack of proper use of gitflow is concerning and confusing...as is the lack of a formal release process, as new commits are being made to BOTH the branch "next" and "next/release"
2. It is concerning and confusing that there is a branch "next/release" and that this branch is 259 commits behind next, but then other release branches AND release candidate branches are maintained
3.  The lack of release notes and versions in Github diminishes confidence and perception of quality for the project / program

**Comment by andrzejewsky** [comment]
Hey, @jaydubb12 The repo organization and "gitflow" is something we discussed internally and at this moment we don't want to change it. The flow we work with right now is completely suitable for us.

Separating repos also is something that we don't want to change (at least not at this moment) - we want to keep the whole community in one place.

The ` release/next` is a branch just for deployments, nothing else. Is being used by us, internally, when we want to deploy something to one of our demos.

Generally speaking, thanks for your engagement and the thoughts you share. The repositories management as well as releasing processes is something that we have to handle inside of VSF company. We don't have just one repository, and the flow we have, we constantly improve to our needs and also the community. We need to develop something that works for fully us along with all of ours projects. Let us improve it, according also to our needs, not just to general "gitflow" and its rules. Thanks!. Closing.

**Comment by jaydubb12** [comment]
@patzick The current next branch has v2.3.3, the npmjs registry shows that that v2.3.4 was published a month ago, and there is currently a v2.3.4.1 release in the branch set / repository (see screenshot).  And so when I see this, and then am working or reviewing other related projects such as the shopify project that is not part of the monorepo...one starts to feel as if they are chasing their tail a bit when it comes to wanting to properly collaborate and support the project, while also effectively managing downstream projects.
