### ISSUE TITLE
Refactor the commercetools impl to be a git submodule vs principle in the vue-storefront/core repository

### ISSUE THREAD

**Issue by jaydubb12** [vuestorefront/vue-storefront#6102]
## What is the motivation for adding / enhancing this feature?
1. The vue-storefront platform is expanding, as in order to better maintain the core repository, it is recommended to ...

- Have a consistent paradigm for referencing / maintaining commerce implementations
- Letting the "boilerplate" provide the sample site and data
- Provide ease of access to developers to the external repos via git submodules or choose to embed the all of the commerce integrations in a single sub-directory in the mono-repo 

2. Improve the use / potential of the boilerplate project to be more than a reference 

## What are the acceptance criteria 
1. Ability for a developer to clone / work out of the core repository without having to download the commercetools package by default
2. Ability for the boilerplate project and core projects to be more autonomous in their construct & maintenance and to provide more flexibility & autonomy to the commercetools platform

## Version of Vue Storefront

- [ ] Vue Storefront
- [X] Vue Storefront Next

## Can you complete this feature request by yourself?

- [ ] YES
- [X] NO - I do not have github repository mgt access

## Additional information
1.  There is already a commercetools repo, but it appears to be currently used....which is a cause for confusion and potential other issues, especially given the referenced repo is not being updated / maintained in sync with change - https://github.com/vuestorefront/commercetools

**Comment by filipsobol** [comment]
In the coming weeks, we plan to move our commercetools integration and boilerplate template into separate repositories. This repository will contain only core packages, i.e., those in the `packages/core` folder.
