### ISSUE TITLE
Type 'null' is not assignable to type 'string'

### ISSUE THREAD

**Issue by SqrTT** [vuestorefront/vue-storefront#6129]
## Current behavior
TS error reported on the next line

https://github.com/vuestorefront/vue-storefront/blob/next/packages/commercetools/api-client/src/helpers/search/index.ts#L111

## Expected behavior
No TS error

**Comment by bloodf** [comment]
@SqrTT can you please recheck the line as it have changed, or post the code sample or error :)

**Comment by SqrTT** [comment]
thank you @bloodf  for replay. Seems file were updated

the issue is here

![image](https://user-images.githubusercontent.com/1271300/132309293-03d87fd4-4c97-479c-9bd6-823014165076.png)
