### ISSUE TITLE
Make api-client available inside extension's call hooks

### ISSUE THREAD

**Issue by Fifciu** [vuestorefront/vue-storefront#6158]
# Summary
[summary]: #summary

Let's make api-client available inside extension's hooks.

# Motivation
[motivation]: #motivation

With this feature, we would be able to modify api-client's object before call - e.g. check for authorization cookie and add proper header there instead of checking it in every endpoint's code of api-client.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

You can operate on api client's instance from your extension's hook so you can prepare a better architecture of your integration by delegating tasks like attaching some data from cookies to the extension.

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation
We would need to add value of `settings.client` to some field inside `e.beforeCall` and `e.afterCall` call.
```ts
// @vue-storefront/core/src/factories/apiClientFactory/index.ts
const extensionHooks = {
  before: (params) => lifecycles
    .filter(e => isFn(e.beforeCall))
    .reduce((args, e) => e.beforeCall({ ...params, configuration: settings.config, args}), params.args),
  after: (params) => lifecycles
    .filter(e => isFn(e.afterCall))
    .reduce((response, e) => e.afterCall({ ...params, configuration: settings.config, response }), params.response)
};
```

Example implementation:
```ts
// @vue-storefront/core/src/factories/apiClientFactory/index.ts
const extensionHooks = {
  before: (params) => lifecycles
    .filter(e => isFn(e.beforeCall))
    .reduce((args, e) => e.beforeCall({ ...params, configuration: settings.config, client: settings.client, args}), params.args),
  after: (params) => lifecycles
    .filter(e => isFn(e.afterCall))
    .reduce((response, e) => e.afterCall({ ...params, configuration: settings.config, client: settings.client, response }), params.response)
    };
```

# Drawbacks
[drawbacks]: #drawbacks

Why should we *not* do this?
Case with modifying headers is only one I see now. There would be definitely more cases if hooks were asynchronous. 

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

- Why is this design the best in the space of possible designs?
We might want to create extension to modify instance of client - e.g. adding auth headers.
- What other designs have been considered and what is the rationale for not choosing them?
We could put client inside config object and use same instance as `client`. Then we could access it from hooks via `configuration.client` - however, it is not so elegant
- What is the impact of not doing this?
We have to use workaround described in earlier answer - e.g. @Mateuszpietrusinski was forced to do it yesterday.

**Comment by Baroshem** [comment]
Cool idea! Definitely worth trying! :)

**Comment by skirianov** [comment]
Issue is closed. Reason: Too Old (>6 months)

---

Sergii Kirianov

Developer Advocate

Vue Storefront
