### ISSUE TITLE
TypeScript errors are only shown in IDE

### ISSUE THREAD

**Issue by wirtsi** [vuestorefront/vue-storefront#6188]
# Typescript errors not  shown

I cloned the latest version of this repo from gitlab and changed the strict mode to true and added noImplicitAny to the packages/tsconfig.base.js file.

My IDE gets this

![image](https://user-images.githubusercontent.com/276751/129346220-a3a3e743-24e5-485f-a049-244f19639e79.png)

But i would like to see this error also in the console that is running nuxt ... but it compiles happily

```
✔ Client
  Compiled successfully in 11.57s

✔ Server
  Compiled successfully in 10.66s

No issues found.

```

I found some [issues](https://github.com/nuxt/typescript/issues/283) at the nuxt repo but both solutions are not giving me any output. Could it be that vue-storefront is doing something with the typescript implementation?

**Comment by bloodf** [comment]
To add errors on Nuxt, you need to configure the nuxt to add type checking and other configurations

https://typescript.nuxtjs.org/guide/setup#module-options

**Comment by wirtsi** [comment]
Judging by the link you posted, typescript checking should be enabled by default. Checking pstree on a running `yarn run dev:ct` gives me

```
 | | \-+= 67898 user node /opt/homebrew/bin/yarn run dev:ct
 | |     \-+- 67900 user /opt/homebrew/Cellar/node@14/14.17.6/bin/node /opt/homebrew/bin/yarn dev
 | |       \-+- 67902 user /opt/homebrew/Cellar/node@14/14.17.6/bin/node /Volumes/Code/typescript/vue-storefront/packages/commercetools/theme/node_modules/.bin/nuxt
 | |         |--- 67917 user /opt/homebrew/Cellar/node@14/14.17.6/bin/node --max-old-space-size=2048 /Volumes/Code/typescript/vue-storefront/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporterRpcService.js
 | |         \--- 67918 user /opt/homebrew/Cellar/node@14/14.17.6/bin/node --max-old-space-size=2048 /Volumes/Code/typescript/vue-storefront/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporterRpcService.js
```
So there are even two fork-ts-checker-webpack-plugin running. It's just that their output seems to be completely ignored
