### ISSUE TITLE
Installation Error 'Module not found'

### ISSUE THREAD

**Issue by romancfischer** [vuestorefront/vue-storefront#6196]
NODE v 12.22.5
YARN v 1.22.5

I followed the official installation guide ( CLI ) on MacOS, which resulted in the following error:

```
Error in ./.nuxt/router.js
Module not found: Error: Can't resolve '../pages/ResetPassword.vue' in '/Users/username/Sites/localhost/website/.nuxt'
```

**Comment by leh08** [comment]
Hi Team, I also have this issue today

**Comment by filipsobol** [comment]
Hi @romancfischer, which integration did you choose during the installation?

**Comment by romancfischer** [comment]
Hi @filipsobol. I chose Shopify (beta)

**Comment by filipsobol** [comment]
Thank you for reporting the issue. While we are working on the fix, you can use the following workaround to run the project:

1. Create a new project using the CLI.
2. Open `package.json` and change the versions of the following packages from `^2.3.3` to `~2.3.3`:
    * ` @vue-storefront/middleware`
    * `@vue-storefront/nuxt`
    * `@vue-storefront/nuxt-theme`
 3. Install dependencies and start the project (`yarn`, then `yarn dev`).

**Comment by romancfischer** [comment]
@filipsobol
Thanks for the quick reply and fix! It works now.

**Comment by filipsobol** [comment]
The issue has been fixed.
