### ISSUE TITLE
[Bug]: Images do not get loaded on iOS mobile devices 

### ISSUE THREAD

**Issue by samberrry** [vuestorefront/vue-storefront#6245]
### Describe the Bug

Hi guys,
I've tested my vue storefront demo: pwa.binshops.com on many ios devices but the images do not get loaded. 
I've also tested the https://demo-ct.vuestorefront.io on iphone devices, same happens. This issue occurs specially on safari, with firefox some images are get loaded but with a lag. 

I did not have a chance to check it deeply. I would be happy if you give it a high priority, we are going to share the demo links with our customers to check the platform. 

Thank you guys.

### Expected behavior

to load images properly

### What version of Vue Storefront are you using?

any

### What version of Node.js are you using?

any

### What browser (and version) are you using?

safari firefox

### What operating system (and version) are you using?

ios - iphone

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
@samberrry bug confirmed :)
