### ISSUE TITLE
Is static site generation possible with V2?

### ISSUE THREAD

**Issue by plenti** [vuestorefront/vue-storefront#6248]
### Provide a description of requested docs changes

I know with nuxt.js static site generation is possible, but it looks like Vue Storefront really depends on SSR. Can I please get some insight into this? 

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
@plenti right now the Vue Storefront 2 does not support the Static Site Generation of Nuxt, but is a feature we are taking a look on it :)

**Comment by plenti** [comment]
Ok, thank you. Also, do you foresee any issues with deploying to AWS Lambda with VSF, similar to what you can do for Nuxt?
(https://epndavis.com/blog/nuxtjs-serverless-side-rendering-on-aws-lambda/)

**Comment by paulcrussell** [comment]
10 months on has there been any update on using SSG with Vue Storefront?

**Comment by filipsobol** [comment]
@paulcrussell Unfortunately, no. It's something we want to explore but is not on our immediate roadmap

**Comment by skirianov** [comment]
Issue is closed. Reason: Too Old (>6 months)

---

Sergii Kirianov

Developer Advocate

Vue Storefront
