### ISSUE TITLE
[Bug]: Closing login window, when you mark incorrectly entered text

### ISSUE THREAD

**Issue by tadrud** [vuestorefront/vue-storefront#6385]
### Describe the Bug

When you mark text in the account details fields when the cursor goes out of the frame, still pressing the left mouse button, the window is unexpectedly closing. 

### Current behavior

the window(pop-up) is unexpectedly closing.

### Expected behavior

the window(pop-up) shouldn't be closed by itself during marking text and moving the cursor out of the window 

### Steps to reproduce

Open login window clicking "person icon" on the top right side of the window. Enter text to password or login field. Mark the written text with pressed Left mouse button. Don't release the left mouse button and move the cursor out of the login window/popup field. 

### What version of Vue Storefront are you using?

vsf2: 2.3.0

### What version of Node.js are you using?

v12

### What browser (and version) are you using?

Chrome 94.0.4606.61 (Official Build) (64-bit)

### What operating system (and version) are you using?

Windows

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Razz21** [comment]
Hi @tadrud, what SFUI version you are using? Try update to latest version first, or pass `persistent=true` prop to login modal.
https://docs.storefrontui.io/?path=/story/components-molecules-modal--persistent
