### ISSUE TITLE
[Bug]: useUserShippingFactory is passing initial shipping value to composables

### ISSUE THREAD

**Issue by sabasayer** [vuestorefront/vue-storefront#6497]
### Describe the Bug

useUserShippingFactory is passing readonlyShipping variables which is unref(shipping). 

shipping variable is reactive, but readonlyShipping is not a computedProp so when any kind of changes happens at the shipping it will not effect the readonlyShipping. It's value will be the initial value. 

This causes some errors.

### Current behavior

variable for shipping that passed to composable methods is readOnlyShipping and it is not reactive. It's not changing when shipping changed. 
In my case shipping is an array of addresses. 

![image](https://user-images.githubusercontent.com/45066901/139256281-5b0f181b-3ac3-4959-b707-6360e4aab18a.png)

### Expected behavior

readonlyShipping variable must be computedProp or shipping must be passed with unref when the methods are called.
addAddress , deleteAddress, updateAddress is using this variable. 

### What version of Vue Storefront are you using?

2.4.4

### What version of Node.js are you using?

14.18.1

### What browser (and version) are you using?

Chrome latest

### What operating system (and version) are you using?

macOs

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skirianov** [comment]
Issue is closed. Reason: Too Old (>6 months)

---

Sergii Kirianov

Developer Advocate

Vue Storefront
