### ISSUE TITLE
I want to integrate laravel as a back end side, please any one explain how to do and any demo for that.

### ISSUE THREAD

**Issue by asadullah-aal** [vuestorefront/vue-storefront#6501]
### Provide a description of requested docs changes

I want to integrate laravel as a back end side,
please any one explain how to do and any demo for that.

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Hi @asadullah-aal.

We have the [Integrating eCommerce platform](https://docs.vuestorefront.io/v2/integrate/integration-guide.html) guide that explains how to integrate backend platforms with Vue Storefront. You can also refer to the source code of our [Supported platforms](https://github.com/vuestorefront/vue-storefront#supported-platforms).

If you need any help, you can join our [Discord server](https://discord.vuestorefront.io/) where we have `#creating-integration` channel dedicated for writing custom integrations.
