### ISSUE TITLE
vue-composition-api.mjs not found

### ISSUE THREAD

**Issue by medspec** [vuestorefront/vue-storefront#6502]
### What is your question / Please describe your issue

Step 1) clean install 
Step 2) yarn dev
-> error 
Module not found: Error: Can't resolve '@vue/composition-api/dist/vue-composition-api.mjs' in '{project dir}/node_modules/vue-demi/lib'

### What version of Vue Storefront are you using?

2.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by readio** [comment]
@medspec I went through this yesterday when creating my first VSF install.

This is the workaround I used. In your **nuxt.config.js** fille add the below:

`import { resolve } from 'path`

`const vueCompositiobnAPIFullpath = resolve("./node_modules/@vue/composition-api/dist/vue-composition-api.esm.js");`

Then create the following alias:

`alias: {
    '@vue/composition-api/dist/vue-composition-api.mjs': vueCompositiobnAPIFullpath,
  }` 

Good luck!

**Comment by medspec** [comment]
@readio Thanks! works like a charm.
