### ISSUE TITLE
 ERROR  VSF Unable to get integration template from git repository[Bug]: 

### ISSUE THREAD

**Issue by lovesgg** [vuestorefront/vue-storefront#6523]
### Describe the Bug

 ERROR  VSF Unable to get integration template from git repository

### Expected behavior

 ERROR  VSF Unable to get integration template from git repository

### What version of Vue Storefront are you using?

1

### What version of Node.js are you using?

1

### What browser (and version) are you using?

1

### What operating system (and version) are you using?

1

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Please specify which eCommerce platform you selected and version of Node you are using.
