### ISSUE TITLE
[Bug]: commercetools useMakeOrder.make Cannot read property 'order' of undefined

### ISSUE THREAD

**Issue by CheStas** [vuestorefront/vue-storefront#6536]
### Describe the Bug

If commercetools api returns an error after  `createMyOrderFromCart` request, the request is successful but the response doesn't have  `order` field and has `graphQLErrors` field. Instead of graphQLErrors message, we observe `useMakeOrder.make Cannot read property 'order' of undefined` error message

### Current behavior

`useMakeOrder` composable doesn't have correct error in error.value.make if any occurs after request to commercetool api

### Expected behavior

check graphQLErrors field from a response and throw an error in any. graphQLErrors should be assigned to error.value.make and provide a useful error message.

### Steps to reproduce

Place an order with useMakeOrder commercetool composable that returns an error. for example, try to place an order with an item in the cart that is out of stock.

### What version of Vue Storefront are you using?

2.4.5

### What version of Node.js are you using?

14.17.2

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Relevant log output

```shell
{"message":"[GraphQL error]: Message: Some line items are out of stock at the time of placing the order: 8505., Location: , Path: order","level":"error","service":"makers","env":"dev"}

ERROR  [VSF][error]:  useMakeOrder.make Cannot read property 'order' of undefined
```

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CheStas** [comment]
the issue affects not only useMakeOrder composable but every composable.
look please at the example with apply coupon code.
![apply coupon 200 response](https://user-images.githubusercontent.com/17459834/148377250-f4a06ca0-4f68-489d-bccd-814ca94fe40f.png)
![apply coupon response body](https://user-images.githubusercontent.com/17459834/148377360-441963c9-902f-410b-acaf-1881cccd1f1a.png)
error log in the console
`useCart/applyCoupon TypeError: Cannot read properties of undefined (reading 'cart')`

and the example with place order
try to place an order with wrong version
![image](https://user-images.githubusercontent.com/17459834/148378027-fd77b70a-608d-47d3-a270-7fff0b71b7ef.png)
but in the console
`useMakeOrder.make TypeError: Cannot read properties of undefined (reading 'order')`

**Comment by filipsobol** [comment]
The open-source version of commercetools integration is no longer supported.
