### ISSUE TITLE
I want to integrate laravel as a back end side, please any one explain how to do and any demo for that.

### ISSUE THREAD

**Issue by asadullah-aal** [vuestorefront/vue-storefront#6542]
### What is your question / Please describe your issue

I want to integrate laravel as a back end side,
please any one explain how to do and any demo for that.

### What version of Vue Storefront are you using?

1.12.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Hi @asadullah-aal. See the [Integrating eCommerce platform](https://docs.vuestorefront.io/v2/integrate/integration-guide.html) doc to learn how to integrate a custom backend platform.

There is also a great video tutorial created by one of our partners explaining it step by step - https://www.youtube.com/watch?v=AhoTlRj8xcs
