### ISSUE TITLE
[Doc] Improve the links in the documentation

### ISSUE THREAD

**Issue by ymaheshwari1** [vuestorefront/vue-storefront#6586]
### Provide a description of requested docs changes

- Link for Layouts and Routing on the project structure is wrong
- `Edit this page` is giving 404

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Fixed in https://github.com/vuestorefront/vue-storefront/pull/6587
