### ISSUE TITLE
[Feature]: add store and language to the context path for multiple store and language

### ISSUE THREAD

**Issue by JasonHao123** [vuestorefront/vue-storefront#6590]
### How the project can be improved?

for SEO, bookmarking, sharing link, it's good to include store and language information in the path for multiple store and/or multiple language. This can be done by adding context path parameter in Store/Locale, this context will be used as root context. then the url will looks like 

https://demo-ct.vuestorefront.io/se/c/women
https://demo-ct.vuestorefront.io/sv_se/c/women

This is inspired by the strategies from big companies for such case.
https://www.nike.com/se/w/kvinnor-rea-klader-3yaepz5e1x6z6ymx6
https://www2.hm.com/sv_se/index.html

### What are the acceptance criteria?

- Open the copied link will get exactly the same as the original.

### Additional information

I'm integrating vue storefront UI 2 with apache ofbiz to replace the old ofbiz ecommerce UI.

### What version of Vue Storefront this feature can be implemented?

2.5.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filrak** [comment]
Happy to inform it works like this! We've added support for multiple languages and locales in 2022. Thanks for the suggestion https://demo-ct.vuestorefront.io/de
