### ISSUE TITLE
[Docs] link pointing to non-existing "Key Concepts" page

### ISSUE THREAD

**Issue by samijaber** [vuestorefront/vue-storefront#6598]
### Provide a description of requested docs changes

in https://docs.vuestorefront.io/v2/ and https://docs.vuestorefront.io/v2/general/installation.html, there are links in the bottom to https://docs.vuestorefront.io/v2/getting-started/key-concepts.html , which is a page that seems to not exist.

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Fixed in https://github.com/vuestorefront/vue-storefront/pull/6601
