### ISSUE TITLE
Refactor imports for types to conform to Typescript spec [Feature]: 

### ISSUE THREAD

**Issue by jaydubb12** [vuestorefront/vue-storefront#6604]
### How the project can be improved?

Utilize the automation provided via eslint to standardize and refactor the import statements for types to conform the to Typescript spec fo "import type" vs the legacy "import"

In addition, it is recommended that "export type" be leveraged for re exports

This paradigm of denoting imports for types was introduced in [Typescript v3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) and was further modified / enhanced in later versions

### What are the acceptance criteria?

- Ability for the eslint profile to detect / warn when a type is imported, but the developer has not used the "import type" paradigm

- Ability for the vuestorefront base code to reflect the recommended syntax of "import type" vs legacy "import" 

- Ability for the vuestorefront base code to reflect the recommended syntax of "export type" to re-export types 

### Additional information

None

### What version of Vue Storefront this feature can be implemented?

2.5.0+

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filrak** [comment]
Thanks for the suggestioN! The commercetools integration was moved to a private repository so I'm closing this issue.
