### ISSUE TITLE
Upgrade Typescript Framework to v4.5 [Feature]: 

### ISSUE THREAD

**Issue by jaydubb12** [vuestorefront/vue-storefront#6605]
### How the project can be improved?

Upgrade the vuestorefront project to Typescript v4.5 to allow for the feature, compilation and other improvements to the base language to be realized & utilized throughout the project such as, but not limited to....

1. Awaited and Promise improvements (v4.5)
2. Performance improvements (v4.3, v4.4)
3. Improve typeahead completion for imports (v4.3)
4. Improved handling of alised conditions, which allows for better downstream recognition, and reduces need for redeclarations in some cases (v4.4)
5. Allowance for symbol and template string patters inde signatures (v4.4)
6. Improvements to the handling of[ optional property types]
(https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) (v4.4)
7. Improved type checking / reduction in errors for generics (v4.3)
8. New flag, useUnknownInCatchVariales that changes default of catch from any to unknown (v4.4)
9. Recognition and allowance of template string types (v4.5)
10. es2022 support that now allows for native support of top-level await
11.  [preserveValueImports](https://www.typescriptlang.org/tsconfig#preserveValueImports) feature for Vue projects such as vue
12. type modifiers for import names (v4.5)
13. Import of type assertions (v4.5)
14. Improved editor support for unresolved types (v4.5)

### What are the acceptance criteria?

- Successful upgrade to v4.5
- Remediation of any issues outlined in the "breaking changes" section of the release notes
- Updated / appended entries to .tsconfig files
- Utilization of eslint auto fix features to employ / deploy quick fixes
- Assessment and validation of typecoverage metrics

### Additional information

See release notes

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html

### What version of Vue Storefront this feature can be implemented?

2.5.0+

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filrak** [comment]
Commercetools repository was moved to a private repository so I'm closing this one.
