### ISSUE TITLE
Upgrade to Nuxt/Vue 3 Plans

### ISSUE THREAD

**Issue by gschema** [vuestorefront/vue-storefront#6619]
### What is your question / Please describe your issue

Is an upgrade to Nuxt/Vue 3 on the Vuestorefront roadmap? If yes, when would that land? Thanks.

### What version of Vue Storefront are you using?

latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Hi @gschema,

We plan to upgrade Vue Storefront 2 to Nuxt 3. However, at this moment, it's not on our roadmap because Nuxt 3 and its ecosystem are not mature enough. Nuxt 3 itself is in beta and not yet production-ready.
