### ISSUE TITLE
addNewAddress show error Cannot read properties of undefined (reading 'setShippingAddressesOnCart 

### ISSUE THREAD

**Issue by sandip-addweb** [vuestorefront/vue-storefront#6624]
### What is your question / Please describe your issue

when i try to add new address in shipping process default vsf2 it does not save on megento backend and show some error as i mention in above image. i used handleAddressSubmit() method for save megento shipping address inter by user in shipping form. can anyone suggest me how can i save shipping form data in megento backend ???

### What version of Vue Storefront are you using?

1.12 with Magento >= v2.4.3 instance for GraphQL endpoint

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Frodigo** [comment]
@sandip-addweb please create an issue (report a bug) in our Magento 2 repository: https://github.com/vuestorefront/magento2

Make sure that you provide steps to reproduce.

Thanks in advance,
Marcin
