### ISSUE TITLE
Remote debugging

### ISSUE THREAD

**Issue by themreza** [vuestorefront/vue-storefront#6648]
### What is your question / Please describe your issue

I'm preparing a remote development environment for Vue Storefront 2 which requires the ability to attach a remote debugger.

I know that Nuxt [can be debugged](https://medium.com/@fernyettheplant/nuxt-js-debugging-for-webstorm-9b4ef5415a5) via the browser's dev tools and by exposing the source maps.

However, I would like to set breakpoints on [server-sided middleware](https://github.com/vuestorefront/vue-storefront/blob/767413e7ae71a47d5643a41f49fb825661ec3f40/packages/core/middleware/src/createServer.ts#L34), such as endpoints for API calls.

I appreciate your recommendations on finding the most efficient way to achieve this :)

### What version of Vue Storefront are you using?

2.5.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Razz21** [comment]
Hi @themreza,
I believe you could use the proxy server, check out this [PR](https://github.com/vuestorefront/vue-storefront/pull/6334/files#diff-2a4ba52b592e202cf4f9638772a23aac52319f9d2d0aa27ded87b9d0fee655e0)

**Comment by themreza** [comment]
@Razz21 Thank you for the suggestion, but I'm looking to set debugger breakpoints rather than capturing the network traffic. I don't think we can debug functions and inspect variables just by intercepting network requests.

**Comment by skirianov** [comment]
Issue is closed. Reason: Too Old (>6 months)

---

Sergii Kirianov

Developer Advocate

Vue Storefront
