### ISSUE TITLE
[RFC]: Supported Node versions

### ISSUE THREAD

**Issue by filipsobol** [vuestorefront/vue-storefront#6665]
Node 12 is reaching its End-of-Life, and we need to upgrade our ecosystem to a newer version to ensure stability and security.

See the [Supported Node versions RFC](https://github.com/vuestorefront/vue-storefront/blob/develop/packages/rfcs/20220302-supported-node-versions/README.md) for the suggested upgrade plan from Node 12 and future support of Node versions.

Please share your thoughts and doubts if you have any.

**Comment by bloodf** [comment]
For me it's fine to be updated.
