### ISSUE TITLE
 Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/vue-composition-api.mjs' is not defined by   "exports" in E:\virtual_work\New folder\Demo\node_modules\@vue\composition-api\package.json

### ISSUE THREAD

**Issue by tortuc** [vuestorefront/vue-storefront#6679]
### What is your question / Please describe your issue

https://docs.vuestorefront.io/v2/general/installation.html
https://docs.vuestorefront.io/storyblok/guide/installation.html

I followed these guide, but this error was appeared and can;'t find the solution.

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/vue-composition-api.mjs' is not defined by   "exports" in E:\virtual_work\New folder\Demo\node_modules\@vue\composition-api\package.json

### What version of Vue Storefront are you using?

3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Hi, which e-commerce platform did you choose in our CLI?
