### ISSUE TITLE
There is any Swell Integration??

### ISSUE THREAD

**Issue by nbpalomino** [vuestorefront/vue-storefront#6723]
### What is your question / Please describe your issue

Hello VSF team,

You are doing an amazing job, I just have a question about Swell headless ecommerce, There is any integration with that??

### What version of Vue Storefront are you using?

2.5.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filrak** [comment]
Hey, unfortunately it's not yet there. We are in discussions with Swell team and we confirmed that we want to build it but I wouldn't expect it to be there any time soon.

at the same time if you or an agency you work with would like to help us building it please let me know! This will speed it up for sure
