### ISSUE TITLE
[BUG]: When I click the "demo" link in the readme, it takes me to a 404 not-found error page.

### ISSUE THREAD

**Issue by notabeatle** [vuestorefront/vue-storefront#6725]
### Provide a description of requested docs changes

At the time of this posting, the Demo link in the project readme leads to an nginx 404 page.

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Thank you for reporting this issue. It was fixed in https://github.com/vuestorefront/vue-storefront/pull/6728
