### ISSUE TITLE
Small typo: Discord server link on README is incorrect in the link list

### ISSUE THREAD

**Issue by jeanlucaslima** [vuestorefront/vue-storefront#6762]
### Provide a description of requested docs changes

The link should be http://discord.vuestorefront.io/ but it just redirects to the Discord homepage. 

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeanlucaslima** [comment]
I know it is just a detail, but sometimes it is the first link someone gets to try when joining the community.

**Comment by filipsobol** [comment]
Thank you so much @jeanlucaslima 🙏 This link should work so we probably wouldn't even notice.

It will be fixed once https://github.com/vuestorefront/vue-storefront/pull/6764 is merged.
