### ISSUE TITLE
Commercetools integration template is missing from generate store command

### ISSUE THREAD

**Issue by petrvecera** [vuestorefront/vue-storefront#6776]
### What is your question / Please describe your issue

Hi guys

I just updated tot he CLI 3.0.0  https://www.npmjs.com/package/%40vue-storefront/cli and when running command `cli generate store` I can't find the template for commerce tools? Are they not longer supported? Or is this a bug? 

![image](https://user-images.githubusercontent.com/8086995/176726316-c33fa74a-332b-472b-bbfb-ca3d87a578b5.png)

Thanks

### What version of Vue Storefront are you using?

CLI 3.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filipsobol** [comment]
Hi @petrvecera 👋,

The commercetools integration is Enterprise-only for a long time now, but wasn't removed from the CLI until yesterday, when we released it's new version.

If you are interested in our Enterprise offering, [reach out to our Sales team](https://www.vuestorefront.io/contact/sales).
