### ISSUE TITLE
After Vue Storefront 2 install with odoo this problem given to me 

### ISSUE THREAD

**Issue by MohammadAtikurRahman** [vuestorefront/vue-storefront#6806]
### What is your question / Please describe your issue

I just follow the normal process of documentation of vuestorefront 2

[
![Captures](https://user-images.githubusercontent.com/46051298/190902765-000fda9c-3b2c-4c94-b2ea-6c0acbae9b38.PNG)
](url)

### What version of Vue Storefront are you using?

Vue Storefront 2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bloodf** [comment]
> ### What is your question / Please describe your issue
> I just follow the normal process of documentation of vuestorefront 2
> 
> [ ![Captures](https://user-images.githubusercontent.com/46051298/190902765-000fda9c-3b2c-4c94-b2ea-6c0acbae9b38.PNG) ](url)
> 
> ### What version of Vue Storefront are you using?
> Vue Storefront 2
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Please use the Odoo integration repository to create the issue. https://github.com/vuestorefront-community/odoo
