### ISSUE TITLE
[Bug]: Open multiple vuestorefront tabs browser crash Page. Help!

### ISSUE THREAD

**Issue by anhhuynd** [vuestorefront/vue-storefront#6813]
### Describe the Bug

On windows machine, I open about 10 website tabs, the last few pages crash. With a machine with stronger ram, the error will be less

### Expected behavior

I hope this bug will be fixed to improve the user experience

### What version of Vue Storefront are you using?

1.12.2

### What version of Node.js are you using?

12.22.1

### What browser (and version) are you using?

Chrome, Safari

### What operating system (and version) are you using?

macOS, Windows

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by filrak** [comment]
Hey, this refers to the old version of Vue Storefront that we no longer maintain.
