### ISSUE TITLE
vsf init command not found 

### ISSUE THREAD

**Issue by TheLucDev** [vuestorefront/vue-storefront#6829]
### What is your question / Please describe your issue

i have a problem when setting up the project , it say the vsf:command not found , i installed vue-cli , vue also but its not working, anyone know it can help me . Thank you so much ! 
<img width="624" alt="Screen Shot 2022-11-11 at 09 53 31" src="https://user-images.githubusercontent.com/83877114/201252909-3b1286a3-0a05-49a8-8c15-09ec603fe952.png">

### What version of Vue Storefront are you using?

v2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashishkpaul** [comment]
npx @vue-storefront/cli generate store

https://www.npmjs.com/package/@vue-storefront/cli
Might be help you

**Comment by filrak** [comment]
The old "init" fn should also work now, so the old merch that has it printed is also up to date ^^

**Comment by skirianov** [comment]
Closing the issue, resolved :)
