### ISSUE TITLE
[Bug]:  npx generate Error: command generate:vue-store not found

### ISSUE THREAD

**Issue by rrubio** [vuestorefront/vue-storefront#6859]
### Describe the Bug

On project creation using "npx" error occurs (see details below) and then exists.

node version - v14.20.0
npm version -  6.14.17

Installation details from - https://docs.vuestorefront.io/v2/getting-started/installation.html

- on execution of "npx @vue-storefront/cli generate vue-store"
- error - Error: command generate:vue-store not found

### Current behavior

Install starts then aborts

### Expected behavior

created project

### Steps to reproduce

Followed instructions from - https://docs.vuestorefront.io/v2/getting-started/installation.html

npx @vue-storefront/cli generate vue-store

### What version of Vue Storefront are you using?

npx version

### What version of Node.js are you using?

v14.20.0

### What browser (and version) are you using?

don't get that far

### What operating system (and version) are you using?

mac os m1

### Relevant log output

```shell
Error: command generate:vue-store not found
```

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jamiewarb** [comment]
Worth noting the docs now say `npx @vue-storefront/cli generate store` rather than `npx @vue-storefront/cli generate vue-store` that's listed above.

**Comment by skirianov** [comment]
Hi @Jamiewarb 👋 

Have this new command `npx @vue-storefront/cli generate store` resolved your problem? 

Please note, that to install dependencies use `yarn` we are working on fixing our docs ASAP. 

______
Sergii Kirianov
Developer Advocate
Vue Storefront

**Comment by skirianov** [comment]
Closing issue, no response for >2 months
