### ISSUE TITLE
how to setup vuex in v2?

### ISSUE THREAD

**Issue by askie** [vuestorefront/vue-storefront#6874]
### Provide a description of requested docs changes

I find the v1 doc: [https://docs.vuestorefront.io/v1/guide/vuex/introduction.html#vuex-conventions](url)
but can't find the v2 doc,
How to develop vuex store on v2 theme?

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skirianov** [comment]
Hi @askie 👋

Can you please ask this question on our [Discord](https://discord.vuestorefront.io/)  channel, our team and community will try to help you.


______
Sergii Kirianov
Developer Advocate
Vue Storefront

**Comment by filrak** [comment]
We don't use Vuex in v2 and don't recommend it but if you want to use it there is nothing stopping you from doing that. Please check the Nuxt guide https://nuxtjs.org/docs/directory-structure/store/
