### ISSUE TITLE
[Bug]: npm install error packages

### ISSUE THREAD

**Issue by andrespaucar** [vuestorefront/vue-storefront#6877]
### Describe the Bug

I can't install the packages
with node v16, v18 and v14

![image](https://user-images.githubusercontent.com/35370608/212120208-eb641a62-4ea0-4fdb-88b1-402fd2ad6221.png)

### Current behavior

error installing packages

### Expected behavior

packages must be installed

### What version of Vue Storefront are you using?

2.5.4

### What version of Node.js are you using?

v14 , v16 and v18

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

windows

### Relevant log output

```shell
-> npm install

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: @vue-storefront/prestashop-theme@1.0.0
npm ERR! Found: babel-jest@27.5.1
npm ERR! node_modules/babel-jest
npm ERR!   dev babel-jest@"^27.3.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer babel-jest@">= 24 < 27" from vue-jest@4.0.1
npm ERR! node_modules/vue-jest
npm ERR!   dev vue-jest@"^4.0.0-0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ASUS\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ASUS\AppData\Local\npm-cache\_logs\2023-01-12T15_18_32_468Z-debug-0.log
```

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrespaucar** [comment]
-> npm run install --force
install the packages but : npm run dev
![image](https://user-images.githubusercontent.com/35370608/212126150-1d18af39-597c-4b8b-a95b-4a4af0ca2c9a.png)

**Comment by skirianov** [comment]
Hi @andrespaucar 👋

Can you please try to remove the `node_modules` folder and `package-lock.json` file and install dependencies using `yarn`? 

Let me know if that works, we will update our docs accordingly.


_____
Sergii Kirianov
Developer Advocate
Vue Storefront

**Comment by skirianov** [comment]
@andrespaucar Awesome! 

Please check the integration-specific docs, they are correct (we will fix the main page ASAP).

I'm closing the issue 💚 

____ 
Sergii Kirianov
Developer Advocate
Vue Storefront
