### ISSUE TITLE
Errors upon installation

### ISSUE THREAD

**Issue by JeffreyArts** [vuestorefront/vue-storefront#6887]
### Provide a description of requested docs changes

I am getting 2 errors when I try to execute `npm run dev`, after I installed a Shopify themed vue-storefront via the `npx @vue-storefront/cli generate store` command according the [installation page](https://docs.vuestorefront.io/v2/getting-started/installation.html)

I am using:

node version: 14.19.0
npm version: 6.14.16

The error messages that I receive are:
Must use import to load ES Module: (...)/node_modules/@glidejs/glide/dist/glide.js require() of ES modules is not supported. require()
Since the documentation says to switch to node v14, I am uncertain of how this errror can be resolved. Is this a bug in the installation process? Or a typo in the documentation?

The other error is
WARN  You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js

An error that I was pretty sure of to move away when I would create a [postcss.config.js](https://github.com/postcss/postcss#usage) in the root directory, but unfortunately no. Given that there are so many pre-configured plugins installed in this project. I am curious why the postcss.config.js is not being added automatically.

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jesuismaxime** [comment]
Lil bump. Is there any lead on that issue? Wanted to test out VSF but I am unable to install it. I tried multiple installations and was able to run it only once but can't remember which combination I used. But so far the documentation' requirements lead to that same Glide error.

**Comment by MarciB-IT** [comment]
Push again, having the same issue.

**Comment by smonkey72** [comment]
I've got the same error, using `npm i` instead of `yarn` to install dependencies. I've tried again with `yarn` and everything works fine.

**Comment by randomnessdev** [comment]
Same issue here, using Yarn doesn't solve the problem

**Comment by jesuismaxime** [comment]
@smonkey72 would you care to share your yarn/node/etc versions?

**Comment by smonkey72** [comment]
@jesuismaxime I tried Node `v14.20.0` with npm `v6.14.7`, Node `v18.9.0` with npm `v8.9.1` and finally Node `v14.20.0` and yarn `1.22.19`

**Comment by DavidDeSloovere** [comment]
So frustrating that the initial setup isn't working as documented.
**How are we (new users) expected to try, use and like VSF?** 
There will be revenue lost, if you can't even try basic things, why would you pay for other features.

**Comment by skirianov** [comment]
Hey 👋 

Vue Storefront Developer Advocate here 🙌 

First of all, I would like to say sorry on behalf of Vue Storefront for not responding to this issue for so long. 
____ 

Now, to the question. I believe our docs are outdated and were not fixed, I will make sure it's fixed ASAP. 

To install the project from the CLI, please use Yarn and Node.js >= 16.13 and <17.

I will force to update the docs soonest. Let me know if that worked.

**Comment by DavidDeSloovere** [comment]
The docs have been updated. That's great. 
Just to be clear, yarn is required and npm is not supported? (if so, hope this changes with the next release)
Might be good to explicitly mention this on the docs. To avoid confusion. I would think that it doesn't matter which one you use.

**Comment by skirianov** [comment]
Hey @DavidDeSloovere - yes, docs are updated :) 

As you can see as per latest release of SFUI2 we are trying to become framework agnostic and this does mean npm/yarn/pnpm support too :)
