### ISSUE TITLE
[Feature]: Upgrade to Nuxt 3

### ISSUE THREAD

**Issue by sthiepaan** [vuestorefront/vue-storefront#6892]
### How the project can be improved?

Nuxt 3 was released as a **stable** version 16th of November 2022.
Is there any chance to upgrade _VueStorefront_ to use recent version?

### What are the acceptance criteria?

- [ ] VueStorefront use Nuxt v3

### Additional information

There are vary of requests for such upgrade / migration at #5335 Issue.

### What version of Vue Storefront this feature can be implemented?

2.x.x

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skirianov** [comment]
Hi @sthiepaan 👋 

Sergii, Dev Advocate of Vue Storefront here 🙌 

As of now, we do not have any plans on migrating current architecture to Nuxt 3, but I can assure that we will have something new for Nuxt 3 in the next few month, we are working hard on it right now ;)

**Comment by aimeb1** [comment]
Does today's news on the new release mean Nuxt 3 is now supported?

**Comment by skirianov** [comment]
> Does today's news on the new release mean Nuxt 3 is now supported?

Hey 👋

Storefront UI does support Nuxt and Vue 3, but Vue Storefront itself does not yet. We are working on it and you should be able to get more news closer to the end of April 😊

**Comment by readio** [comment]
Hey @skirianov Are there any further updates on when Nuxt and Vue 3 will be supported?

We are currently developing a large project with an upcoming deadline that requires some custom integrations. We do not want to spend time/resources creating these with Nuxt 2 modules if Nuxt 3 is close.

Any info would be greatly appreciated.

**Comment by rohrig** [comment]
Hi @readio, you can take a look at this timeline https://github.com/orgs/vuestorefront/projects/4

**Comment by Zielgestalt** [comment]
@rohrig I get a 404 error for this link

**Comment by rohrig** [comment]
I've opened up an issue internally to get the permission adjusted.

**Comment by aimeb1** [comment]
404's suspense, killing me fast,
Access denied, a mysterious cast.
Permissions refused, I'm left in the dark,
In suspense I dwell, awaiting a spark.
Creds: LLM

**Comment by readio** [comment]
@rohrig Any further updates on this?

**Comment by aimeb1** [comment]
Maybe just  a screenshot of the timeline since we still can't get access via the link?

**Comment by DavidDeSloovere** [comment]
Still 404. Any update that can be shared?

**Comment by aimeb1** [comment]
About to start a large project using VSF but willing to defer a bit longer if if we knew Nuxt 3 support was close. Any feedback appreciated @rohrig.

**Comment by rohrig** [comment]
Hi everyone, 
After come consideration, we decided against the roadmap. But there is great news. We have published the new Magento 2 integration! 🎊  
Please see the [magento2 sdk docs](https://docs.vuestorefront.io/sdk-magento2/).The new integration is framework agnostic. It will serve as the basis for all Storefronts in various Frameworks.

 Nuxt 3 will the first open source, Vue Storefront backed storefront to use this new integration. I'm beginning work on this storefront [here](https://github.com/vuestorefront/nuxt3-magento-sdk-storefront). It will take some time to reach the level of the pervious integration. All are welcome to contribute. 

I'll be documenting the progress so leave a star on the repo and check out our [youtube channel](https://www.youtube.com/channel/UCkm1F3Cglty3CE1QwKQUhhg) for regular updates. 

All the best 👋

**Comment by simonmaass** [comment]
is there any current project with nuxt 3?

**Comment by giorgiopogliani** [comment]
@simonmaass I am using it on nuxt 3, what integration are interested in?

**Comment by simonmaass** [comment]
@giorgiopogliani magento 2
