### ISSUE TITLE
[Bug]: NPX installation script

### ISSUE THREAD

**Issue by JeffreyArts** [vuestorefront/vue-storefront#6901]
### Describe the Bug

When I install a new vuestorefront application, it installs succesfully. But with a lot of outdated packages.

warning " > @storefront-ui/vue@2.0.0" has unmet peer dependency "vue@^3.2.47".
warning "@storefront-ui/vue > @vueuse/core > vue-demi@0.13.11" has unmet peer dependency "vue@^3.0.0-0 || ^2.6.0".
warning "@storefront-ui/vue > @floating-ui/vue@0.2.1" has unmet peer dependency "vue@^2.0.0 || >=3.0.0".
warning "@storefront-ui/vue > @storefront-ui/tailwind-config > @storefront-ui/tw-plugin-peer-next@2.0.0" has unmet peer dependency "tailwindcss@>=3.0.0 || >= 3.0.0-alpha.1".
warning "@storefront-ui/vue > @storefront-ui/tailwind-config > @mertasan/tailwindcss-variables@2.6.1" has unmet peer dependency "autoprefixer@^10.0.2".
warning "@storefront-ui/vue > @storefront-ui/tailwind-config > @mertasan/tailwindcss-variables@2.6.1" has unmet peer dependency "postcss@^8.0.9".
warning "@vue-storefront/nuxt > @nuxtjs/composition-api@0.29.3" has unmet peer dependency "@nuxt/vue-app@^2.15".
warning "@vue-storefront/nuxt > @nuxtjs/composition-api@0.29.3" has unmet peer dependency "vue@^2".
warning "@vue-storefront/nuxt > @nuxtjs/composition-api > @vue/composition-api@1.7.1" has unmet peer dependency "vue@>= 2.5 < 2.7".
warning "@vue-storefront/nuxt > nuxt-purgecss > purgecss-webpack-plugin@2.3.0" has unmet peer dependency "webpack@*".
warning "@vue-storefront/nuxt > @nuxt/typescript-build > ts-loader@8.4.0" has unmet peer dependency "webpack@*".
warning "@vue-storefront/nuxt > @nuxt/typescript-build > fork-ts-checker-webpack-plugin@6.5.3" has unmet peer dependency "webpack@>= 4".
warning " > @vue-storefront/nuxt-theme@2.5.6" has unmet peer dependency "@nuxtjs/composition-api@^0.29.3".
warning " > @vue-storefront/shopify@1.1.4" has unmet peer dependency "@nuxtjs/composition-api@0.29.3".
warning "@vue-storefront/shopify > @vue-storefront/shopify-api > @nuxtjs/composition-api@0.30.0" has unmet peer dependency "@nuxt/vue-app@^2.15".
warning "@vue-storefront/shopify > @vue-storefront/shopify-api > @nuxtjs/composition-api@0.30.0" has unmet peer dependency "vue@^2".
warning "@vue-storefront/shopify > @vue-storefront/core@2.5.6" has unmet peer dependency "@nuxtjs/composition-api@^0.29.3".
warning "nuxt > @nuxt/components@2.2.1" has unmet peer dependency "consola@*".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "vue-jest > @babel/plugin-transform-modules-commonjs@7.21.2" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > vee-validate@3.4.15" has unmet peer dependency "vue@^2.5.18".
warning " > @vue/test-utils@1.3.4" has unmet peer dependency "vue@2.x".
warning " > @vue/test-utils@1.3.4" has unmet peer dependency "vue-template-compiler@^2.x".
warning " > babel-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > vue-jest@4.0.1" has unmet peer dependency "@babel/core@7.x".
warning " > vue-jest@4.0.1" has incorrect peer dependency "jest@26.x".
warning " > vue-jest@4.0.1" has unmet peer dependency "vue@^2.x".
warning " > vue-jest@4.0.1" has unmet peer dependency "vue-template-compiler@^2.x".

### Current behavior

All of these packages have newer versions available:

| Package name | package.json version | Yarn.lock (installed) version | Latest NPM version |
| --- | --- | --- | --- |
| @storefront-ui/vue | 0.12.0 | 0.12.3 | 2.0.0 |
| @vue-storefront/shopify | 1.1.2 | 1.1.2 | 1.1.4 |
| @vue-storefront/middleware | 2.5.6 |  2.5.6 | 2.7.5 |
| @vue-storefront/nuxt | 2.5.6 |  2.5.6 | 2.7.5 |
| @vue-storefront/nuxt-theme |  2.5.6 |  2.5.6 | 2.7.5 |
| babel-jest | 24.1.0 | 24.9.0 & 27.5.1 | 29.5.0 |
| vee-validate | 3.2.3 | 3.4.14 | 3.4.15* |
| @vue/test-utils | 1.0.0-beta.27 | 1.3.0 | 29.5.0 |
| vue-jest |  4.0.0-0 |  4.0.1 | 3.0.7 |
| nuxt | 2.13.3 | 2.15.8 | 2.16.3 |

* Latest version is 4.8.4, but that one is meant for Vue 3

### Expected behavior

When I install vue-storefront with shopify, I expect that all the packages it depends on are up to date. So I can rule out that any issues are related to outdated packages 🙂

### Steps to reproduce

Install a new vuestorefront with Shopify, by running `npx @vue-storefront/cli generate store`. Make sure that you use node [>= v16.13 & <= v17.0](https://github.com/vuestorefront/vue-storefront/issues/6887#issuecomment-1482659708) for installation, and install all the npm packages with yarn

### What version of Vue Storefront are you using?

Whatever @vue-storefront/cli is using

### What version of Node.js are you using?

v16.14.0

### What browser (and version) are you using?

-

### What operating system (and version) are you using?

macOS

### Relevant log output

Uncertain if this question belongs here, or [over here](https://github.com/vuestorefront/cli-integrations)

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xXWarMachineRoXx** [comment]
Its not a error tho @JeffreyArts .
