### ISSUE TITLE
[Bug]: [Integrator] Odoo publish @vuestorefront/odoo error

### ISSUE THREAD

**Issue by odranoelBR** [vuestorefront/vue-storefront#6906]
### Describe the Bug

The github action publish npm package is not working.

We can't update github workflow configuration / envs.

### Current behavior

Error on publish.
![Screenshot from 2023-04-23 19-14-29](https://user-images.githubusercontent.com/7774534/233869004-be9309a2-48ba-4cce-9926-4b4b883c323c.png)

![Screenshot from 2023-04-23 19-17-20](https://user-images.githubusercontent.com/7774534/233869087-dd744347-b634-45e9-8acb-170f7bfae034.png)

### Expected behavior

Publish the new version.

### Steps to reproduce

Run the github action workflow from DEV branch.
https://github.com/vuestorefront-community/odoo/actions/workflows/publish.yml

### What version of Vue Storefront are you using?

2.7.5

### What version of Node.js are you using?

16

### What browser (and version) are you using?

Chrome Version 111.0.5563.146

### What operating system (and version) are you using?

Linux ubuntu 22

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rohrig** [comment]
@odranoelBR I updated the npm token. The issue appears to be fixed. Let me know if there are more issues. 😄 
![image](https://user-images.githubusercontent.com/45824492/235136592-55239602-1954-416d-99b7-35b966b93886.png)
![image](https://user-images.githubusercontent.com/45824492/235136757-1d11c4d3-efba-4aa6-a31f-a83f9307c340.png)

**Comment by odranoelBR** [comment]
Tks @rohrig !

**Comment by odranoelBR** [comment]
@rohrig we have the same problem on api layer @vue-storefront/odoo-api.
Can you do the same ? tks

**Comment by odranoelBR** [comment]
![Screenshot from 2023-04-29 09-56-00](https://user-images.githubusercontent.com/7774534/235303606-f88b48b8-493c-4313-9a49-166232e99641.png)

**Comment by rohrig** [comment]
@odranoelBR please link the repository 😄

**Comment by rohrig** [comment]
@odranoelBR Nevermind, I realized my mistake. 😄  I updated the token to allow publishing the api.

**Comment by rohrig** [comment]
In a year, we'll need to update this again. @odranoelBR please add a reminder and create an issue when this time approaches. 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/45824492/235318862-b36366a0-c91d-45a8-aa83-92c8c8c36b85.png">
