### ISSUE TITLE
CLI w/ custom integration: git repository url error

### ISSUE THREAD

**Issue by DavidDeSloovere** [vuestorefront/vue-storefront#6920]
### What is your question / Please describe your issue

When choosing a custom integration we get the question "What's the URL of the custom integration's git repository?"?

I get **Couldn't locate git repository with the received URL.** when I pass in `https://github.com/propeller-commerce/vuestorefront.git`

What is the CLI looking for exactly? What is wrong with the URL?

### What version of Vue Storefront are you using?

latest cli 4.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skirianov** [comment]
Hey @DavidDeSloovere, looking into it.

**Comment by skirianov** [comment]
Handled in PR #6923 - will update the package soon.

**Comment by skirianov** [comment]
https://www.npmjs.com/package/@vue-storefront/cli/v/4.2.1 - @DavidDeSloovere you can try with the latest CLI. 

It was working well with custom integration, unfortunately the console.log was wrong
