### ISSUE TITLE
[Feature]: Show CLI version in CLI output

### ISSUE THREAD

**Issue by DavidDeSloovere** [vuestorefront/vue-storefront#6921]
### How the project can be improved?

Showing the CLI version can be useful when submitting issues. That way it's 100% clear what version is used.

![image](https://github.com/vuestorefront/vue-storefront/assets/352626/f7dc823d-9535-4e10-9033-e809c0aedbec)

### What are the acceptance criteria?

- [ ] Show version in "Welcome" message

### Additional information

I know there is a message so notity about upgrades. But screenshot or output can be copied when the new version wasn't out yet.

### What version of Vue Storefront this feature can be implemented?

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rohrig** [comment]
Hi, @DavidDeSloovere 👋 , with `npx @vue-storefront/cli` you can get the version. 
![image](https://github.com/vuestorefront/vue-storefront/assets/45824492/dd323a56-7878-49f7-a689-cf91b5c929a0)

Does that solve the issue?

**Comment by DavidDeSloovere** [comment]
Although that is useful, and thanks for pointing that out, my use case is more for grabbing output from the `init` command where I run into errors to create GH issues here :-) 
I just happen to run into a lot errors.
