### ISSUE TITLE
getting error while installing VSF using cli.

### ISSUE THREAD

**Issue by tajdev1** [vuestorefront/vue-storefront#6922]
### What is your question / Please describe your issue

Hi,

I am trying to install VSF2 using the documentation. but while installing I am getting the following error.

```
Error: ENOTDIR: not a directory, rmdir '/media/tajdev/01D6E742CE302D90/Wo
    rk/Modern-Squared/modernsquared/.env.example'
    Code: ENOTDIR
```
Also, I tried to install Magento docker, but it gave Python errors. 

OS: ubuntu 22.04.2 LTS
Node version: 16.19.1
npm version: 8.19.3

### What version of Vue Storefront are you using?

2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by skirianov** [comment]
Answered on Discord. Do you want to keep discussion here?
