### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by mattbrailsford** [vuestorefront/vue-storefront#6938]
### Environment

Demo store

### Reproduction

Out of the box

### Describe the bug

In reviewing the vue storefront demo project for an implementation, I'm finding a few layout issues a problem.

1. Carousel text overlaps image on homepage

![image](https://github.com/vuestorefront/vue-storefront/assets/527305/1fe74b3d-8fc6-4983-96ce-74713c5f32ac)

2. Homepage banner text overflows into images

![image](https://github.com/vuestorefront/vue-storefront/assets/527305/6ac9177d-707e-4b5a-92a0-8a0f1e891104)

3. Logo touches the left hand side, and country/cart icons go behind scrollbars (I think it should have some padding either side)

![image](https://github.com/vuestorefront/vue-storefront/assets/527305/9b30add4-4c60-400b-bbf8-fa726eead0ba)

4. I'm not sure if this is by design, but the quantity fields in the cart dialog overlap the image stopping you from seeing the product image well

![image](https://github.com/vuestorefront/vue-storefront/assets/527305/ccb56d4d-24ca-453f-9cdf-f4090a036426)

5. In the same cart, there seem to be some attributes attached to the Smith Journal entry when added to cart which causes disappear on rollover causing the quantity field to jump

![image](https://github.com/vuestorefront/vue-storefront/assets/527305/9d3304ba-d7f2-478c-9e74-93770f9a3c05)
![image](https://github.com/vuestorefront/vue-storefront/assets/527305/6c1966cd-0a3b-44bf-912d-24e9cff5745e)

6. There is a lack of padding in the search box so the text touches the side

![image](https://github.com/vuestorefront/vue-storefront/assets/527305/43b6dd8d-d79d-4cfc-8df2-8337bbdd85ab)

7. Inconsistent bottom margin on homepage newsletter banner

![image](https://github.com/vuestorefront/vue-storefront/assets/527305/c090545b-af16-44ef-9ede-3cbfa943e36d)

8. Banner text overflowing on mobile 

![IMG_0632](https://github.com/vuestorefront/vue-storefront/assets/527305/19655f40-701d-4df2-847e-acda1d5d3654)

**Comment by filrak** [comment]
Related to the old demo, so I'm closing.

Thanks for reporting though!
