### ISSUE TITLE
Integrate into exisiting Nuxt project

### ISSUE THREAD

**Issue by bastianhilton** [vuestorefront/vue-storefront#6966]
### Describe the feature

I'm wondering is it possible to integrate vue-storefront into an exisiting Nuxt project?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://github.com/vuestorefront/.github/blob/main/CONTRIBUTING.md).
- [X] Check existing discussions and issues.

**Comment by rohrig** [comment]
Hi @bastianhilton 👋 , the short answer is yes. Our SDK is framework agnostic, which means you can use it in any frontend framework that uses javascript/typescript. You can read more about it here: https://docs.vuestorefront.io/
